// Package oapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.1 DO NOT EDIT.
package oapi

import (
	"bytes"
	"compress/gzip"
	"context"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"path"
	"strings"

	externalRef0 "github.com/antflydb/antfly-go/libaf/chunking"
	externalRef1 "github.com/antflydb/antfly-go/libaf/logging"
	externalRef2 "github.com/antflydb/antfly-go/libaf/s3"
	externalRef3 "github.com/antflydb/antfly-go/libaf/scraping"
	"github.com/getkin/kin-openapi/openapi3"
	"github.com/oapi-codegen/runtime"
)

// Defines values for ConfigModelStrategies.
const (
	ConfigModelStrategiesBounded ConfigModelStrategies = "bounded"
	ConfigModelStrategiesEager   ConfigModelStrategies = "eager"
	ConfigModelStrategiesLazy    ConfigModelStrategies = "lazy"
)

// Defines values for GPUMode.
const (
	GPUModeAuto   GPUMode = "auto"
	GPUModeCoreml GPUMode = "coreml"
	GPUModeCuda   GPUMode = "cuda"
	GPUModeOff    GPUMode = "off"
	GPUModeTpu    GPUMode = "tpu"
)

// Defines values for ImageURLContentPartType.
const (
	ImageURLContentPartTypeImageUrl ImageURLContentPartType = "image_url"
)

// Defines values for TextContentPartType.
const (
	TextContentPartTypeText TextContentPartType = "text"
)

// Chunk A chunk of text with position information.
type Chunk = externalRef0.Chunk

// ChunkConfig Configuration for chunking requests to Termite API.
// This is a simplified config for the HTTP API - differs from the full ChunkerConfig
// which includes provider selection and caching configuration.
type ChunkConfig struct {
	// MaxChunks Maximum number of chunks to return
	MaxChunks int `json:"max_chunks,omitempty,omitzero"`

	// Model The chunking model to use. Either 'fixed' for simple token-based chunking, or a model name from models/chunkers/{name}/.
	Model string `json:"model,omitempty,omitzero"`

	// OverlapTokens Number of overlapping tokens between chunks
	OverlapTokens int `json:"overlap_tokens,omitempty,omitzero"`

	// Separator Text separator for fixed chunking
	Separator string `json:"separator,omitempty,omitzero"`

	// TargetTokens Target number of tokens per chunk
	TargetTokens int `json:"target_tokens,omitempty,omitzero"`

	// Threshold Confidence threshold for ONNX models (0.0-1.0)
	Threshold float32 `json:"threshold,omitempty,omitzero"`
}

// ChunkRequest defines model for ChunkRequest.
type ChunkRequest struct {
	// Config Configuration for chunking requests to Termite API.
	// This is a simplified config for the HTTP API - differs from the full ChunkerConfig
	// which includes provider selection and caching configuration.
	Config ChunkConfig `json:"config,omitempty,omitzero"`

	// Text Text to chunk
	Text string `json:"text"`
}

// ChunkResponse defines model for ChunkResponse.
type ChunkResponse struct {
	// CacheHit Whether result was served from cache
	CacheHit bool `json:"cache_hit"`

	// Chunks Array of text chunks
	Chunks []Chunk `json:"chunks"`

	// Model Chunking model actually used (may differ from requested if fallback occurred)
	Model string `json:"model"`
}

// Config defines model for Config.
type Config struct {
	// ApiUrl URL of the Termite embedding/chunking service
	ApiUrl          string                             `json:"api_url"`
	ContentSecurity externalRef3.ContentSecurityConfig `json:"content_security,omitempty,omitzero"`
	Gpu             GPUMode                            `json:"gpu,omitempty,omitzero"`

	// KeepAlive How long to keep models loaded in memory after last use (Ollama-compatible).
	// Models are automatically unloaded after this duration of inactivity.
	// Use Go duration format: "5m" (5 minutes), "1h" (1 hour), "0" (never unload, eager loading).
	// When set to "0" or omitted, models are loaded eagerly at startup and never unloaded (legacy behavior).
	KeepAlive string `json:"keep_alive,omitempty,omitzero"`

	// Log Logging configuration for Termite services
	Log externalRef1.Config `json:"log,omitempty,omitzero"`

	// MaxConcurrentRequests Maximum number of concurrent inference requests allowed.
	// Additional requests will be queued up to max_queue_size.
	// Set to 0 for unlimited (default).
	MaxConcurrentRequests int `json:"max_concurrent_requests,omitempty,omitzero"`

	// MaxLoadedModels Maximum number of models to keep loaded in memory simultaneously.
	// When this limit is reached, the least recently used model is unloaded (LRU eviction).
	// Set to 0 for unlimited (default). Only effective when keep_alive is non-zero.
	MaxLoadedModels int `json:"max_loaded_models,omitempty,omitzero"`

	// MaxMemoryMb Maximum memory (in MB) to use for loaded models.
	// When this limit is approached, least recently used models are unloaded.
	// Set to 0 for unlimited (default). This is an advisory limit - actual memory
	// usage depends on model sizes and may temporarily exceed this value.
	// Works alongside max_loaded_models for fine-grained control.
	MaxMemoryMb int `json:"max_memory_mb,omitempty,omitzero"`

	// MaxQueueSize Maximum number of requests to queue when max_concurrent_requests is reached.
	// When the queue is full, new requests receive 503 Service Unavailable with Retry-After header.
	// Set to 0 for unlimited queue (default). Only effective when max_concurrent_requests > 0.
	MaxQueueSize int `json:"max_queue_size,omitempty,omitzero"`

	// ModelStrategies Per-model loading strategy overrides. Maps model names to their loading strategy.
	// Models not in this map use the default strategy based on keep_alive:
	// - If keep_alive="0" (default): eager loading (load at startup, never unload)
	// - If keep_alive>0: lazy loading (load on demand, unload after idle)
	//
	// When a model has strategy "eager" in this map:
	// - It is loaded at startup (as part of preload)
	// - It is never unloaded, even when keep_alive>0 (pinned in memory)
	//
	// This allows mixing eager and lazy models in the same pool.
	ModelStrategies map[string]ConfigModelStrategies `json:"model_strategies,omitempty,omitzero"`

	// ModelsDir Base directory containing model subdirectories. Termite auto-discovers models from:
	// - `{models_dir}/embedders/` - Embedding models (ONNX)
	// - `{models_dir}/chunkers/` - Chunking models (ONNX)
	// - `{models_dir}/rerankers/` - Reranking models (ONNX)
	//
	// Defaults to ~/.termite/models (set via viper). If not set, only built-in fixed chunking is available.
	ModelsDir string `json:"models_dir,omitempty,omitzero"`

	// Preload List of model names to preload at startup (Ollama-compatible).
	// These models are loaded immediately when Termite starts, avoiding first-request latency.
	// Model names should match those in models_dir/embedders/ (e.g., "bge-small-en-v1.5").
	// Only effective when keep_alive is non-zero (lazy loading mode).
	Preload []string `json:"preload,omitempty,omitzero"`

	// RequestTimeout Maximum time to wait for a request to complete, including queue wait time.
	// Use Go duration format: "30s", "1m", "0" (no timeout, default).
	// Requests exceeding this timeout receive 504 Gateway Timeout.
	RequestTimeout string                   `json:"request_timeout,omitempty,omitzero"`
	S3Credentials  externalRef2.Credentials `json:"s3_credentials,omitempty,omitzero"`
}

// ConfigModelStrategies defines model for Config.ModelStrategies.
type ConfigModelStrategies string

// ContentPart A content part for multimodal embedding (text or image)
type ContentPart struct {
	union json.RawMessage
}

// EmbedRequest defines model for EmbedRequest.
type EmbedRequest struct {
	// Input Input content to embed. Supports three formats:
	// - Single text string: `"hello world"`
	// - Array of text strings: `["hello", "world"]`
	// - Array of content parts (multimodal): `[{"type": "text", "text": "hello"}, {"type": "image_url", "image_url": {"url": "data:image/png;base64,..."}}]`
	Input EmbedRequest_Input `json:"input"`

	// Model Name of the embedder model from models_dir/embedders/
	Model string `json:"model"`

	// Truncate Truncate input to fit model context length
	Truncate bool `json:"truncate,omitempty,omitzero"`
}

// EmbedRequestInput0 Single text string (backward compatible)
type EmbedRequestInput0 = string

// EmbedRequestInput1 Array of text strings (backward compatible)
type EmbedRequestInput1 = []string

// EmbedRequestInput2 Array of multimodal content parts (text or images)
type EmbedRequestInput2 = []ContentPart

// EmbedRequest_Input Input content to embed. Supports three formats:
// - Single text string: `"hello world"`
// - Array of text strings: `["hello", "world"]`
// - Array of content parts (multimodal): `[{"type": "text", "text": "hello"}, {"type": "image_url", "image_url": {"url": "data:image/png;base64,..."}}]`
type EmbedRequest_Input struct {
	union json.RawMessage
}

// EmbedResponse defines model for EmbedResponse.
type EmbedResponse struct {
	// Embeddings Array of embedding vectors (one per input string)
	Embeddings [][]float32 `json:"embeddings"`

	// Model Model used for embedding
	Model string `json:"model"`
}

// Error defines model for Error.
type Error struct {
	// Error Error message
	Error string `json:"error"`
}

// GPUMode GPU/accelerator mode. Configurable via TERMITE_GPU env var (viper auto-binding).
// - "auto": Auto-detect (default). TPU > CUDA/CoreML > CPU based on availability.
// - "tpu": Force TPU. Fails if TPU not available.
// - "cuda": Force CUDA. Fails if CUDA not available.
// - "coreml": Force CoreML (macOS only).
// - "off": CPU only, disable all GPU acceleration.
type GPUMode string

// ImageURL Image URL or data URI
type ImageURL struct {
	// Url URL or data URI (data:image/png;base64,...)
	Url string `json:"url"`
}

// ImageURLContentPart Image content for embedding (OpenAI-compatible format)
type ImageURLContentPart struct {
	// ImageUrl Image URL or data URI
	ImageUrl ImageURL                `json:"image_url"`
	Type     ImageURLContentPartType `json:"type"`
}

// ImageURLContentPartType defines model for ImageURLContentPart.Type.
type ImageURLContentPartType string

// ModelsResponse defines model for ModelsResponse.
type ModelsResponse struct {
	// Chunkers Available chunking models (always includes "fixed")
	Chunkers []string `json:"chunkers"`

	// Embedders Available embedding models from models_dir/embedders/
	Embedders []string `json:"embedders"`

	// Rerankers Available reranking models
	Rerankers []string `json:"rerankers"`
}

// RerankRequest defines model for RerankRequest.
type RerankRequest struct {
	// Model Name of reranking model from models_dir/rerankers/
	Model string `json:"model"`

	// Prompts Pre-rendered document texts to rerank. The client is responsible for extracting
	// and rendering document fields/templates before calling this endpoint.
	Prompts []string `json:"prompts"`

	// Query Search query for relevance scoring
	Query string `json:"query"`
}

// RerankResponse defines model for RerankResponse.
type RerankResponse struct {
	// Model Name of model used for reranking
	Model string `json:"model"`

	// Scores Relevance scores (one per prompt, same order as input)
	Scores []float32 `json:"scores"`
}

// TextContentPart Text content for embedding
type TextContentPart struct {
	// Text Text content to embed
	Text string              `json:"text"`
	Type TextContentPartType `json:"type"`
}

// TextContentPartType defines model for TextContentPart.Type.
type TextContentPartType string

// VersionResponse defines model for VersionResponse.
type VersionResponse struct {
	// BuildTime Build timestamp
	BuildTime string `json:"build_time"`

	// GitCommit Git commit hash
	GitCommit string `json:"git_commit"`

	// GoVersion Go runtime version
	GoVersion string `json:"go_version"`

	// Version Termite version
	Version string `json:"version"`
}

// ChunkTextJSONRequestBody defines body for ChunkText for application/json ContentType.
type ChunkTextJSONRequestBody = ChunkRequest

// GenerateEmbeddingsJSONRequestBody defines body for GenerateEmbeddings for application/json ContentType.
type GenerateEmbeddingsJSONRequestBody = EmbedRequest

// RerankPromptsJSONRequestBody defines body for RerankPrompts for application/json ContentType.
type RerankPromptsJSONRequestBody = RerankRequest

// AsTextContentPart returns the union data inside the ContentPart as a TextContentPart
func (t ContentPart) AsTextContentPart() (TextContentPart, error) {
	var body TextContentPart
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromTextContentPart overwrites any union data inside the ContentPart as the provided TextContentPart
func (t *ContentPart) FromTextContentPart(v TextContentPart) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeTextContentPart performs a merge with any union data inside the ContentPart, using the provided TextContentPart
func (t *ContentPart) MergeTextContentPart(v TextContentPart) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsImageURLContentPart returns the union data inside the ContentPart as a ImageURLContentPart
func (t ContentPart) AsImageURLContentPart() (ImageURLContentPart, error) {
	var body ImageURLContentPart
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromImageURLContentPart overwrites any union data inside the ContentPart as the provided ImageURLContentPart
func (t *ContentPart) FromImageURLContentPart(v ImageURLContentPart) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeImageURLContentPart performs a merge with any union data inside the ContentPart, using the provided ImageURLContentPart
func (t *ContentPart) MergeImageURLContentPart(v ImageURLContentPart) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t ContentPart) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *ContentPart) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}

// AsEmbedRequestInput0 returns the union data inside the EmbedRequest_Input as a EmbedRequestInput0
func (t EmbedRequest_Input) AsEmbedRequestInput0() (EmbedRequestInput0, error) {
	var body EmbedRequestInput0
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromEmbedRequestInput0 overwrites any union data inside the EmbedRequest_Input as the provided EmbedRequestInput0
func (t *EmbedRequest_Input) FromEmbedRequestInput0(v EmbedRequestInput0) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeEmbedRequestInput0 performs a merge with any union data inside the EmbedRequest_Input, using the provided EmbedRequestInput0
func (t *EmbedRequest_Input) MergeEmbedRequestInput0(v EmbedRequestInput0) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsEmbedRequestInput1 returns the union data inside the EmbedRequest_Input as a EmbedRequestInput1
func (t EmbedRequest_Input) AsEmbedRequestInput1() (EmbedRequestInput1, error) {
	var body EmbedRequestInput1
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromEmbedRequestInput1 overwrites any union data inside the EmbedRequest_Input as the provided EmbedRequestInput1
func (t *EmbedRequest_Input) FromEmbedRequestInput1(v EmbedRequestInput1) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeEmbedRequestInput1 performs a merge with any union data inside the EmbedRequest_Input, using the provided EmbedRequestInput1
func (t *EmbedRequest_Input) MergeEmbedRequestInput1(v EmbedRequestInput1) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsEmbedRequestInput2 returns the union data inside the EmbedRequest_Input as a EmbedRequestInput2
func (t EmbedRequest_Input) AsEmbedRequestInput2() (EmbedRequestInput2, error) {
	var body EmbedRequestInput2
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromEmbedRequestInput2 overwrites any union data inside the EmbedRequest_Input as the provided EmbedRequestInput2
func (t *EmbedRequest_Input) FromEmbedRequestInput2(v EmbedRequestInput2) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeEmbedRequestInput2 performs a merge with any union data inside the EmbedRequest_Input, using the provided EmbedRequestInput2
func (t *EmbedRequest_Input) MergeEmbedRequestInput2(v EmbedRequestInput2) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t EmbedRequest_Input) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *EmbedRequest_Input) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}

// RequestEditorFn  is the function signature for the RequestEditor callback function
type RequestEditorFn func(ctx context.Context, req *http.Request) error

// Doer performs HTTP requests.
//
// The standard http.Client implements this interface.
type HttpRequestDoer interface {
	Do(req *http.Request) (*http.Response, error)
}

// Client which conforms to the OpenAPI3 specification for this service.
type Client struct {
	// The endpoint of the server conforming to this interface, with scheme,
	// https://api.deepmap.com for example. This can contain a path relative
	// to the server, such as https://api.deepmap.com/dev-test, and all the
	// paths in the swagger spec will be appended to the server.
	Server string

	// Doer for performing requests, typically a *http.Client with any
	// customized settings, such as certificate chains.
	Client HttpRequestDoer

	// A list of callbacks for modifying requests which are generated before sending over
	// the network.
	RequestEditors []RequestEditorFn
}

// ClientOption allows setting custom parameters during construction
type ClientOption func(*Client) error

// Creates a new Client, with reasonable defaults
func NewClient(server string, opts ...ClientOption) (*Client, error) {
	// create a client with sane default values
	client := Client{
		Server: server,
	}
	// mutate client and add all optional params
	for _, o := range opts {
		if err := o(&client); err != nil {
			return nil, err
		}
	}
	// ensure the server URL always has a trailing slash
	if !strings.HasSuffix(client.Server, "/") {
		client.Server += "/"
	}
	// create httpClient, if not already present
	if client.Client == nil {
		client.Client = &http.Client{}
	}
	return &client, nil
}

// WithHTTPClient allows overriding the default Doer, which is
// automatically created using http.Client. This is useful for tests.
func WithHTTPClient(doer HttpRequestDoer) ClientOption {
	return func(c *Client) error {
		c.Client = doer
		return nil
	}
}

// WithRequestEditorFn allows setting up a callback function, which will be
// called right before sending the request. This can be used to mutate the request.
func WithRequestEditorFn(fn RequestEditorFn) ClientOption {
	return func(c *Client) error {
		c.RequestEditors = append(c.RequestEditors, fn)
		return nil
	}
}

// The interface specification for the client above.
type ClientInterface interface {
	// ChunkTextWithBody request with any body
	ChunkTextWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	ChunkText(ctx context.Context, body ChunkTextJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GenerateEmbeddingsWithBody request with any body
	GenerateEmbeddingsWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	GenerateEmbeddings(ctx context.Context, body GenerateEmbeddingsJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// ListModels request
	ListModels(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error)

	// RerankPromptsWithBody request with any body
	RerankPromptsWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	RerankPrompts(ctx context.Context, body RerankPromptsJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetVersion request
	GetVersion(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error)
}

func (c *Client) ChunkTextWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewChunkTextRequestWithBody(c.Server, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) ChunkText(ctx context.Context, body ChunkTextJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewChunkTextRequest(c.Server, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GenerateEmbeddingsWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGenerateEmbeddingsRequestWithBody(c.Server, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GenerateEmbeddings(ctx context.Context, body GenerateEmbeddingsJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGenerateEmbeddingsRequest(c.Server, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) ListModels(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewListModelsRequest(c.Server)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) RerankPromptsWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewRerankPromptsRequestWithBody(c.Server, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) RerankPrompts(ctx context.Context, body RerankPromptsJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewRerankPromptsRequest(c.Server, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetVersion(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetVersionRequest(c.Server)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// NewChunkTextRequest calls the generic ChunkText builder with application/json body
func NewChunkTextRequest(server string, body ChunkTextJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewChunkTextRequestWithBody(server, "application/json", bodyReader)
}

// NewChunkTextRequestWithBody generates requests for ChunkText with any type of body
func NewChunkTextRequestWithBody(server string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/chunk")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewGenerateEmbeddingsRequest calls the generic GenerateEmbeddings builder with application/json body
func NewGenerateEmbeddingsRequest(server string, body GenerateEmbeddingsJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewGenerateEmbeddingsRequestWithBody(server, "application/json", bodyReader)
}

// NewGenerateEmbeddingsRequestWithBody generates requests for GenerateEmbeddings with any type of body
func NewGenerateEmbeddingsRequestWithBody(server string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/embed")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewListModelsRequest generates requests for ListModels
func NewListModelsRequest(server string) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/models")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewRerankPromptsRequest calls the generic RerankPrompts builder with application/json body
func NewRerankPromptsRequest(server string, body RerankPromptsJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewRerankPromptsRequestWithBody(server, "application/json", bodyReader)
}

// NewRerankPromptsRequestWithBody generates requests for RerankPrompts with any type of body
func NewRerankPromptsRequestWithBody(server string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/rerank")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewGetVersionRequest generates requests for GetVersion
func NewGetVersionRequest(server string) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/version")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

func (c *Client) applyEditors(ctx context.Context, req *http.Request, additionalEditors []RequestEditorFn) error {
	for _, r := range c.RequestEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	for _, r := range additionalEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	return nil
}

// ClientWithResponses builds on ClientInterface to offer response payloads
type ClientWithResponses struct {
	ClientInterface
}

// NewClientWithResponses creates a new ClientWithResponses, which wraps
// Client with return type handling
func NewClientWithResponses(server string, opts ...ClientOption) (*ClientWithResponses, error) {
	client, err := NewClient(server, opts...)
	if err != nil {
		return nil, err
	}
	return &ClientWithResponses{client}, nil
}

// WithBaseURL overrides the baseURL.
func WithBaseURL(baseURL string) ClientOption {
	return func(c *Client) error {
		newBaseURL, err := url.Parse(baseURL)
		if err != nil {
			return err
		}
		c.Server = newBaseURL.String()
		return nil
	}
}

// ClientWithResponsesInterface is the interface specification for the client with responses above.
type ClientWithResponsesInterface interface {
	// ChunkTextWithBodyWithResponse request with any body
	ChunkTextWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*ChunkTextResponse, error)

	ChunkTextWithResponse(ctx context.Context, body ChunkTextJSONRequestBody, reqEditors ...RequestEditorFn) (*ChunkTextResponse, error)

	// GenerateEmbeddingsWithBodyWithResponse request with any body
	GenerateEmbeddingsWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*GenerateEmbeddingsResponse, error)

	GenerateEmbeddingsWithResponse(ctx context.Context, body GenerateEmbeddingsJSONRequestBody, reqEditors ...RequestEditorFn) (*GenerateEmbeddingsResponse, error)

	// ListModelsWithResponse request
	ListModelsWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*ListModelsResponse, error)

	// RerankPromptsWithBodyWithResponse request with any body
	RerankPromptsWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*RerankPromptsResponse, error)

	RerankPromptsWithResponse(ctx context.Context, body RerankPromptsJSONRequestBody, reqEditors ...RequestEditorFn) (*RerankPromptsResponse, error)

	// GetVersionWithResponse request
	GetVersionWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*GetVersionResponse, error)
}

type ChunkTextResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *ChunkResponse
	JSON400      *Error
	JSON500      *Error
}

// Status returns HTTPResponse.Status
func (r ChunkTextResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r ChunkTextResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type GenerateEmbeddingsResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *EmbedResponse
	JSON400      *Error
	JSON404      *Error
	JSON500      *Error
}

// Status returns HTTPResponse.Status
func (r GenerateEmbeddingsResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GenerateEmbeddingsResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type ListModelsResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *ModelsResponse
	JSON500      *Error
}

// Status returns HTTPResponse.Status
func (r ListModelsResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r ListModelsResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type RerankPromptsResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *RerankResponse
	JSON400      *Error
	JSON404      *Error
	JSON500      *Error
	JSON503      *Error
}

// Status returns HTTPResponse.Status
func (r RerankPromptsResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r RerankPromptsResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type GetVersionResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *VersionResponse
}

// Status returns HTTPResponse.Status
func (r GetVersionResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetVersionResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ChunkTextWithBodyWithResponse request with arbitrary body returning *ChunkTextResponse
func (c *ClientWithResponses) ChunkTextWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*ChunkTextResponse, error) {
	rsp, err := c.ChunkTextWithBody(ctx, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseChunkTextResponse(rsp)
}

func (c *ClientWithResponses) ChunkTextWithResponse(ctx context.Context, body ChunkTextJSONRequestBody, reqEditors ...RequestEditorFn) (*ChunkTextResponse, error) {
	rsp, err := c.ChunkText(ctx, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseChunkTextResponse(rsp)
}

// GenerateEmbeddingsWithBodyWithResponse request with arbitrary body returning *GenerateEmbeddingsResponse
func (c *ClientWithResponses) GenerateEmbeddingsWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*GenerateEmbeddingsResponse, error) {
	rsp, err := c.GenerateEmbeddingsWithBody(ctx, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGenerateEmbeddingsResponse(rsp)
}

func (c *ClientWithResponses) GenerateEmbeddingsWithResponse(ctx context.Context, body GenerateEmbeddingsJSONRequestBody, reqEditors ...RequestEditorFn) (*GenerateEmbeddingsResponse, error) {
	rsp, err := c.GenerateEmbeddings(ctx, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGenerateEmbeddingsResponse(rsp)
}

// ListModelsWithResponse request returning *ListModelsResponse
func (c *ClientWithResponses) ListModelsWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*ListModelsResponse, error) {
	rsp, err := c.ListModels(ctx, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseListModelsResponse(rsp)
}

// RerankPromptsWithBodyWithResponse request with arbitrary body returning *RerankPromptsResponse
func (c *ClientWithResponses) RerankPromptsWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*RerankPromptsResponse, error) {
	rsp, err := c.RerankPromptsWithBody(ctx, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseRerankPromptsResponse(rsp)
}

func (c *ClientWithResponses) RerankPromptsWithResponse(ctx context.Context, body RerankPromptsJSONRequestBody, reqEditors ...RequestEditorFn) (*RerankPromptsResponse, error) {
	rsp, err := c.RerankPrompts(ctx, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseRerankPromptsResponse(rsp)
}

// GetVersionWithResponse request returning *GetVersionResponse
func (c *ClientWithResponses) GetVersionWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*GetVersionResponse, error) {
	rsp, err := c.GetVersion(ctx, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetVersionResponse(rsp)
}

// ParseChunkTextResponse parses an HTTP response from a ChunkTextWithResponse call
func ParseChunkTextResponse(rsp *http.Response) (*ChunkTextResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &ChunkTextResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest ChunkResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	}

	return response, nil
}

// ParseGenerateEmbeddingsResponse parses an HTTP response from a GenerateEmbeddingsWithResponse call
func ParseGenerateEmbeddingsResponse(rsp *http.Response) (*GenerateEmbeddingsResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GenerateEmbeddingsResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest EmbedResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	case rsp.StatusCode == 200:
		// Content-type (application/octet-stream) unsupported

	}

	return response, nil
}

// ParseListModelsResponse parses an HTTP response from a ListModelsWithResponse call
func ParseListModelsResponse(rsp *http.Response) (*ListModelsResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &ListModelsResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest ModelsResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	}

	return response, nil
}

// ParseRerankPromptsResponse parses an HTTP response from a RerankPromptsWithResponse call
func ParseRerankPromptsResponse(rsp *http.Response) (*RerankPromptsResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &RerankPromptsResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest RerankResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 503:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON503 = &dest

	}

	return response, nil
}

// ParseGetVersionResponse parses an HTTP response from a GetVersionWithResponse call
func ParseGetVersionResponse(rsp *http.Response) (*GetVersionResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetVersionResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest VersionResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+x8bXPbONLgX0Fxryr2HvViO8lkdLUfPJkkj+9xJn7seOfuRikZIlsS1iDAAUDZmpTv",
	"t191A3ynbGdnZ28/bFWqYpFAo9Hv3Wjwa5ToLNcKlLPR7Gtkkw1knP58uynULf6Rgk2MyJ3QKppFpyzB",
	"F0yvmIN7x+6E27BcW4HvmVArbTKOf4+jOMqNzsE4AQQRVLpINtz0gb7dcMMTB6YJiWkj1kJxGRbagIGw",
	"OKjUsgO4T2RhxRYOozhyuxyiWSSUgzWY6CGORNpf6Ap+LUAlwFSRLcHQLjYl1INpzI5idhyz8Xg8ADOO",
	"7kdrPQpPC6HcyTEuZB037h+0M4JlB/eDY/sLfK7QT7RyoFw91zoj1Dp6eIgjA78WwkAazX5BugRgLdTj",
	"mj9fKhB6+TdIHK5O4vBWq5VYD+ySnheGGM9W2niUhFozXBmss8xp9hlMJhyw04uz8Vx93gjLhGWcWZHl",
	"UqwEpLiJlVgTCGTMf3z+fIHD2YilYrUCY9nK6IzerQopGaEFxiMwV3cbkWyYUIksUrAsN3orUjDMgoSE",
	"kOMqZQlPNohb0kR7PFc9ic34/YJ2Yv2eV7yQLpq9msYdAnzk9yIrsoZY+Wm4awOuMAgb7nmWS/Dz+/zN",
	"dAqytU60EveA3NrDctwDzcJlCgtj9k64DRj2gia+IDIScYE5fQtqtOQWiRwmx0wbxgMIxTPwxKXfdpJ4",
	"0trJV3z1MBk3t1Ch1pG1ONJbMJLnC1rwKbr9VNErTMtxT34qW4K7A1CBlE8T0ELODXfatIk4V8TZDg1R",
	"8aoJRCjaUUWb1mYDiN5eHTdrcMNb7e31Mw1uWh6/zRyCurR3OLhFtzFgN1qmrcWm41fxkEamZOqqObTL",
	"Tz/99L8Ch9nBdDwdHY2nh82VCZi34shmqXnDpHjkyaQMW4hLr+6IXluVksp0/DcDq2gW/WlSu55J8DuT",
	"ppXZb/KQd073iRbVJkVqtWapTooMlGNuwx1TACkp5BKYzaVwTCinmc24lCUL7Hg8ftKAElZf9lPA5lpZ",
	"II9XYvY1QpsDi41w0WzFpYU4Kg3LL94z6tXKgotmR8j5DBxPuePR7GvlYMoB05Iu1XbJGgpjnd8E7uEh",
	"7kD9/gmo3w+DtZBolTbgfqkMVTABD12j2dhpl3M/b4DskwFbSMfuuGUWzBZSb3hoZk3+pdYSuMIVmka4",
	"FY0Yw3dVLFIZCuEgs8+StaiWZI6wOoa47cpbJpcnruBS7tDwpuwg47vgovxegt+DlIkVW3Eplzy5ZTpJ",
	"CmMgPXyOLe2IXbU7j1/cIPSgMFYK12YPz8WiMAP7u748L+Oh0lFDtoQ0FWo9qfwN8ksk0MJ/41w+m0yk",
	"TrjcaOtmb6ZvplHDihRGDJnPELEsLCSFEW73FMe4ciu5G631QoolXy1sYjg6jIXOQeG+3nqAVwFebUjW",
	"eUF7l/LTijTusWU+XFx/1CmQrNduhBdOI6hbgHzBpdhC281Mez7mP/Sdt0NOM5xVml2peYpyoVgGmTY7",
	"xlcYIEpuHQoTO/gkJc/4CFHjTiwlHI7n6qOfzA0wRAWD7MTLnwoAPRiH2puWsZheMaF44sRWuN14rq4t",
	"sA+6fu9ZNGPz6FU2j9jBK5YJVTiwhzGbR0cbfHbENrow9GCKvxVswYRlYwZ8jchrjnKCiP68AcUskIn2",
	"M7RhOhPOQRqXNMBtBLQJgNwx7nz0W+QUpDVXQQWTsObJji1hw7dCm0Mfr9VC+CobEjGp198qVVKv1x2h",
	"ClJE4aBWpMLKLcrQtu2LnxEaViAwXwJDXrqKk7mU+g7S8VydpillDFzWb++ElOjAfi2ggJQVOVIZ8aIH",
	"Cyt+g/FcXXnqT8njF0oK1OaUHQQsu7R7ORiO8vuFp/3C8+xbtxk4XQp/T+qtyArpuAJdWLkrBYfElxBG",
	"F2QAbVwak1WSgBpiIAHlSrvrbbGwDUE5v7xmsBUU7h8+hxjsk5I7BqsVpghbwHxMsVrNEbrSavQbGN0h",
	"3Mk+wvktLrLl84gWKHIgFPv4w2GI5gnfsClPy2Ea8Tw3OpBpL4m8xpVEehZVqmBKMZ5uhUUM/aKj4PwC",
	"3nNVWL4GlkJOiblWgS0ojZaUGb2jgyzXhhuBxL5PAFK/kS2XBQrtz9rcovhrtbYiBdYTwBClKxitDRfK",
	"Z4vOaNkV5+n3r/cxplaTbxXnZiJLULyc7LEJDeGtuRbUFt9h8hozBXc1XOQaitur6Qm78l6WXSu+5ULy",
	"pQRfabkEZ3ajU7L0G+ApmP289Is9Ief78J8X0+kJsGmHtkfT/bnrwjrDHazLQKMyXxedMlCRYTxDdj+K",
	"I8l/20VxtNSFSiFtxDK1FW/z5gLMyAtY8DosLLyjLNKIFOyYfeS5baS2xDe3AWF6s2rnqjSaZC+WGc9J",
	"C5FtgYT1Oj6P1k0zMZurETtbNZ78JfjLkgGztq9kB/hHw+3FLZ932IPnWTKdMaRYB4pWLIWMqzQO00M0",
	"IFIJh5i+kgiWuf4GA+9yL3PPiXnU3LrfDdmXMrqo3fMBtyznxqFa5AZqbGl823HHDLagujY1bIUd5EKp",
	"plcgXMnykB+0LBP3uEtPOTQltPlgEITXKsszYLnuGYKv0XINI0rwRqBG26Pxq2hWyV2y0ep2F828AA5l",
	"tH6VRSoGCns/cAssFQYSh4YRLREXqk4PbLEs3woUxzKkxthtlAqboKjaciOYMhDJb77Wiz5MfPwNxk5u",
	"2Ii9K6PxKn/HZP6wP62q3OCsdtqyf5IBw+tZl/RrYNpc/ejFmRTq/07Gzm9sUo7DyG8rONuKHMzhGEUY",
	"1cqCi5lGA7QshHQjoToFF3I1pbHrBne9dYZivSCKfV6dC+uqiKS2BmF8S7IHQ+/PG7AwELmKLINUcAdy",
	"5wW8ZLKv4saMb7UghlF2PgrGlUnuQCWV3QkY2Y0uJLpKl2yY22gLpBYVixrSwA5gvB5jQN4T8HmEGD8/",
	"omEHLWuCy3XDw18G1CiOEiny0VY4qimOcsT65Bitd5V898tlnUQ70GPhRAa6cE/lU6VPxuHIvzsuHLk8",
	"XjpRqgppxNpBHMrAuKvgr3E8Tn40DzqZ2nlEyU/m//c5j2YBy5g1oujL0l36gIaKl2i8wtiGT3/JPnAH",
	"d3zHPvt3XRE/mQ4KtT1ZJAZSUE5wab85Qz6p05gGlG5poawJ7KkjYE59wY0bPA3yr70/QGZgUC8ynXJZ",
	"lw/YAdVntGEi42s6r9EKnpGKf4Z710TgIX58/BmCv748b8358hBHZDv3FieFyouB3Z3h42qHTvsNjdlV",
	"kefaoAXcGIAgO5bs95VQawm+HOWZOGM382gDUmp2p41M59ENDmxXrvxQO2M3v4TBXvbCjC/tKU2aW3ZQ",
	"U/wQAXydExPnEUozQveg/F/4LMB/iFlrKLEGxcCPb/yc4cDw1zxKueMzejvJ1fp/oPq/fhmPx+N59PCA",
	"mLZtR2PrEcbgyUYoyuUMeksUuVoUOod1PVqygyVPbu+4SVnDQg+ozeN1wkDtvdCebcH2LtNQgg6zWopg",
	"D59drGwpQQePL/uLlj9haBSqeqX/CH6wcdbTcS8tuzRk+/t0MYVKuGsnVc4U0DsECQMZqRzq1Eq4gBBR",
	"6t4xCWrtNgN14I7VKuugXnuHbFfQ+sGCfGWcbDT75ZfpeHp0fBKPpuPpy1ev4+l4+t2b77/E+Pz45CU9",
	"f/X6O3z+5vsvjRp4nzq9enhzob0CU5vKLcWMlh1oBXQ25Cnlad2Sl+qPp05r+p73mSVvH55QFQFNe4Xk",
	"twrIHsY1KDPIPWP8WV6HnuXjNq40mmVgLV/Dkyh4IEOrltXf3gIfLq4nPElAgj8zxF2MWXX0jSk6xr2f",
	"311+PPv8bvHh4pqB2rItN+yAgmEf+y+FKiulIzansjLa1VPKC8BB4lpFmIvrMhV/e/3j6eStNvDxvHp0",
	"cV2noiF4FtJXehG4ywuE/V6bBBDUmL3nAvOmFQHGuLwZcuOUpEh5PQfXbEzCn8OztIFMNuZ5NA8ynny6",
	"orC/3K9erXAYYo6PY5YKS7TjUjKkWUXi6ky+LBhQBT7GTWH4WaQc/6OFMZ5YrQZLB2VEMODd8Q2jUw/D",
	"0Kmx68uzXgvA/qOSehI72OsT2wc9w8PEX3/4dHk3/c8Pa/2c48d9gdpQ7LNn06VPaik1O/iUgzo9ayQ/",
	"IbQ57FGlCg6e8lsV+SujUxeAaiBfnjxyxbfx4IyaAL6I0zT3nYPJkBYPmOGqyJZ0s2Uu7/jO1i0lc39a",
	"N48O22FOeYbnqwqjDC2vC3aRogEp1LrgcnT0bTlS5ZUfwxq6lYHn+fbhxK73bCTejH5135rahWrCY2ib",
	"TpGhj1sJZrQ9HmUn34LC0OEpotNErUndIYHyRZC9WcMTIVdndz2e1AWXnjvtbHuw1qGz3A1Q98LgdJWC",
	"gbTRAAH3LjQjIeQxox4iKegMyjLjdaZUeQb3zvDECbWeK65S5gGKZkvFSoBM7cRBlkvuwLIlrLQBlnAp",
	"qzQYVJproVyvoHCmnNFp4Vuy6ASrnRZ4O/gjnRuFR2xVqJTj2lxSm8Y3yeOvBZjdUD8gN8mG0VvauQEJ",
	"W64SYDbRphvqdNFkPM+lSMhX2WeHPR6XmoePid4+W/aE7GXtwK0SxcEKA/rQAUm6bJECGhGpRzz2dVdt",
	"MKXg1seprQD1W+PSPfQKCA6RqVsfGO4VGnR3PZ/2SLNRtwQwmAJ1vFunS+hxx7a3peivYKzQar8gLAsh",
	"U6qgDdSo8R3VoqzjWd4S5ePp8cvR9Gh09Orz0XR2Mp1Np/9naFtr4RaJzrKhdp4PAkmD79iG200LPl8m",
	"R8cnLwdB6sXWb2sApGamUFThK8c0oa710fj41Xg6BHYvzLIqOwRwezSeDoHrsKme2qBH3CR+a1tDnOyW",
	"5spIoy7Q/bvh+t8N1/vlZU9bSv+ww49rNzeT6atOJ/zhsu3Ji4QtyN/bLnNOQIhLO19p+T3QrgjIYL/p",
	"8xBpnSmgtvSOFUqCbcEsUWR2zNOhTjxTWBZrKjTR9Dvu27nLEkJtTcKAnml63i5bqNJxl+JyL7q6cHnh",
	"QobGiNhj9qKc5nu/Ey21Eb/5TgmrJcTsxd+sVqEz3JkicQUGiv/z6tNPMXsh9XqVOf/WN4zDaiUSChNv",
	"YfcXatVgORfGxuyF0jove8wlKDdukKyBPi4YUSfWKkMVwGltsjUGP0m6PSca/TbHJAFrF7ewWwzZpdOf",
	"r5gfghtjZz82qvq3sLMOY1m7U47f+x1CYsAxqfVtkY/Zey6lZdTS6TQ7/flqcfr27burq8V/vvvfi7Mf",
	"GaitMFpRpLzlRlC6I6qT0HYr/U4XZuSRGd3CbiQG44sylh6wsSfNlL0cV54RvrAnY57x37Tid3ac6OwF",
	"0wZZXTZrfj+dTj0bPwp19qldsehOjuIoE+rcV2hnR0PhJFFqUdN/mPiBoDUPfi8Drt69vXz3ucGHv4MJ",
	"fpEGLwbjZbDo5H3Xf39zn/LQs+d3SWO9Mnm1Cl1QO9Y41vumvQ+hTauMPEYDKBcWFtbKJ6vz7xTR6Orq",
	"fPL5/IrWvjpB26H87RlblSZnDOfTiNOfr2JGPe2hYy3hshalgRr+k5b8mX29fZ33rZMLFGs71H0uHMjQ",
	"CxDGMhxL5++TswvfYSaFumWpvqMGFksNDJDlbhdTiZJg+y7cAAHDIsgdy43YcgcM4YgVW0qd3C7Cw4XI",
	"fUu9KeBw3M6Fw59Bu5JUjdtPjr4/Hk/Hx+NvLByVxMi52zyXGDiW5QZW4h7KdjsJs8mEOm/sCf51fXne",
	"Iwqt0STKmL1vTC4sML60WhYOwthgnCbXFoydpNzxyaGf5FfBKcsiuQU38fiUM7LdKDwvcmLQpEvPJkw0",
	"V70J30bHHh+f1KIfcEarX7AWDWa4WmMufXT8HWYe4+nkTcyOpo2/vzseH72mX0fHMUPuH71+43+/jtnR",
	"6+/Hx69eht+Hg7clSuEtGysW/hZHG/OT/gWl0LSAfBcqFVuRFlxWqsBQ1XypA0PqEmazHXZK3kFkGAMc",
	"7WvBrLCz4jdYLHcO2ogdTV++efXd6+nenkych1JbAgqNoL6fmnmArZbFCl6F3PSJXEMo9/plibCvOqci",
	"A1UnmAHZ4+nLN/vwpHnsTqRuM9mAWG8Iv1zcU2HZHwBXDd0GcFvtiyEe+GMU7VtTfERhqL9z5XhCEQOa",
	"OPS8ZGmj2B9r0MUNO5tM1sJtiiXamxCQp8tJ6Lfqt1+WaYRvDQ4NU1LcQjD9dU873e0x1bWzcPvw43nd",
	"zjxXf/oT+3nDqQoZAFMHYFgjXOC0pVc5b0CnRLjGoBECnV6cUTPGn/9ct8x9ABWk989/njGq6lBjcn1Q",
	"f/D2/OzisFdL94BoQtlKhxCuIOPKiaQ+MSB8mtfryjuFIxLY8g6Qh1f11yGsutJmYBTqjsHxU3nSX5cK",
	"mLwvMGTHaT+9u4xZIrm1YhWKkDFtah32uoWqGZGiC5ZLrhSk1MVXajV11nMH1DcugaOtdqyUDC8OY6En",
	"qU7spHKLFeuA6rfXFobYl3DFTKEwyVYpl1oB3Titu0e5Yl4kWSIL68AQ386J2TUpO0xHGwX3DgxFWRdn",
	"ofEcVCKAiNSXiJsJz4U/BbmpI+RWPZBmVlyt75OVvLg8/cBykYMUyq/S5FpZ6SfTmaHUQlpy79eCS+F2",
	"OOUtKGe4pIwscAZzcbVmPDHaWpYKdETLwkHKlE79QhfoPZLdKDdQDm8pAp0+hrZbCXwLlmFYiCMMr5K8",
	"w8Cy98DxZ+Dgn9iQinhJ8+dpKGlNqW41sJY39/a2rXpIpxdnBOZ5fCk1xJc8MSjIuCM8fhAKI+fqfDym",
	"xLXcycdal0M4HXTaA/RHn9V2CSC+Zo3bBX8juUDmj7z1rq2BzXkCARJ1ZDTxooPc6jzYsoObvSfCN4eo",
	"AxhFeWDh0PVtRRQEeG3BdjqHQqJ/cPN3NW2F9qybQAvU17fcAmHvCeOlNWYkiCNPRgPOCNhyGbOtsBgM",
	"WJEJyQ3Js6d6yzJ2Bed9bf8qZSqPVKsegkP235sS1oDBfgxytkNgp3tbp/f2P3tYb/19f4RxPPL329jn",
	"z+fltRu6RxmMazDShHsrxew2K5dnLCsuZKVLlVV/7h6aijWwkUZPtof4XwWap98qP3bavgmIUvOrH1Jf",
	"/BGrmtQN+cXprcNCMnnhTIodhMPBDVepxFxAgEyrc0GtDulET4oEwqlEGWBIyS4x1LHsEvzd3l60UfsU",
	"CWtOtUInnL/AXX8hImpU9KPtEZf5hh/RBwZ8UhjNopPxdHwSxVGV4njOU2Ko7VClJJcCI3Lc6cDlb1ZY",
	"f8U1OIG2A++0BpTRy8cgtF4CSODrnvu+rPsm0d4nGehCuqvCiPA1BBx8Xbae/6VqPcDH77n1EUwKvnwm",
	"rBNJiQbJ1cdKnfrBStU1VBqZpmKP2MfHbH3jDLutad+sMSxoJv669EEOZZGkkc27gmibj8urqWOaBlS4",
	"q/oyltptyq+HIFlc49yuZNU7H1jjr5ubm79ZdHRf54q1umP3fEOADGjsB/tlvIlVjOEj2poHEJgUl69a",
	"H4nAIa+m0+pl+2sZ/m31svo+hQc8nyv8F+Hrh7l6oF2QHlaZ2VlaXlT/7M8bQhb6g053ZUYAvobYOLqe",
	"UIm2+vzPsy7Ol10RD+3TDsyH6YF33qSVx9PpP3rtcBpKiw+d15JYpswWVMlbFVJSLv/yH4iJ704cwOBM",
	"bbkUaVkAwHVf/XPWDSFxSLsgDIwjW2QZN7tSNAbsn4V1Rt+AwuE+HttvRUOcCDb0qjZi6FA7aLbNe5sq",
	"OyG9LT8AVAXjwja6sEMyRfHiC9sOE0Mg5Iup9y72LSqYEKjUMhFOSPu9bI1Ur8yHEEYjBOyb9M6l+0dt",
	"YfOyVn2lKNw1wSzL78LPaGQhTjOqw9U3PRvYlLnniK5OZSGwKothvVatwxk7Taga2Wx0D9FIvf8uHIqS",
	"21ORpqFEsRW8Dm0DiVohsL+z17gKQQQLRIb0D70YMXRla/9liWfdj/Cx8h9zO2KgyfLwd/rCxtcE6Dwh",
	"aX4vACGkkBbe2mDqH2IcYsdKUlXK34XbIggDaaFSrhzy5LZUiG4uho+rEwvSK4xnqi6ZXR6kJgiUv6js",
	"7zc2DZ9OHLiRdQZ4dlNldxaMwBzZH1yXuV7MMm0dq84jD3vQ0IzezCgjLBvagh1pfOCKTEUj5W/GBV6O",
	"UeqaPbE96Zr1o4eG9x+4kBeiBjKLOOiXjtijPHU7y+bRl9rDz9XHwUtVfVF6HLfBK3tD+FH88aSecJZv",
	"tNNUx2EJd6g0A1N/n+aE5uigQAj+yyOhT+ma6iz/D4qBWvfJ/skxUPtWC669T6naMDunFKRto1LbIO3f",
	"QWl+wmdJwwd6XXpxSE37shD5LxSJvZy+/OPXDbd6NQYYhUr/pSLAUkMaVtAHffVHXtbghrpBXWGUpVDF",
	"ksr3u8/jxpcFfdtwu7+7ysPKSMlHOP0iyHBUhWP/q6pu0Im+cpZt+BbYzUi8uWG2WK3EfelPQ27qFznd",
	"18fPDsoL6eRSLmRhGVe7x7Fq5r3BQ4ZKzTO21KnqvMtyt/N9CeWUsnfLl+obQWgj/sQQM3wlpPnZpKT8",
	"5kjPNp4L6z6WffZ/mHHqXMLYpx22rC0O2IZ/GV05HwrLvbZ4Hu7PkS79QQ59g3Rfja2qwdRN504zHrrR",
	"fZxGgrRPj976Gt1l2b0vpHAihDF1f39WWDebq6Mxe+fLd+V6ZRO/l9Cy0GHn6njMLgljUoSqxX+uTsbs",
	"ClQ6sKfySi237Cbs76b6lEcKVqz9Bwhs8xsJDiRY/4Gg8LUPjzKdmSeFdToTv0Hj9oHUa5H0s7S6XvWc",
	"PK2jflUc2yucHvhZi+rFWCt170vo7cJrboC+Tftr3zq1q69PlaE6gWT7HkgVqZGA+FGP3kioJgSONIK7",
	"ee8KxscA6TxAmvkPQK0LkWJovwVj6xoYAqDbGeVo9r5xO2PGfoLCcMkUuDv/VScDNLkTv83Ve20qyQul",
	"0FraKXjvVp7j6qs8XlhGVqQwVzdSLCfV1BuW8+SWjt/pi8BlGbsWpaevq7StpzfwF+HKxh8TVLbvG/2T",
	"o8rOjZMBkxk2Hxj076Du/6ujwtVP/vjV6+8AlcFG0fgk2cFQyHLY8aIeRO31drW/8760cXHj0dCzc48j",
	"Zuvq/klMXxXyd1187Nm/SDIeyBbdX6uLHX+YYnWv8AxQOQxp3ubohe2u3EdnFHWkomTYgU9oNM7TgvxU",
	"p3ETnovo4cvD/wsAAP//eP4cAwNgAAA=",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	for rawPath, rawFunc := range externalRef0.PathToRawSpec(path.Join(path.Dir(pathToFile), "../../../antfly-go/libaf/chunking/openapi.yaml")) {
		if _, ok := res[rawPath]; ok {
			// it is not possible to compare functions in golang, so always overwrite the old value
		}
		res[rawPath] = rawFunc
	}
	for rawPath, rawFunc := range externalRef1.PathToRawSpec(path.Join(path.Dir(pathToFile), "../../../antfly-go/libaf/logging/openapi.yaml")) {
		if _, ok := res[rawPath]; ok {
			// it is not possible to compare functions in golang, so always overwrite the old value
		}
		res[rawPath] = rawFunc
	}
	for rawPath, rawFunc := range externalRef2.PathToRawSpec(path.Join(path.Dir(pathToFile), "../../../antfly-go/libaf/s3/openapi.yaml")) {
		if _, ok := res[rawPath]; ok {
			// it is not possible to compare functions in golang, so always overwrite the old value
		}
		res[rawPath] = rawFunc
	}
	for rawPath, rawFunc := range externalRef3.PathToRawSpec(path.Join(path.Dir(pathToFile), "../../../antfly-go/libaf/scraping/openapi.yaml")) {
		if _, ok := res[rawPath]; ok {
			// it is not possible to compare functions in golang, so always overwrite the old value
		}
		res[rawPath] = rawFunc
	}
	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
