// Package oapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.1 DO NOT EDIT.
package oapi

import (
	"bytes"
	"compress/gzip"
	"context"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"path"
	"strings"

	externalRef0 "github.com/antflydb/antfly-go/libaf/chunking"
	externalRef1 "github.com/antflydb/antfly-go/libaf/logging"
	externalRef2 "github.com/antflydb/antfly-go/libaf/s3"
	externalRef3 "github.com/antflydb/antfly-go/libaf/scraping"
	"github.com/getkin/kin-openapi/openapi3"
	"github.com/oapi-codegen/runtime"
)

// Defines values for ConfigModelStrategies.
const (
	ConfigModelStrategiesBounded ConfigModelStrategies = "bounded"
	ConfigModelStrategiesEager   ConfigModelStrategies = "eager"
	ConfigModelStrategiesLazy    ConfigModelStrategies = "lazy"
)

// Defines values for FinishReason.
const (
	FinishReasonContentFilter FinishReason = "content_filter"
	FinishReasonFunctionCall  FinishReason = "function_call"
	FinishReasonLength        FinishReason = "length"
	FinishReasonStop          FinishReason = "stop"
	FinishReasonToolCalls     FinishReason = "tool_calls"
)

// Defines values for GenerateChunkObject.
const (
	GenerateChunkObjectChatCompletionChunk GenerateChunkObject = "chat.completion.chunk"
)

// Defines values for GenerateResponseObject.
const (
	GenerateResponseObjectChatCompletion GenerateResponseObject = "chat.completion"
)

// Defines values for ImageURLContentPartType.
const (
	ImageURLContentPartTypeImageUrl ImageURLContentPartType = "image_url"
)

// Defines values for RecognizerCapability.
const (
	RecognizerCapabilityAnswers   RecognizerCapability = "answers"
	RecognizerCapabilityLabels    RecognizerCapability = "labels"
	RecognizerCapabilityRelations RecognizerCapability = "relations"
	RecognizerCapabilityZeroshot  RecognizerCapability = "zeroshot"
)

// Defines values for Role.
const (
	RoleAssistant Role = "assistant"
	RoleSystem    Role = "system"
	RoleUser      Role = "user"
)

// Defines values for TextContentPartType.
const (
	TextContentPartTypeText TextContentPartType = "text"
)

// ChatMessage defines model for ChatMessage.
type ChatMessage struct {
	// Content Message content. Supports two formats:
	// - Simple string: "Hello, how are you?"
	// - Array of content parts (OpenAI multimodal format): [{"type": "text", "text": "Hello"}]
	Content ChatMessageContent `json:"content"`

	// Role The role of a message sender in a conversation
	Role Role `json:"role"`
}

// ChatMessageContent Message content. Supports two formats:
// - Simple string: "Hello, how are you?"
// - Array of content parts (OpenAI multimodal format): [{"type": "text", "text": "Hello"}]
type ChatMessageContent struct {
	union json.RawMessage
}

// ChatMessageContent0 Simple text content
type ChatMessageContent0 = string

// ChatMessageContent1 Array of content parts (OpenAI multimodal format)
type ChatMessageContent1 = []ContentPart

// Chunk A chunk of text with position information.
type Chunk = externalRef0.Chunk

// ChunkConfig Configuration for chunking requests to Termite API.
// This is a simplified config for the HTTP API - differs from the full ChunkerConfig
// which includes provider selection and caching configuration.
type ChunkConfig struct {
	// MaxChunks Maximum number of chunks to return
	MaxChunks int `json:"max_chunks,omitempty,omitzero"`

	// Model The chunking model to use. Either 'fixed' for simple token-based chunking, or a model name from models/chunkers/{name}/.
	Model string `json:"model,omitempty,omitzero"`

	// OverlapTokens Number of overlapping tokens between chunks
	OverlapTokens int `json:"overlap_tokens,omitempty,omitzero"`

	// Separator Text separator for fixed chunking
	Separator string `json:"separator,omitempty,omitzero"`

	// TargetTokens Target number of tokens per chunk
	TargetTokens int `json:"target_tokens,omitempty,omitzero"`

	// Threshold Confidence threshold for ONNX models (0.0-1.0)
	Threshold float32 `json:"threshold,omitempty,omitzero"`
}

// ChunkRequest defines model for ChunkRequest.
type ChunkRequest struct {
	// Config Configuration for chunking requests to Termite API.
	// This is a simplified config for the HTTP API - differs from the full ChunkerConfig
	// which includes provider selection and caching configuration.
	Config ChunkConfig `json:"config,omitempty,omitzero"`

	// Text Text to chunk
	Text string `json:"text"`
}

// ChunkResponse defines model for ChunkResponse.
type ChunkResponse struct {
	// CacheHit Whether result was served from cache
	CacheHit bool `json:"cache_hit"`

	// Chunks Array of text chunks
	Chunks []Chunk `json:"chunks"`

	// Model Chunking model actually used (may differ from requested if fallback occurred)
	Model string `json:"model"`
}

// Config defines model for Config.
type Config struct {
	// ApiUrl URL of the Termite embedding/chunking service
	ApiUrl string `json:"api_url"`

	// BackendPriority Backend priority order for model loading with optional device specifiers.
	// Format: `backend` or `backend:device` where device defaults to `auto`.
	//
	// Termite tries entries in order and uses the first available backend+device
	// combination that supports the model.
	//
	// **Backends** (depend on build tags):
	// - `go` - Pure Go inference (always available, CPU only, slowest)
	// - `onnx` - ONNX Runtime (requires -tags="onnx,ORT", fastest)
	// - `xla` - GoMLX XLA (requires -tags="xla,XLA", TPU/CUDA/CPU)
	//
	// **Devices**:
	// - `auto` - Auto-detect best available (default)
	// - `cuda` - NVIDIA CUDA GPU
	// - `coreml` - Apple CoreML (macOS only, used by ONNX)
	// - `tpu` - Google TPU (used by XLA)
	// - `cpu` - Force CPU only
	//
	// **Examples**:
	// - `["onnx", "xla", "go"]` - Try backends with auto device detection
	// - `["onnx:cuda", "xla:tpu", "onnx:cpu", "go"]` - Prefer GPU, fall back to CPU
	// - `["onnx:coreml", "go"]` - macOS with CoreML acceleration
	BackendPriority []string                           `json:"backend_priority,omitempty,omitzero"`
	ContentSecurity externalRef3.ContentSecurityConfig `json:"content_security,omitempty,omitzero"`

	// KeepAlive How long to keep models loaded in memory after last use (Ollama-compatible).
	// Models are automatically unloaded after this duration of inactivity.
	// Use Go duration format: "5m" (5 minutes), "1h" (1 hour), "0" (never unload, eager loading).
	// When set to "0" or omitted, models are loaded eagerly at startup and never unloaded (legacy behavior).
	KeepAlive string `json:"keep_alive,omitempty,omitzero"`

	// Log Logging configuration for Termite services
	Log externalRef1.Config `json:"log,omitempty,omitzero"`

	// MaxConcurrentRequests Maximum number of concurrent inference requests allowed.
	// Additional requests will be queued up to max_queue_size.
	// Set to 0 for unlimited (default).
	MaxConcurrentRequests int `json:"max_concurrent_requests,omitempty,omitzero"`

	// MaxLoadedModels Maximum number of models to keep loaded in memory simultaneously.
	// When this limit is reached, the least recently used model is unloaded (LRU eviction).
	// Set to 0 for unlimited (default). Only effective when keep_alive is non-zero.
	MaxLoadedModels int `json:"max_loaded_models,omitempty,omitzero"`

	// MaxMemoryMb Maximum memory (in MB) to use for loaded models.
	// When this limit is approached, least recently used models are unloaded.
	// Set to 0 for unlimited (default). This is an advisory limit - actual memory
	// usage depends on model sizes and may temporarily exceed this value.
	// Works alongside max_loaded_models for fine-grained control.
	MaxMemoryMb int `json:"max_memory_mb,omitempty,omitzero"`

	// MaxQueueSize Maximum number of requests to queue when max_concurrent_requests is reached.
	// When the queue is full, new requests receive 503 Service Unavailable with Retry-After header.
	// Set to 0 for unlimited queue (default). Only effective when max_concurrent_requests > 0.
	MaxQueueSize int `json:"max_queue_size,omitempty,omitzero"`

	// ModelStrategies Per-model loading strategy overrides. Maps model names to their loading strategy.
	// Models not in this map use the default strategy based on keep_alive:
	// - If keep_alive="0" (default): eager loading (load at startup, never unload)
	// - If keep_alive>0: lazy loading (load on demand, unload after idle)
	//
	// When a model has strategy "eager" in this map:
	// - It is loaded at startup (as part of preload)
	// - It is never unloaded, even when keep_alive>0 (pinned in memory)
	//
	// This allows mixing eager and lazy models in the same pool.
	ModelStrategies map[string]ConfigModelStrategies `json:"model_strategies,omitempty,omitzero"`

	// ModelsDir Base directory containing model subdirectories. Termite auto-discovers models from:
	// - `{models_dir}/embedders/` - Embedding models (ONNX)
	// - `{models_dir}/chunkers/` - Chunking models (ONNX)
	// - `{models_dir}/rerankers/` - Reranking models (ONNX)
	// - `{models_dir}/recognizers/` - Recognition models (ONNX)
	// - `{models_dir}/rewriters/` - Seq2Seq rewriter models (ONNX)
	//
	// Defaults to ~/.termite/models (set via viper). If not set, only built-in fixed chunking is available.
	ModelsDir string `json:"models_dir,omitempty,omitzero"`

	// Preload List of model names to preload at startup (Ollama-compatible).
	// These models are loaded immediately when Termite starts, avoiding first-request latency.
	// Model names should match those in models_dir/embedders/ (e.g., "bge-small-en-v1.5").
	// Only effective when keep_alive is non-zero (lazy loading mode).
	Preload []string `json:"preload,omitempty,omitzero"`

	// RequestTimeout Maximum time to wait for a request to complete, including queue wait time.
	// Use Go duration format: "30s", "1m", "0" (no timeout, default).
	// Requests exceeding this timeout receive 504 Gateway Timeout.
	RequestTimeout string                   `json:"request_timeout,omitempty,omitzero"`
	S3Credentials  externalRef2.Credentials `json:"s3_credentials,omitempty,omitzero"`
}

// ConfigModelStrategies defines model for Config.ModelStrategies.
type ConfigModelStrategies string

// ContentPart A content part for multimodal embedding (text or image)
type ContentPart struct {
	union json.RawMessage
}

// EmbedRequest defines model for EmbedRequest.
type EmbedRequest struct {
	// Input Input content to embed. Supports three formats:
	// - Single text string: `"hello world"`
	// - Array of text strings: `["hello", "world"]`
	// - Array of content parts (multimodal): `[{"type": "text", "text": "hello"}, {"type": "image_url", "image_url": {"url": "data:image/png;base64,..."}}]`
	Input EmbedRequest_Input `json:"input"`

	// Model Name of the embedder model from models_dir/embedders/
	Model string `json:"model"`

	// Truncate Truncate input to fit model context length
	Truncate bool `json:"truncate,omitempty,omitzero"`
}

// EmbedRequestInput0 Single text string (backward compatible)
type EmbedRequestInput0 = string

// EmbedRequestInput1 Array of text strings (backward compatible)
type EmbedRequestInput1 = []string

// EmbedRequestInput2 Array of multimodal content parts (text or images)
type EmbedRequestInput2 = []ContentPart

// EmbedRequest_Input Input content to embed. Supports three formats:
// - Single text string: `"hello world"`
// - Array of text strings: `["hello", "world"]`
// - Array of content parts (multimodal): `[{"type": "text", "text": "hello"}, {"type": "image_url", "image_url": {"url": "data:image/png;base64,..."}}]`
type EmbedRequest_Input struct {
	union json.RawMessage
}

// EmbedResponse defines model for EmbedResponse.
type EmbedResponse struct {
	// Embeddings Array of embedding vectors (one per input string)
	Embeddings [][]float32 `json:"embeddings"`

	// Model Model used for embedding
	Model string `json:"model"`
}

// Error defines model for Error.
type Error struct {
	// Error Error message
	Error string `json:"error"`
}

// FinishReason Reason why generation stopped
type FinishReason string

// GenerateChoice defines model for GenerateChoice.
type GenerateChoice struct {
	// FinishReason Reason why generation stopped
	FinishReason FinishReason `json:"finish_reason"`

	// Index Index of this choice in the list
	Index int `json:"index"`

	// Logprobs Log probability information (not supported, always null)
	Logprobs map[string]interface{} `json:"logprobs,omitzero"`
	Message  GenerateMessage        `json:"message"`
}

// GenerateChunk Streaming generation chunk (SSE event data)
type GenerateChunk struct {
	Choices []GenerateChunkChoice `json:"choices"`
	Created int                   `json:"created"`
	Id      string                `json:"id"`
	Model   string                `json:"model"`
	Object  GenerateChunkObject   `json:"object"`
}

// GenerateChunkObject defines model for GenerateChunk.Object.
type GenerateChunkObject string

// GenerateChunkChoice defines model for GenerateChunkChoice.
type GenerateChunkChoice struct {
	// Delta Delta content for streaming
	Delta GenerateDelta `json:"delta"`

	// FinishReason Reason why generation stopped
	FinishReason FinishReason `json:"finish_reason,omitempty,omitzero"`
	Index        int          `json:"index"`
}

// GenerateDelta Delta content for streaming
type GenerateDelta struct {
	// Content Token content delta
	Content string `json:"content,omitzero"`

	// Role The role of a message sender in a conversation
	Role Role `json:"role,omitempty,omitzero"`
}

// GenerateMessage defines model for GenerateMessage.
type GenerateMessage struct {
	// Content The generated message content
	Content string `json:"content"`

	// Role The role of a message sender in a conversation
	Role Role `json:"role"`
}

// GenerateRequest defines model for GenerateRequest.
type GenerateRequest struct {
	// MaxTokens Maximum tokens to generate
	MaxTokens int `json:"max_tokens,omitempty,omitzero"`

	// Messages Conversation messages (OpenAI-compatible format)
	Messages []ChatMessage `json:"messages"`

	// Model Name of the generator model from models_dir/generators/
	Model string `json:"model"`

	// Stream If true, partial message deltas will be sent as SSE events
	Stream bool `json:"stream,omitempty,omitzero"`

	// Temperature Sampling temperature (0.0 = deterministic, higher = more random)
	Temperature float32 `json:"temperature,omitempty,omitzero"`

	// TopK Top-k sampling (Termite extension, not in OpenAI API)
	TopK int `json:"top_k,omitempty,omitzero"`

	// TopP Nucleus sampling probability
	TopP float32 `json:"top_p,omitempty,omitzero"`
}

// GenerateResponse OpenAI-compatible chat completion response
type GenerateResponse struct {
	// Choices List of completion choices (currently always 1)
	Choices []GenerateChoice `json:"choices"`

	// Created Unix timestamp (seconds) when the completion was created
	Created int `json:"created"`

	// Id A unique identifier for the chat completion
	Id string `json:"id"`

	// Model Model used for generation
	Model string `json:"model"`

	// Object The object type, always "chat.completion"
	Object GenerateResponseObject `json:"object"`
	Usage  GenerateUsage          `json:"usage"`
}

// GenerateResponseObject The object type, always "chat.completion"
type GenerateResponseObject string

// GenerateUsage defines model for GenerateUsage.
type GenerateUsage struct {
	// CompletionTokens Number of tokens in the completion
	CompletionTokens int `json:"completion_tokens"`

	// PromptTokens Number of tokens in the prompt
	PromptTokens int `json:"prompt_tokens"`

	// TotalTokens Total tokens used (prompt + completion)
	TotalTokens int `json:"total_tokens"`
}

// ImageURL Image URL or data URI
type ImageURL struct {
	// Url URL or data URI (data:image/png;base64,...)
	Url string `json:"url"`
}

// ImageURLContentPart Image content for embedding (OpenAI-compatible format)
type ImageURLContentPart struct {
	// ImageUrl Image URL or data URI
	ImageUrl ImageURL                `json:"image_url"`
	Type     ImageURLContentPartType `json:"type"`
}

// ImageURLContentPartType defines model for ImageURLContentPart.Type.
type ImageURLContentPartType string

// ModelsResponse defines model for ModelsResponse.
type ModelsResponse struct {
	// Chunkers Available chunking models (always includes "fixed")
	Chunkers []string `json:"chunkers"`

	// Embedders Available embedding models from models_dir/embedders/
	Embedders []string `json:"embedders"`

	// Extractors Available GLiNER extractor models (zero-shot recognition with custom labels)
	Extractors []string `json:"extractors,omitempty,omitzero"`

	// Generators Available generator/LLM models from models_dir/generators/
	Generators []string `json:"generators"`

	// RecognizerInfo Detailed information about recognizer models including capabilities.
	// Map of model name to model info. Use this to determine what capabilities
	// each recognizer supports (labels, zeroshot, relations, answers).
	RecognizerInfo map[string]RecognizerModelInfo `json:"recognizer_info,omitempty,omitzero"`

	// Recognizers Available recognizer models from models_dir/recognizers/
	Recognizers []string `json:"recognizers"`

	// Rerankers Available reranking models
	Rerankers []string `json:"rerankers"`

	// Rewriters Available Seq2Seq rewriter models from models_dir/rewriters/
	Rewriters []string `json:"rewriters"`
}

// RecognizeEntity defines model for RecognizeEntity.
type RecognizeEntity struct {
	// End Character offset where entity ends (exclusive)
	End int `json:"end"`

	// Label Entity type (PER, ORG, LOC, MISC)
	Label string `json:"label"`

	// Score Confidence score (0.0 to 1.0)
	Score float32 `json:"score"`

	// Start Character offset where entity begins
	Start int `json:"start"`

	// Text The entity text
	Text string `json:"text"`
}

// RecognizeRequest defines model for RecognizeRequest.
type RecognizeRequest struct {
	// Labels Custom entity labels to extract (GLiNER models only).
	// When using a GLiNER model, you can specify any entity types to extract,
	// enabling zero-shot NER without model retraining.
	// If not provided, the model's default labels are used.
	Labels []string `json:"labels,omitempty,omitzero"`

	// Model Name of recognizer model from models_dir/recognizers/
	Model string `json:"model"`

	// RelationLabels Relation types to extract (for models with 'relations' capability).
	// Only used when the model supports relation extraction (GLiNER multitask, REBEL).
	// If not provided, the model extracts all relations it can detect.
	RelationLabels []string `json:"relation_labels,omitempty,omitzero"`

	// Texts Texts to extract entities from
	Texts []string `json:"texts"`
}

// RecognizeResponse defines model for RecognizeResponse.
type RecognizeResponse struct {
	// Entities Array of entity arrays (one per input text)
	Entities [][]RecognizeEntity `json:"entities"`

	// Model Name of model used for NER
	Model string `json:"model"`

	// Relations Array of relation arrays (one per input text).
	// Only present when using a model with 'relations' capability (GLiNER multitask, REBEL).
	Relations [][]Relation `json:"relations,omitempty,omitzero"`
}

// RecognizerCapability Capability that a recognizer model supports:
// - labels: Entity extraction (NER) - extracts labeled spans like PER, ORG, LOC
// - zeroshot: Supports arbitrary labels at inference time (GLiNER models)
// - relations: Relation extraction between entities (GLiNER multitask, REBEL)
// - answers: Extractive question answering (GLiNER multitask)
type RecognizerCapability string

// RecognizerModelInfo Detailed information about a recognizer model
type RecognizerModelInfo struct {
	// Capabilities List of capabilities this recognizer model supports
	Capabilities []RecognizerCapability `json:"capabilities,omitempty,omitzero"`
}

// Relation defines model for Relation.
type Relation struct {
	Head RecognizeEntity `json:"head"`

	// Label The relationship type
	Label string `json:"label"`

	// Score Confidence score for the relation (0.0 to 1.0)
	Score float32         `json:"score"`
	Tail  RecognizeEntity `json:"tail"`
}

// RerankRequest defines model for RerankRequest.
type RerankRequest struct {
	// Model Name of reranking model from models_dir/rerankers/
	Model string `json:"model"`

	// Prompts Pre-rendered document texts to rerank. The client is responsible for extracting
	// and rendering document fields/templates before calling this endpoint.
	Prompts []string `json:"prompts"`

	// Query Search query for relevance scoring
	Query string `json:"query"`
}

// RerankResponse defines model for RerankResponse.
type RerankResponse struct {
	// Model Name of model used for reranking
	Model string `json:"model"`

	// Scores Relevance scores (one per prompt, same order as input)
	Scores []float32 `json:"scores"`
}

// RewriteRequest defines model for RewriteRequest.
type RewriteRequest struct {
	// Inputs Input texts to rewrite/transform
	Inputs []string `json:"inputs"`

	// Model Name of Seq2Seq rewriter model from models_dir/rewriters/
	Model string `json:"model"`
}

// RewriteResponse defines model for RewriteResponse.
type RewriteResponse struct {
	// Model Name of model used for rewriting
	Model string `json:"model"`

	// Texts Rewritten texts (array of arrays, one per input, multiple per beam)
	Texts [][]string `json:"texts"`
}

// Role The role of a message sender in a conversation
type Role string

// TextContentPart Text content for embedding
type TextContentPart struct {
	// Text Text content to embed
	Text string              `json:"text"`
	Type TextContentPartType `json:"type"`
}

// TextContentPartType defines model for TextContentPart.Type.
type TextContentPartType string

// VersionResponse defines model for VersionResponse.
type VersionResponse struct {
	// BuildTime Build timestamp
	BuildTime string `json:"build_time"`

	// GitCommit Git commit hash
	GitCommit string `json:"git_commit"`

	// GoVersion Go runtime version
	GoVersion string `json:"go_version"`

	// Version Termite version
	Version string `json:"version"`
}

// ChunkTextJSONRequestBody defines body for ChunkText for application/json ContentType.
type ChunkTextJSONRequestBody = ChunkRequest

// GenerateEmbeddingsJSONRequestBody defines body for GenerateEmbeddings for application/json ContentType.
type GenerateEmbeddingsJSONRequestBody = EmbedRequest

// GenerateContentJSONRequestBody defines body for GenerateContent for application/json ContentType.
type GenerateContentJSONRequestBody = GenerateRequest

// RecognizeEntitiesJSONRequestBody defines body for RecognizeEntities for application/json ContentType.
type RecognizeEntitiesJSONRequestBody = RecognizeRequest

// RerankPromptsJSONRequestBody defines body for RerankPrompts for application/json ContentType.
type RerankPromptsJSONRequestBody = RerankRequest

// RewriteTextJSONRequestBody defines body for RewriteText for application/json ContentType.
type RewriteTextJSONRequestBody = RewriteRequest

// AsChatMessageContent0 returns the union data inside the ChatMessageContent as a ChatMessageContent0
func (t ChatMessageContent) AsChatMessageContent0() (ChatMessageContent0, error) {
	var body ChatMessageContent0
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromChatMessageContent0 overwrites any union data inside the ChatMessageContent as the provided ChatMessageContent0
func (t *ChatMessageContent) FromChatMessageContent0(v ChatMessageContent0) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeChatMessageContent0 performs a merge with any union data inside the ChatMessageContent, using the provided ChatMessageContent0
func (t *ChatMessageContent) MergeChatMessageContent0(v ChatMessageContent0) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsChatMessageContent1 returns the union data inside the ChatMessageContent as a ChatMessageContent1
func (t ChatMessageContent) AsChatMessageContent1() (ChatMessageContent1, error) {
	var body ChatMessageContent1
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromChatMessageContent1 overwrites any union data inside the ChatMessageContent as the provided ChatMessageContent1
func (t *ChatMessageContent) FromChatMessageContent1(v ChatMessageContent1) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeChatMessageContent1 performs a merge with any union data inside the ChatMessageContent, using the provided ChatMessageContent1
func (t *ChatMessageContent) MergeChatMessageContent1(v ChatMessageContent1) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t ChatMessageContent) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *ChatMessageContent) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}

// AsTextContentPart returns the union data inside the ContentPart as a TextContentPart
func (t ContentPart) AsTextContentPart() (TextContentPart, error) {
	var body TextContentPart
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromTextContentPart overwrites any union data inside the ContentPart as the provided TextContentPart
func (t *ContentPart) FromTextContentPart(v TextContentPart) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeTextContentPart performs a merge with any union data inside the ContentPart, using the provided TextContentPart
func (t *ContentPart) MergeTextContentPart(v TextContentPart) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsImageURLContentPart returns the union data inside the ContentPart as a ImageURLContentPart
func (t ContentPart) AsImageURLContentPart() (ImageURLContentPart, error) {
	var body ImageURLContentPart
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromImageURLContentPart overwrites any union data inside the ContentPart as the provided ImageURLContentPart
func (t *ContentPart) FromImageURLContentPart(v ImageURLContentPart) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeImageURLContentPart performs a merge with any union data inside the ContentPart, using the provided ImageURLContentPart
func (t *ContentPart) MergeImageURLContentPart(v ImageURLContentPart) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t ContentPart) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *ContentPart) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}

// AsEmbedRequestInput0 returns the union data inside the EmbedRequest_Input as a EmbedRequestInput0
func (t EmbedRequest_Input) AsEmbedRequestInput0() (EmbedRequestInput0, error) {
	var body EmbedRequestInput0
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromEmbedRequestInput0 overwrites any union data inside the EmbedRequest_Input as the provided EmbedRequestInput0
func (t *EmbedRequest_Input) FromEmbedRequestInput0(v EmbedRequestInput0) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeEmbedRequestInput0 performs a merge with any union data inside the EmbedRequest_Input, using the provided EmbedRequestInput0
func (t *EmbedRequest_Input) MergeEmbedRequestInput0(v EmbedRequestInput0) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsEmbedRequestInput1 returns the union data inside the EmbedRequest_Input as a EmbedRequestInput1
func (t EmbedRequest_Input) AsEmbedRequestInput1() (EmbedRequestInput1, error) {
	var body EmbedRequestInput1
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromEmbedRequestInput1 overwrites any union data inside the EmbedRequest_Input as the provided EmbedRequestInput1
func (t *EmbedRequest_Input) FromEmbedRequestInput1(v EmbedRequestInput1) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeEmbedRequestInput1 performs a merge with any union data inside the EmbedRequest_Input, using the provided EmbedRequestInput1
func (t *EmbedRequest_Input) MergeEmbedRequestInput1(v EmbedRequestInput1) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsEmbedRequestInput2 returns the union data inside the EmbedRequest_Input as a EmbedRequestInput2
func (t EmbedRequest_Input) AsEmbedRequestInput2() (EmbedRequestInput2, error) {
	var body EmbedRequestInput2
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromEmbedRequestInput2 overwrites any union data inside the EmbedRequest_Input as the provided EmbedRequestInput2
func (t *EmbedRequest_Input) FromEmbedRequestInput2(v EmbedRequestInput2) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeEmbedRequestInput2 performs a merge with any union data inside the EmbedRequest_Input, using the provided EmbedRequestInput2
func (t *EmbedRequest_Input) MergeEmbedRequestInput2(v EmbedRequestInput2) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t EmbedRequest_Input) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *EmbedRequest_Input) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}

// RequestEditorFn  is the function signature for the RequestEditor callback function
type RequestEditorFn func(ctx context.Context, req *http.Request) error

// Doer performs HTTP requests.
//
// The standard http.Client implements this interface.
type HttpRequestDoer interface {
	Do(req *http.Request) (*http.Response, error)
}

// Client which conforms to the OpenAPI3 specification for this service.
type Client struct {
	// The endpoint of the server conforming to this interface, with scheme,
	// https://api.deepmap.com for example. This can contain a path relative
	// to the server, such as https://api.deepmap.com/dev-test, and all the
	// paths in the swagger spec will be appended to the server.
	Server string

	// Doer for performing requests, typically a *http.Client with any
	// customized settings, such as certificate chains.
	Client HttpRequestDoer

	// A list of callbacks for modifying requests which are generated before sending over
	// the network.
	RequestEditors []RequestEditorFn
}

// ClientOption allows setting custom parameters during construction
type ClientOption func(*Client) error

// Creates a new Client, with reasonable defaults
func NewClient(server string, opts ...ClientOption) (*Client, error) {
	// create a client with sane default values
	client := Client{
		Server: server,
	}
	// mutate client and add all optional params
	for _, o := range opts {
		if err := o(&client); err != nil {
			return nil, err
		}
	}
	// ensure the server URL always has a trailing slash
	if !strings.HasSuffix(client.Server, "/") {
		client.Server += "/"
	}
	// create httpClient, if not already present
	if client.Client == nil {
		client.Client = &http.Client{}
	}
	return &client, nil
}

// WithHTTPClient allows overriding the default Doer, which is
// automatically created using http.Client. This is useful for tests.
func WithHTTPClient(doer HttpRequestDoer) ClientOption {
	return func(c *Client) error {
		c.Client = doer
		return nil
	}
}

// WithRequestEditorFn allows setting up a callback function, which will be
// called right before sending the request. This can be used to mutate the request.
func WithRequestEditorFn(fn RequestEditorFn) ClientOption {
	return func(c *Client) error {
		c.RequestEditors = append(c.RequestEditors, fn)
		return nil
	}
}

// The interface specification for the client above.
type ClientInterface interface {
	// ChunkTextWithBody request with any body
	ChunkTextWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	ChunkText(ctx context.Context, body ChunkTextJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GenerateEmbeddingsWithBody request with any body
	GenerateEmbeddingsWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	GenerateEmbeddings(ctx context.Context, body GenerateEmbeddingsJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GenerateContentWithBody request with any body
	GenerateContentWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	GenerateContent(ctx context.Context, body GenerateContentJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// ListModels request
	ListModels(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error)

	// RecognizeEntitiesWithBody request with any body
	RecognizeEntitiesWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	RecognizeEntities(ctx context.Context, body RecognizeEntitiesJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// RerankPromptsWithBody request with any body
	RerankPromptsWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	RerankPrompts(ctx context.Context, body RerankPromptsJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// RewriteTextWithBody request with any body
	RewriteTextWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	RewriteText(ctx context.Context, body RewriteTextJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetVersion request
	GetVersion(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error)
}

func (c *Client) ChunkTextWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewChunkTextRequestWithBody(c.Server, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) ChunkText(ctx context.Context, body ChunkTextJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewChunkTextRequest(c.Server, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GenerateEmbeddingsWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGenerateEmbeddingsRequestWithBody(c.Server, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GenerateEmbeddings(ctx context.Context, body GenerateEmbeddingsJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGenerateEmbeddingsRequest(c.Server, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GenerateContentWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGenerateContentRequestWithBody(c.Server, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GenerateContent(ctx context.Context, body GenerateContentJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGenerateContentRequest(c.Server, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) ListModels(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewListModelsRequest(c.Server)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) RecognizeEntitiesWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewRecognizeEntitiesRequestWithBody(c.Server, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) RecognizeEntities(ctx context.Context, body RecognizeEntitiesJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewRecognizeEntitiesRequest(c.Server, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) RerankPromptsWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewRerankPromptsRequestWithBody(c.Server, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) RerankPrompts(ctx context.Context, body RerankPromptsJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewRerankPromptsRequest(c.Server, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) RewriteTextWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewRewriteTextRequestWithBody(c.Server, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) RewriteText(ctx context.Context, body RewriteTextJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewRewriteTextRequest(c.Server, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetVersion(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetVersionRequest(c.Server)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// NewChunkTextRequest calls the generic ChunkText builder with application/json body
func NewChunkTextRequest(server string, body ChunkTextJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewChunkTextRequestWithBody(server, "application/json", bodyReader)
}

// NewChunkTextRequestWithBody generates requests for ChunkText with any type of body
func NewChunkTextRequestWithBody(server string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/chunk")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewGenerateEmbeddingsRequest calls the generic GenerateEmbeddings builder with application/json body
func NewGenerateEmbeddingsRequest(server string, body GenerateEmbeddingsJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewGenerateEmbeddingsRequestWithBody(server, "application/json", bodyReader)
}

// NewGenerateEmbeddingsRequestWithBody generates requests for GenerateEmbeddings with any type of body
func NewGenerateEmbeddingsRequestWithBody(server string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/embed")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewGenerateContentRequest calls the generic GenerateContent builder with application/json body
func NewGenerateContentRequest(server string, body GenerateContentJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewGenerateContentRequestWithBody(server, "application/json", bodyReader)
}

// NewGenerateContentRequestWithBody generates requests for GenerateContent with any type of body
func NewGenerateContentRequestWithBody(server string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/generate")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewListModelsRequest generates requests for ListModels
func NewListModelsRequest(server string) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/models")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewRecognizeEntitiesRequest calls the generic RecognizeEntities builder with application/json body
func NewRecognizeEntitiesRequest(server string, body RecognizeEntitiesJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewRecognizeEntitiesRequestWithBody(server, "application/json", bodyReader)
}

// NewRecognizeEntitiesRequestWithBody generates requests for RecognizeEntities with any type of body
func NewRecognizeEntitiesRequestWithBody(server string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/recognize")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewRerankPromptsRequest calls the generic RerankPrompts builder with application/json body
func NewRerankPromptsRequest(server string, body RerankPromptsJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewRerankPromptsRequestWithBody(server, "application/json", bodyReader)
}

// NewRerankPromptsRequestWithBody generates requests for RerankPrompts with any type of body
func NewRerankPromptsRequestWithBody(server string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/rerank")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewRewriteTextRequest calls the generic RewriteText builder with application/json body
func NewRewriteTextRequest(server string, body RewriteTextJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewRewriteTextRequestWithBody(server, "application/json", bodyReader)
}

// NewRewriteTextRequestWithBody generates requests for RewriteText with any type of body
func NewRewriteTextRequestWithBody(server string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/rewrite")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewGetVersionRequest generates requests for GetVersion
func NewGetVersionRequest(server string) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/version")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

func (c *Client) applyEditors(ctx context.Context, req *http.Request, additionalEditors []RequestEditorFn) error {
	for _, r := range c.RequestEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	for _, r := range additionalEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	return nil
}

// ClientWithResponses builds on ClientInterface to offer response payloads
type ClientWithResponses struct {
	ClientInterface
}

// NewClientWithResponses creates a new ClientWithResponses, which wraps
// Client with return type handling
func NewClientWithResponses(server string, opts ...ClientOption) (*ClientWithResponses, error) {
	client, err := NewClient(server, opts...)
	if err != nil {
		return nil, err
	}
	return &ClientWithResponses{client}, nil
}

// WithBaseURL overrides the baseURL.
func WithBaseURL(baseURL string) ClientOption {
	return func(c *Client) error {
		newBaseURL, err := url.Parse(baseURL)
		if err != nil {
			return err
		}
		c.Server = newBaseURL.String()
		return nil
	}
}

// ClientWithResponsesInterface is the interface specification for the client with responses above.
type ClientWithResponsesInterface interface {
	// ChunkTextWithBodyWithResponse request with any body
	ChunkTextWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*ChunkTextResponse, error)

	ChunkTextWithResponse(ctx context.Context, body ChunkTextJSONRequestBody, reqEditors ...RequestEditorFn) (*ChunkTextResponse, error)

	// GenerateEmbeddingsWithBodyWithResponse request with any body
	GenerateEmbeddingsWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*GenerateEmbeddingsResponse, error)

	GenerateEmbeddingsWithResponse(ctx context.Context, body GenerateEmbeddingsJSONRequestBody, reqEditors ...RequestEditorFn) (*GenerateEmbeddingsResponse, error)

	// GenerateContentWithBodyWithResponse request with any body
	GenerateContentWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*GenerateContentResponse, error)

	GenerateContentWithResponse(ctx context.Context, body GenerateContentJSONRequestBody, reqEditors ...RequestEditorFn) (*GenerateContentResponse, error)

	// ListModelsWithResponse request
	ListModelsWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*ListModelsResponse, error)

	// RecognizeEntitiesWithBodyWithResponse request with any body
	RecognizeEntitiesWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*RecognizeEntitiesResponse, error)

	RecognizeEntitiesWithResponse(ctx context.Context, body RecognizeEntitiesJSONRequestBody, reqEditors ...RequestEditorFn) (*RecognizeEntitiesResponse, error)

	// RerankPromptsWithBodyWithResponse request with any body
	RerankPromptsWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*RerankPromptsResponse, error)

	RerankPromptsWithResponse(ctx context.Context, body RerankPromptsJSONRequestBody, reqEditors ...RequestEditorFn) (*RerankPromptsResponse, error)

	// RewriteTextWithBodyWithResponse request with any body
	RewriteTextWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*RewriteTextResponse, error)

	RewriteTextWithResponse(ctx context.Context, body RewriteTextJSONRequestBody, reqEditors ...RequestEditorFn) (*RewriteTextResponse, error)

	// GetVersionWithResponse request
	GetVersionWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*GetVersionResponse, error)
}

type ChunkTextResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *ChunkResponse
	JSON400      *Error
	JSON500      *Error
}

// Status returns HTTPResponse.Status
func (r ChunkTextResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r ChunkTextResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type GenerateEmbeddingsResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *EmbedResponse
	JSON400      *Error
	JSON404      *Error
	JSON500      *Error
}

// Status returns HTTPResponse.Status
func (r GenerateEmbeddingsResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GenerateEmbeddingsResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type GenerateContentResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *GenerateResponse
	JSON400      *Error
	JSON404      *Error
	JSON500      *Error
	JSON503      *Error
}

// Status returns HTTPResponse.Status
func (r GenerateContentResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GenerateContentResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type ListModelsResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *ModelsResponse
	JSON400      *Error
	JSON500      *Error
}

// Status returns HTTPResponse.Status
func (r ListModelsResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r ListModelsResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type RecognizeEntitiesResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *RecognizeResponse
	JSON400      *Error
	JSON404      *Error
	JSON500      *Error
	JSON503      *Error
}

// Status returns HTTPResponse.Status
func (r RecognizeEntitiesResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r RecognizeEntitiesResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type RerankPromptsResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *RerankResponse
	JSON400      *Error
	JSON404      *Error
	JSON500      *Error
	JSON503      *Error
}

// Status returns HTTPResponse.Status
func (r RerankPromptsResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r RerankPromptsResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type RewriteTextResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *RewriteResponse
	JSON400      *Error
	JSON404      *Error
	JSON500      *Error
	JSON503      *Error
}

// Status returns HTTPResponse.Status
func (r RewriteTextResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r RewriteTextResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type GetVersionResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *VersionResponse
	JSON400      *Error
}

// Status returns HTTPResponse.Status
func (r GetVersionResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetVersionResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ChunkTextWithBodyWithResponse request with arbitrary body returning *ChunkTextResponse
func (c *ClientWithResponses) ChunkTextWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*ChunkTextResponse, error) {
	rsp, err := c.ChunkTextWithBody(ctx, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseChunkTextResponse(rsp)
}

func (c *ClientWithResponses) ChunkTextWithResponse(ctx context.Context, body ChunkTextJSONRequestBody, reqEditors ...RequestEditorFn) (*ChunkTextResponse, error) {
	rsp, err := c.ChunkText(ctx, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseChunkTextResponse(rsp)
}

// GenerateEmbeddingsWithBodyWithResponse request with arbitrary body returning *GenerateEmbeddingsResponse
func (c *ClientWithResponses) GenerateEmbeddingsWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*GenerateEmbeddingsResponse, error) {
	rsp, err := c.GenerateEmbeddingsWithBody(ctx, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGenerateEmbeddingsResponse(rsp)
}

func (c *ClientWithResponses) GenerateEmbeddingsWithResponse(ctx context.Context, body GenerateEmbeddingsJSONRequestBody, reqEditors ...RequestEditorFn) (*GenerateEmbeddingsResponse, error) {
	rsp, err := c.GenerateEmbeddings(ctx, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGenerateEmbeddingsResponse(rsp)
}

// GenerateContentWithBodyWithResponse request with arbitrary body returning *GenerateContentResponse
func (c *ClientWithResponses) GenerateContentWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*GenerateContentResponse, error) {
	rsp, err := c.GenerateContentWithBody(ctx, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGenerateContentResponse(rsp)
}

func (c *ClientWithResponses) GenerateContentWithResponse(ctx context.Context, body GenerateContentJSONRequestBody, reqEditors ...RequestEditorFn) (*GenerateContentResponse, error) {
	rsp, err := c.GenerateContent(ctx, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGenerateContentResponse(rsp)
}

// ListModelsWithResponse request returning *ListModelsResponse
func (c *ClientWithResponses) ListModelsWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*ListModelsResponse, error) {
	rsp, err := c.ListModels(ctx, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseListModelsResponse(rsp)
}

// RecognizeEntitiesWithBodyWithResponse request with arbitrary body returning *RecognizeEntitiesResponse
func (c *ClientWithResponses) RecognizeEntitiesWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*RecognizeEntitiesResponse, error) {
	rsp, err := c.RecognizeEntitiesWithBody(ctx, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseRecognizeEntitiesResponse(rsp)
}

func (c *ClientWithResponses) RecognizeEntitiesWithResponse(ctx context.Context, body RecognizeEntitiesJSONRequestBody, reqEditors ...RequestEditorFn) (*RecognizeEntitiesResponse, error) {
	rsp, err := c.RecognizeEntities(ctx, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseRecognizeEntitiesResponse(rsp)
}

// RerankPromptsWithBodyWithResponse request with arbitrary body returning *RerankPromptsResponse
func (c *ClientWithResponses) RerankPromptsWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*RerankPromptsResponse, error) {
	rsp, err := c.RerankPromptsWithBody(ctx, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseRerankPromptsResponse(rsp)
}

func (c *ClientWithResponses) RerankPromptsWithResponse(ctx context.Context, body RerankPromptsJSONRequestBody, reqEditors ...RequestEditorFn) (*RerankPromptsResponse, error) {
	rsp, err := c.RerankPrompts(ctx, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseRerankPromptsResponse(rsp)
}

// RewriteTextWithBodyWithResponse request with arbitrary body returning *RewriteTextResponse
func (c *ClientWithResponses) RewriteTextWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*RewriteTextResponse, error) {
	rsp, err := c.RewriteTextWithBody(ctx, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseRewriteTextResponse(rsp)
}

func (c *ClientWithResponses) RewriteTextWithResponse(ctx context.Context, body RewriteTextJSONRequestBody, reqEditors ...RequestEditorFn) (*RewriteTextResponse, error) {
	rsp, err := c.RewriteText(ctx, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseRewriteTextResponse(rsp)
}

// GetVersionWithResponse request returning *GetVersionResponse
func (c *ClientWithResponses) GetVersionWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*GetVersionResponse, error) {
	rsp, err := c.GetVersion(ctx, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetVersionResponse(rsp)
}

// ParseChunkTextResponse parses an HTTP response from a ChunkTextWithResponse call
func ParseChunkTextResponse(rsp *http.Response) (*ChunkTextResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &ChunkTextResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest ChunkResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	}

	return response, nil
}

// ParseGenerateEmbeddingsResponse parses an HTTP response from a GenerateEmbeddingsWithResponse call
func ParseGenerateEmbeddingsResponse(rsp *http.Response) (*GenerateEmbeddingsResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GenerateEmbeddingsResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest EmbedResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	case rsp.StatusCode == 200:
		// Content-type (application/octet-stream) unsupported

	}

	return response, nil
}

// ParseGenerateContentResponse parses an HTTP response from a GenerateContentWithResponse call
func ParseGenerateContentResponse(rsp *http.Response) (*GenerateContentResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GenerateContentResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest GenerateResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 503:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON503 = &dest

	case rsp.StatusCode == 200:
		// Content-type (text/event-stream) unsupported

	}

	return response, nil
}

// ParseListModelsResponse parses an HTTP response from a ListModelsWithResponse call
func ParseListModelsResponse(rsp *http.Response) (*ListModelsResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &ListModelsResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest ModelsResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	}

	return response, nil
}

// ParseRecognizeEntitiesResponse parses an HTTP response from a RecognizeEntitiesWithResponse call
func ParseRecognizeEntitiesResponse(rsp *http.Response) (*RecognizeEntitiesResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &RecognizeEntitiesResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest RecognizeResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 503:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON503 = &dest

	}

	return response, nil
}

// ParseRerankPromptsResponse parses an HTTP response from a RerankPromptsWithResponse call
func ParseRerankPromptsResponse(rsp *http.Response) (*RerankPromptsResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &RerankPromptsResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest RerankResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 503:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON503 = &dest

	}

	return response, nil
}

// ParseRewriteTextResponse parses an HTTP response from a RewriteTextWithResponse call
func ParseRewriteTextResponse(rsp *http.Response) (*RewriteTextResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &RewriteTextResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest RewriteResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 503:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON503 = &dest

	}

	return response, nil
}

// ParseGetVersionResponse parses an HTTP response from a GetVersionWithResponse call
func ParseGetVersionResponse(rsp *http.Response) (*GetVersionResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetVersionResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest VersionResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	}

	return response, nil
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+x9DXPbtrLoX8Fj30zsHkqW7SRN9aZzx3Gc1OfaiY8/TntelJEhEpJQkwADgLbVjt9v",
	"f4PFB8EvWW6a3jP3diYzsUhgsVgs9guL5W9RwvOCM8KUjMa/RTJZkhzDn4dLrE6JlHhB9M9C8IIIRQm8",
	"TDhThCn95/8WZB6No292Kkg7FsxOAOPQ9niII8Ez8ljPc93mQTcmn0sqSBqNP5qOsR/8UxypVUGiccRn",
	"v5AEYHeMOP4tSolMBC0U5SwaR/Y9snCG6KIsCi6UROqOozkXOVZyPGEDdEHzIiNIKkHZYowm0Y8ky3iM",
	"lvwOYUHQipf/MYl0ywMh8ArxuQOKCqwBbn0oCDs4RnmZKZrzFGcW/vYYffxtAvhPIg1ZkXs1iWL/lx9t",
	"Ej18mrAojjgjH+bR+GNzOhZJ3c2NHnnKGNSjh7jZ68kIR3FEFcnlo2tu4J1hAQti8cB6uOjhEyxRyW7a",
	"q3KAEv1CowRTuaNqiQouqX6PKDNoUM6GUdzgRsLSabLEog30cIkFThQRISTEBV1QhjM70JIIYgcnLJVo",
	"i9wnWSnpLdmuCEmZIgsi9JRo2h7ognwuCUsIYmU+IwJmsXRQt0Yx2o3RXoyGw2EHzDi6Hyz4wD4tKVP7",
	"e3ogqbBQf9DMAJbsnI9u2x7g0qPfy1SN7UnTyAKroR5X69O9Y0t2c8jZnC46ZgnPSwELrznRoETZAumR",
	"idSblqNLInKqCDo4Ox5O2OWSSkQlwkjqrUHnlKR6EnO6ABB6YX68vDzTzdEApXQ+J0KiueA5vJuXWYYA",
	"LSIMAhN2t6TJElGWZGVKJCoEv6UpEUiSjCSAHGYpSnCy1LglIdpD2L11js3x/RRmIs2c57jMVDR+MYqb",
	"sgrf07zMA7Yy3fSsBVGl0LDJPdYiwPRvr2/OU5LVxonm9J7o1epZcj0H6KWHKSUZoiOqlkSgZ9DxGZBR",
	"WrnDbwgbzLDURLadY8QFwhYEwzkxxIXfcicxpJU7v+lXDzvDcAoetaYAi/gtERkupjDgY3R77+lluxV6",
	"TqYrmhF1RwizpHycgJIUWGDFRZ2IEwYr26Ch3ni+AxAKZuRpU5usBdGaq8JiQVT3VFtzvYTGoeQx0yyI",
	"3S71GXZOUS0FkUuepbXBRsMXcdeOTEHU+T4wyw/v3/9sVxhtjYajwe5wtB2ODMCMFNfLnHEciBSDPIiU",
	"bglxbrZ7pyliRcd6S6SSMv0iT6+d4m2iRZVIyThboJQnZa6VplpihRghKWzIGUGyyKhClCmOZI6zzC2B",
	"HA6HjwpQwOpTPwVkwZkE08lj9lukZQ6ZLqmKxnOcSRJHTrB8DDXjrl53rblGdb0ycsTwcwQRSIVUBnON",
	"uDYfAlDfW1C7dVDfd8OSJOEsDYB98iLJbvaHpngM5tRco5+WBCSRILLMFLrDEkkibklqRAz0rAg94zwj",
	"mOkRQnHbaQgZA8qJhM1sHWCUlpVTE7l1pV0TrjhRJc6ylRaxKdrK8coqIzMXq+FIiugczXGWzXByg3iS",
	"lEKQdHsTqdlgMD87g18cELqT7fzWqi8PLui0FB3zuzo/cZaPU8kkn5E0pWyx4zWLXi+akBr+S6WK8c5O",
	"xhOcLblU41ejV6MokBeloF2CUpNEc2YhKBdUrWri62PEGbvX5lWGozhacD3LOsavTX/k+iMutFrXAs2s",
	"Ucaxxt6Yoxy64QylRM8AyYIk2rwQcjhhbwHVMbq2OF1rJeh+jE2Pa2uT2f4WUxAe17hU/HqoNYKjnRKU",
	"SESY+R/MO42ctjRKScKdim8xzfAsI8iO9zczwoQlPJ9RZuwnkFbSOztLYuYIY377rSWF/PZbtJWSQlOF",
	"MzQraZYihRdyG1yi6wW/RgN0VgqC3nFtlxMB2mALZ3d4JStUYnR4doU4y1Yxkhm/I1JtAwS9KBoGaIzz",
	"kimaE7Rl+VSigR7shwmsXfzh/FJ7RXMsle9/n2Hd/R0/PfkZ/Xxy0NH3PsPxzycHuuvl2dXO4dWbg53D",
	"s6ttM9M3QBv57bdmRkB4NEAHpeKDlCiSKDQjNapu2ZUyCCRlChi8/+fxm+MDpKGjd2dX5h0XJM8AXKHN",
	"o0MuyOmJ3tzJhwtLDdjusxUQwEBURWmmxBcZ0SijLdfo55MDO6pp85aLhHjSmgkdmX3kZ/TRUM/4k/cZ",
	"Nn8s+CT6pEFcipXjE2kYW5OgYkplTNoQ1FjP2cMbq6I0P8w798uPcCaIFmPvzq5ikFwwnObyQ0smDxbI",
	"1ehtaAWIWfLhJCEZMfb0pGbyfqzQMxtd4wbeskHMPjR/GQngRXvb7GqIcev5TCVJSidd1ukDzNQ8Ww0W",
	"fJrRGZ5PZSKwNjynvCBMS03rHF9YeJVBckNIMcUZvSV1G3PUMjB/5HfGCFEc6V7O5tKCSqsKhnKSc7FC",
	"eK69wwxLpRkObX3IMpzjgUYbKzrLyPZwwk5NZywI8ID2sBOjkpgFaMAordBT54jxOaIMJ4reUrUaTtiV",
	"BGGQBo4aiMJJ9CKfRGjrBcopKxWR23qdd5f62S5a8lLAg5H+zcgtEXbYGBG80Mgb4asR/WlJGJIE7DPT",
	"gwvEc6oUSWNHAz0NizYAyFZISzxto5QFyM1wFK1zM7LAyQrNyBLfUi62h3Xuil7kXVon44unskLGF4sG",
	"J9ilB1+QM9DqTE2dX1s3xDfwCz2IQCh7JxlnWgKnwwk7SFNqtZh/e0f1FiXoc0lKkqKy0FTWeMGDqaS/",
	"kuGEXRjqj0A7liyjWkmllWxs0O55py+K76eG9lOzZk+dpl1px/wtrpc0LzOFGeGlzFaOcYB9AWFtlQqi",
	"zZ40BhWYEb1DBEkIU84UM6qfyoBRTs6vkJaPGrHtTYiBPrBshch8roXpLdGKn6Fqm2vojLPBr0TwBuH2",
	"+whnpjjNZ5sRzVJkizJ0+nrbuvKAr52UoWU3jXBRCG7J1Esis+MckTaiivekGMLpLZUaQzPowNrDFu8J",
	"KyFKa0wRqW0RsyyaGyVsZm0wK5IXXGBBNbHvE0JSM5FbnJWaaX/i4kazP2cLSVOCWgxoXXRGBguBKTOh",
	"IiV41mTn0fcv+xam2iZPZecwigVQDJ/0yISAeatVs9tWv5uXWRYjRu4quHrVNLu9GO2jC2N4oytWWTag",
	"Zc+JEqvBAUj6JcEpEf1raQZ7hM/78J+Uo9E+QaMGbXdH/YGrqVQCK7JwvocXX2eNGHCZa2sA5H4URxn+",
	"dRXF0YyXLCVp4N5UUry+NmdEDOomvx14BSEkQVMih+gUFzKIa8G6qSWhotWrUq6Ma5Fs2DLHBexCvWyW",
	"hNU4JojGQzEB9tzxPHjyg9WXbgHGdV2JtvQfgdqLazpvuwXPLMlojDTFGlA4QynJMUtj291aAzTNCNjS",
	"wIIu0LfUvriby8SsxCQKp25mA/LFWReVet7CEg4h9LYoBKmwhfZ1xR0jcktYU6baqaCtgjIWagXAFSQP",
	"6EGJcnqvZ2kop0UJTN4KBGp2lcQ5QQVvCYLfotmCDCC6MyBscLs7fBGNPd8lS85uVtHYMGBXOMuMMk1p",
	"R1T/NZYEpVSQRGnBqCURpqyKGMhy5t5SzY7OU8TgulCZaFaVbiJzwXPjEPxWDfqwY1xyIuSONraPnIPu",
	"g3eVW1Lr5sO2ulc9ktHfSRCBq17n8GujbglfMPpr1RF+g3H5aNc7QZXreEE+712Qz8g9bfaesDeBD/7/",
	"dobKUHTHtdMm5y3F6JYWRGwP9d7R+1kSFYMDBg6yGlDWCPOCjnNStmlVtsbpMjLtHmgzyQmVyptClRiy",
	"7WtbqtPmv1wSSTpMZprnJKVYkWxldpbjLnN2FCN8yylwCgQdBlaqowwrwhIv8CxGcsnLTOtolSyRWnJJ",
	"YD/6lQrYEG2R4WKoPYHWzppEGuPNTSm0VRNjerimXfqxY//GUZLRYnBLFZxkDAqN9f7e07xFS4+pojnh",
	"pXrMkXPGAIQ/FEd3mCrQtdhpb4hFc421IrE9fNKzsoaCbq87r3XA9kfSeNe7ufnfOFscWSxjFJjv505P",
	"G0sKjky01LRtA2PiOXqHFbnDK3Rp3jVZfH/UydRyf5oIkhKmKM7kk/3p/cp/CqA0w5wuPtkT0/TH011n",
	"0MFpuIkCVgfhPpSJtiBWzAWiOV7AKXF1OL9uPpfkXtXPx9e3P9bgr85Pan0+PcQRCO3eIxHKirJjdsf6",
	"sZ+h4mZCYfrDUhDSSIBgC5db4LIgrifRkmQZR3dcZOkkuq7lPwRN5RjiPEuTxaB5z/b4dL0uZaKi+LYG",
	"8GiWhIX/EKNaU1gazQamffBzrBvavyZRihUew9udgi3+j97+L5/Hw+FwEj08aEzrsiOYeqSN/2RJGTiR",
	"QqtpzXL9eRpNWqKtGU5u7rBIUSChn5K8EVK7F9rGEqx3mGATNBarthHkH5ck0nOA8l7bZPaEwekPqweD",
	"E+aGeqnJpS7Z36aLKFmCVd2bU6IkraNX2xDBltN7ak6VRQgoda9QRthCLTvOpBpSy53JmN3bJbvsru88",
	"BvTCSUbjjx9Hw9Hu3n48GA1Hz1+8jEfD0Xevvv8U6+d7+8/h+YuX3+nnr77/FJzHtanTOpsLB+plmEpU",
	"3oKxKtEWZwROpA2lDK1r/OL/eOyMuK15Nzx+M+YJhC+0aPdIPpVBehYuoEzn6glhMgga9HSP67hCa5Tb",
	"BLzHUDBAukZ9SxmVy3OCpQbbHMU8R3fLFVoQZgPsSCpeFHCc6Lxq/UQ71Z6VOc+mCc7AcnVR8jnNFPhA",
	"85JBnAxadLre78xg5HDJadKRXzgHrKfCo71OmNSm+KA3UEruu9RfSu6N8KASJTCy8/UyKlVnblTGF4Xg",
	"sw5eP+ELpF/hGc2oWoUZatq+8gdt2lm1R2OszDLN8vp/7RY4mdJ2Eau8y3UTd1R0aZqthCwgRAUubtC1",
	"i1+qlenM0rtQguBcb+yAX2yW28XFEbjlCmmdut1KejIkr+/1TaZncjcMp3Qd0giCFUkDBdfK1WvxnxcQ",
	"7SwjQ4kgopQssRpaM5xyNjTZIZ82yoaz0Cokg6N3S41HF6Fvj6QkU3hTGr6Bxg/xH7SzmoTuYTyD4roZ",
	"vnGTqLMZPPa2BmSbOcZrs1Vfnu8lvyHMAzG49G6+igOelJ7cO7FNUqfb2Xd2U5HUSf41Gb1fNY/aTaPX",
	"x8jxfVd62t6Ll71+rslKU9zPMtS70LEjBGzIIDtTQ2+JkEYCuWYufzmIeDw5fznIe9/ctAgNUzs93meZ",
	"+vcN03RB8hwP9ge7swHtXHCzB2r0tilfDU03R8DbYKRTOFGR9iwlU7g67pN6X2CJvOCWnZlTiuSFRrgU",
	"dYN4tznuhZ4JBA2qHpALiH6ArAKRa3miaBKjJV0siUA/oJwLggRmKc8b2YLfxZtYgryY3jySC3rJi8EN",
	"kg65LZ+adK8Ik5Sz2IXobfL7wdlxd+a3Hq1YT4P3ZZKRUlbDBTZCtFH+Y5dp6bfB+r1aeQZ1pNqbQis1",
	"VCk1JFzfNUq7OwoZALFt0ZY998lWzvLZ3Xj7NSzD9fq+kX3G6D2EqqTCeYG2TOKh3DbxQkjHr3C9wxJV",
	"Srk6ifpu9Hx3b/95tzTqyvw/QCWjn0uCKMSj5tSmj5n0/xqVa7tdv0vyIhvgWbK7t9+13zdzYypDrDNr",
	"2tszbW1j3iHdx9uok6a9M4kCP6DxrtO2L59iul51G64b2k5usHW74qpPDbtJ1NRYdw65VV20yUWdQqIQ",
	"PC/Uk6Gabj1iR+GsF+ClfuuAmUxSAwv9LUC1S6A1qF5HPO4gUQOVLrK7kGWH/6XfIEgRFeAhoKvz45a8",
	"6c8rrTqhrd6gXT0rtrsZ/efrD+d3o/98t+CbZGX3RZK7grM9kw4N2SCKvM5WaUR0XfTysX3lye8FZ+XI",
	"VEAedV7gbdzZoyKAOd4OtU5TdZgDww6Z6dMPkuY5ohVD/qbNxKQ2T6LtehzWJTyb89ZBrjeVsoEbCFdq",
	"5VvibLD7tEMcHzZchzVpnpluFnzsPnlqPRvQV4PP6olo3yuBIdK2Du93J/T90TnyjT3VfyWCD+SSwxGP",
	"P2mF3JCklIrnKMMzksnGIiwyyogw2Eex+wnkV1jePG0KlVm8bgq+1c7JyWkf+Xss7I9tE5uy1cBYnwP7",
	"7qlnfu6gekrZnK/LUFnrpnkwsKmONahWhsobojDNIK+hCjXhmT2Ys/2rJAZ3WpjgwtiflMjhhJ3ion54",
	"DLl+JuGNzfkQXUF6CgVPzVntBN2BKROAmjCCk2U4ss8s3zLMEiPNVpqrYiRIBvjKGGEm74iQ2+20Cr2D",
	"4fiVEWGugVTD6dUzYKNPDx2s1t88jhwakV4vi0cURxaREJ7h5I1gfep0/4PEhXVc3F6vJguHGRANGVIj",
	"Uxyl2qXK4Kl5UJvLE7nZZmusx72exNGWcA7M4HZvkD95Q9n0jXUo9GV1tInockEayiPDbKBeeMGV5Z8X",
	"Awh0UM4GgUH9BNS7rtroaYRUDdVLTeDVGSekQpfi9dLiiCmbld66EL3uxjCfzyVx14MJwOi6+Ryk53WG",
	"xvWW6Di4MPB0e7R1dnQeow/n72J08uEwRqfHF4d1C+3s6Lwz0pFwQXquA5vLh9DCBBcUR+27ht9/v0n4",
	"ADJbnkqqGVlQVmP70dOuVVs49qp0RYy/8yVDFzkNTwvXXRV0a+DmATetI0e9tZzTG9ezgq5NEmMGWNRN",
	"K8ghMLYE2rK2hd2JnGUrn7ZfSi0tMAqbxGjFS5RgZi9RrRBmK0+ZVUFC6PGEEYZnEE+pTBUNS5soWgEa",
	"BSaIEiZfbjhhNlPLXtW22d7Q7pn0uZd2IpDGLCGrti4pCiIk+HlgpLOVsczTEhzTFCvyNOn2SPSwqRY2",
	"1gotpdAOFlvFN+1b4HPboEV8tDWvLEUwCZ95LfqsMglWPlELfFAfc3GJi9Y2cF0ddDguc4zhtHmMzo9e",
	"H51sr11FBwGSOisDA1EFbGWuMbUWdG4TguPojosbOQW5kPEEK5JOKXvacupdKLvvEdcoCGxNiVFQdXyq",
	"PY/uTKq6stfAtGdq7pAds2SIKEQKDkvYq4wPv0A3uTCKQf8ROdHn3bk5rcsCMLsZkGhlAOjBu8//NzKU",
	"rer7/ckAbs/l9Wja+26FVNmN/dP1rL1mwm6PFIJA9P0ulI8GlTVbbO1O+R20NEM8TsS+hAfHAmtZSBx6",
	"/DvUSjU3uJ2K2zLQiQ5ISDPSa4yslREKkfdH59toUEkFaEpSJAvMJMroDUE1c0SDc9b8uEqCw2JGlcDC",
	"KzkcXqgyd1Vrug5ykP1yjdF5h4RzFSe8IOhdSA3MOiZjdGQh3MIdD2nrjOiXED9qwtg2ws6GezZ2fzrY",
	"vcsf7Tik7fVH28vYPlioeVi9pwtBK+OV9vJHXa52OGzxE0VMyLhdW6KD5e2GagnLJTGJ3E8UbT0mtrYh",
	"/UouaYFsuC4oB+C13O82rd0Zhpdqa2ztFxsd1WGaPZkGDckDdLSgAut3jb2rXa/+Q+zHzLGap9thjbnL",
	"Da0MsoYL3Jnez/Oiy3o4E7o7S4kgaVBpxNkUBvIQQbGejMJ9T+nO71wQ2csetpgwzFJkANKwdsmckiyV",
	"O4rkRYYVkWhG5nrhE5xlPvObsLTglLXtqGOmjB0MJiNHzUxYE1l/A3c07SM0L1mK9dg4g3ooT7K1PpdE",
	"rLoKb2GRLBG8hZkLkpFb7Pi4md3XRBPhosho4oXiZpl+BpdqDdexXp/99DSzxLNi75buNukDUpDAIjGI",
	"x+aOk60qIY2dUrPJnpqK2UMvi2A3mSDSsT6XXfYlswe7AsDsKIGZ1FjXufVSP9Zcrtu+IyLHbIw6ivn9",
	"od5cd5RqwyBVK0a1GWdacq2l9B/FkRpcD0f2OEYGBaU9Q1i4LexsZ2Myx6hmMsfGtNEukH42Izjv9hge",
	"d9S+0B2ymVYdaphnQBzsc2wkSFrtq0ECm89RCrNpV1KRHE6vwVnHUlKpcC0Vq5pL89JId9mqziPGltG1",
	"pu5V815I57I2ThQbBavWHyb2Vrf6JxGSctbPmFCDBq5VddyYNPVpXNZHbQvtjfaeD0a7g90Xl7uj8f5o",
	"PBr9365pLaiaJjzPu+pNvaOQwZFThZZYLmvwTebG806QfHprptUBkiNhq964NrU0ML473HsxHHWB7YXp",
	"cpq6AN7uDkdd4BrLVHUN6BGHxK9Nq2slm/e13OludWvrr9qff9X+7OeXniIpXbn3i1adTRB9/sqqKXUg",
	"W/ySkVuSfWnxlhMAAqu0ejwH9zFoFwCk06PcDJHaRVM4ho57CHZLxEyzzAoZOlQ6KSWzcgEGBHS/w6ay",
	"qLtXUkkT26AlmjabZQ1Vc7aMs150eam0lWe2PwJiD9Ez182UIU14xgX91dTtkDwjMXr2i+TsmUsbLxNV",
	"alfq7xcf3sfoWcYX81yZt6Z2KZnPaQKO1A1Z/QCFQ1CBqZAxesY4L1y504wwNQxIFqD/izkkMLCjONLd",
	"6mQLGj9Kup5rru06fElCpJzekNW0MzPxpwtkmuiJoeM3wVXPG7KSSnt7csUUvjczJIkgCmWc35TFEL3F",
	"WSZ94a6Dny6mB4eHRxcX0/88+tf0+A0i7JYKzsCXvMWCwsks9dfj61VdV7wUA4PM4IasBrTTvnDeZoeM",
	"3Q/TpFw7d3H8mdwf4hz/yhm+k8OE588QF3qpXTXB70ejkVnGU8qOP9TPIJudozjKKTsxd53Gu10OF1Bq",
	"WtG/m/iWoNUafOkCXBwdnh9dBuvwOxbBDBKsRadHSaT0eX9d+cS2gpSZJbQ1m8lsK1uTZ4WCu95PmnsX",
	"2jDKwGDUmXZKplJmj17ZPGImheDiZOfy5ALGvtjXsoOZqnfSl1YZQxY9tDj46QIK2fn6SQnOKlbquNj5",
	"qCTfsDRce8+bQl5TzdayqzwqVSSzwVPbFum2UJRh5/jM1DvKKLtBKb+DcioSqlqQvFCrGM7SALapCWch",
	"aLOIFAoVgt5qL1rDoXM0y3hyM7UPp7QwNV9FSbaHdf/b/ml3V5KyYf3J7vd7w9Fwb/jEZD1HjAKr5abE",
	"0G1RIcic3hNX/Ckj450dqAMj9/VfV+cnLaLAGCFRhuht0LmUBOGZ5FmpiG1rhdPOldTOfYoV3tk2ncwo",
	"ususTG6I2jH4uB75amCflwUs0E6TniFMLa5aHZ5Gx9Y6PrqLXusetepVFWsggRncxdnd+057HsPRzqsY",
	"7Y6Cv7/bG+6+hF+7ezHSq7/78pX5/TJGuy+/H+69eG5/b3deSnHM66ptTG22fw3z/fZdEFvJQq87ZSm9",
	"pWmJM78VEC9s6g+ctjqYYXG2EWgHmmsbYLevIJjHTtJfyXS2UqSO2O7o+asX370c9VYI0/001zpAtiyZ",
	"qe6HDMBaho6H55EbPeJrUKZePncIm0zflObmRkz9Ttfo+as+PKEfuqOpWu4sCV0sAb+C3kNaqakK4O8b",
	"CaKnVa9cbICvo2hbmj48WDvVXqfD5oKDFnFa84KkjWKTSg6VheV4Z2dB1bKcaXljDfJ0tmOL8LRTLZ0b",
	"YQrV2So6cIRoRH91IAjFp4WvgG4L4Z+eVMX1Juybb9BPSwxxegs4rPJrUxuk0yonAXRTnNVjEJhAB2fH",
	"cCD67bdVAad3PnHt22/HCKI6UCavqt6wdXhyfLbdyl82gKCDK+ykIVyQHDNFkypLG/AJK7278vYDYFhX",
	"pNrA89WeNKwqFi3IwEbmreKHAL6p520xeY9zkroz3qD2kwZkz0SRycyRMeJigRn91aWXQi4HbGDzQQdy",
	"r4LpnbuoJVDIBYuNy2yO4V3U1qVG+4PXKi0wtscN4ROikqGpJ+VECdwrx4pA6cSMYK0gFHLsaHhwSPlO",
	"yhO543Wx5xcCxypXknTxTIIZEiXTnj1LccYZgS8uVAXUMENmH6AkK6UiApjlBDisWr8Gp2nBSO4VEWDa",
	"nR3b2ouEJZDvO+hgw+sdXFCT7n5dmeW1ICT09KxUVVl3DHB+8A4VtCAZZWaUkFXcARzI61xvFZI6lvlc",
	"4oyqle5ySJgSOAM30J4KE3EL5zuJ4FKilGrtNysVSRHjqRnoTKusZDWAZAzTvLb74JqJrTyXEXxLJNK2",
	"qG4hsPcst+2SvSVw4dGu4Deoa18aTjQXJzQHhlupVsPN1bPvrdxmIB2cHQOYzdbFbUsTZ0WmYDng8Zoy",
	"ba77ooIxeMtuJqeVALE2vBUkBqC54+KnCwD1axQU2PwF+EIv/sCojEoEyQInxEKCQ50QL7ix4y/+SLR1",
	"3Xv153pb7wFtuhlg9nbNoSeKBngliWzUsLHRha3r31U+yBYKura00Pv1EEsoxY0MYQy3xggYcWDIKIgS",
	"lNziLEa3VGoLRNKcZlgAPxuq18Rxk3HeVkLXb6ZWBfZt9LeQwwIY6I3ls5UGdtBbPbC3BKCBdWi+d6Nh",
	"7A1MiWd0eXniKs/C1wVMy7dWMwDuNb+2WTbPHTTNMc38XvKqZNM5hBurYyJBWUID8R+lFk+/euV5UC+G",
	"rbnms2lS1b6l84rUAf/q7rUzfBB59qgYbdkz+yVmaaYdEEqyNEgVMjk8GU2IPQpxVk2WoXNtX0l0TswX",
	"L1omTqVTMrLAEKBUVJkPmFRfSIqCY4TodhdnxRLvwlVR44lG42h/OBruR3Hk/Sqz8uCNctkVnikyqt0A",
	"PdOOj59Y1SqdEqhbDY07YM5kOrVMazgAGL4qO9nm9eB7beEnieCDLKr6goP5GpBufOWKIP7g75jpx2+x",
	"NGZT7ca6QwP46tRvp7aF5Gu4OiETbuwBOl0n64ND4fpOe/KOQXZn6l/nxrIC1xV2ZFguW8vmPVedfQjd",
	"CEQL/QW8GVdL9/UsTZbwO3Nuqez3B/Sv6+vrX6RWdL9NGKrVaev5hg4I0Ng0NsMYEcsQ0o9gagaAXaTY",
	"vap9JEk3eTEa+Zf1r0WZt/6l/z6TATyZMP0v0q8fJuwBZmG+uefcwePUfb7l0hxyWNf3NU9XjaoeQUbJ",
	"zi+2yIo5CtjoczIuE+KhfsSinXB4YJQ37Mq90eiPHtsewcLgXYfEwJYpkiWED+dllkEA4fkfiImpk9WB",
	"wTG7xRlNXdRBj/vizxnXmsTW1yO2YRzJMs+xWDnW6JB/kixyKKyhmxt7rF+Kuivr0lZNC2xoG7AICzga",
	"mZo1THrpPoDnjXEqg3qA1oMDe/GZrJuJ1hAyEdx7FZvMMaiSkUJavenburQc+Jc2FxNgBCZgW6Q3vjux",
	"VhaG9Yqr4ra26qn2sswsTI/AC1Ec6noFn3EJsHEe4QCK+ObWsHIRuNad3O0xOkggBBqWXLTWSDX/Jhyw",
	"kutdNU1tXOSW4sq0tSSqmcCmbHVQlBMI5guLfdUSnV3Fg/vLdm5UqdPYyl+nTmfHbfrtL9SFwQc14BAj",
	"CT+ZgeErTmlppA1JJ8zaOLAc8wxCYaYqM5REEyQtWYqZgmsebkM0fTH92B+T+OQnn5oDN3M011iGMrX6",
	"7VeMAsHHE0XUwJQLuvbenSSCah/ZpvNaXy9GOZcK+UPQ7RY0LUavx+AR+joxRhYEl4hBVAQuf2gXGD7W",
	"XBcWP2hx17htPQTav6M0tLUaQCzqRh8bbK/5qZnwOYk+VRp+wk47y/u2WWk9bp3Fo7vwA/vj0X2CUbHk",
	"ipu8sgQrvWk6un7ZzrFVMOwG0uA/rTF9nGqqvPyvZAPVKhv/yTZQvb6qHrtvU9VhNo5GYLcN3G4jabsa",
	"algIagbNOxJsWnZIRfugTty/iyX2fPT8649r68tzbWCULP23sgDdDgmkoDH6fLW7Dey+IA5tDLugyIU1",
	"Kd6RPMdof3s4YW/1oreMO20R2UJmh0us0KEv4yPtB5K/wBYLKmv8gcbYN98gX1gUVCBR6NrsNHMIf21y",
	"vE31+QtYhMGFVolHULYOao9um+lTlghiLhlMmMlJMGXvhugIJ0tbodR+WUN7o9eaShWRwJK/trWxzNcS",
	"bPFJVH0vz0Qh0cc3H94ffboedthu+hEEG3tqr1lj26hRV70QDmTXq5paBROvYhyEupYRPLOqwmQcGz1h",
	"t4p58S9emoVHS5IV8zJDPhl5WFM7FaxSEtEBCbLp/9ckMqrE4eWrROpGey9e2ueGoPoZJFWEGrkyG9DW",
	"e84GvvDntg0vzLBcTrRplqHBz+jsw8Ul6vx6KPCh23xoMtEjD35EE/cJgMHlqiBj1BQXk8i1TdGzrjBE",
	"1wq01mATirkzwaaJ8h+T6OFTBbZGwt3RCKIUzzrpdfHfllaeuyrCVDykJUSNKr3my6FPZ/0atkuzaOqf",
	"bL606kA+2ATfHZB5nabLxvWXu9TiYU8RySE6h0/TS+MzaL+KhTvZe1HxhHHRJc9rFX8rp2sr1Alw5/kv",
	"i+dPtXj06Ptff/R3QS16+826Mvhm3RbjzihyGeAk3e6zxwKbSltTHc6dsdOq71EuiOq6u2RYWlsxElyz",
	"djm42Efl4+rsOq5qlsXo/dF5jMyFzFrpIh9Jd7EuE6NqH2N1x8V023/48ylIBNXbaIlvCboe0FfXSJbz",
	"Ob13ERF7umAGOegruYe23MetIChwlpUSqrSsxSo8ubAxDnvWtsGUGudyR3mhViadtb3gFvw7b5Ea+M2y",
	"cH3W66bwq+vgm00g+HAZfL3OUbVeH0cLuM6ie35UeynQjNlISukY1n/0TDe/fBGjtycH7wf6j9cH55eG",
	"505O//EOdeSz+PPhmi8QuAHa0Lf7MPyYbuK+RNnStydUqlNXHeyrKbxGAco+8Sndcft/lbv8Gv97Hlqc",
	"dDlkRhh6Pu73Wv3GkBABTIPiFo/mZtl8qSpFywpo2Fui9bE/Lx1NRpg2Rk2oFNKfRIoO+fuTk1r1KJsc",
	"d3Z0DufxgJD9Mp3/2lxVe2cS2fyND+fvIKEmxLvqYArzGPO0Ks3jO598ONSdT3wGmu/4ntyhf3FxY7q+",
	"FZglxHc7Pb6AfqdUJiTLzLeLPTVb7np1iLyJw94SSD68/LmtL7bMF1fpqyFn7B7QO2xEF34s4WrOW5wQ",
	"9Pro/NIes7fXTHeuyzx3OJR0lRK7pdiED8zva1RggXOiiHj8jDmMEod1sLx7DDd7bYR4TcGl5sK2ai7V",
	"gsctoVcvXkHJ1wqRtoq4/cl+Rrs4VFew0gkDm9ryV6jyf4LhHn6n9Xdb7p6/GnrFaSZtIq5TSwNb7aLo",
	"TcLySTpVsRDFEbZpvTVVVK916hTRoUniOndVV3xNXBMvtDleeSnVeMJ2hz5p2Y7niq8Yce0yYeSE7WnX",
	"GeoHaDvbl2aZsP0huiAs7ZiT+/oflujazu/af+44JZIuzLdSZfg5V0UyIs1H1O0XkQ3KcJPDyGdN/6pq",
	"TMYXNBl+sS6qWfcdmsiFuk2vqX8B+sjkWNYz8wpB5kR0KrN6et5TdEirfo9XJMAgptXaSjK+g12RIC47",
	"aZXOObWQTiyksflI/qKkKUEmn7FKktIAoKqOa43eBlV1xug9KQXOECPKajdBoHPjgG/C3nLhOc8rccft",
	"oOqbqYmx/3K5YZaBpCmZsOuMznZ8V624kxu4FLKkydLnOVas9HiZoaZa1aDPbKmdr6VSwzpRf7o+rVUK",
	"6hCrdvJ2gf5Spf8zVKnbjF+gSDWISuutKn3ndCmEDdYp00ZZpXU3ZTqiDuDlfbnaqAU3GsNCjIuwhKdE",
	"gJqIUUrg14Ayquwjk9BbNYJ7m7LLwdkgSPLNN8jn+btcsn+4HvVLWD4K6SBanW+KLw7cN2Kh3IAHJFZ9",
	"UGRV7cyVkw3NB/B4scDFUmDpL14B9VxuIkrpHO63QCJS6q5+2fpY7upYVS5L93LVKzPMFiUc27TUqdYm",
	"XUSrSGrIt/5ws1bzaiA/lzgdfF7UE2mcH7doUnaMJuVotJ8sM/ifoNdkxbVp1/NYKiwguCXRkVIY/R2C",
	"A9rfwynNMpxA6E+k8lG3Dwj8FfOCGzXS/nT1VK8b1pcbLHxxr7+0018nNBupp0AydakUo6SCmldrD2Ya",
	"JbBitPClu2I082XCjC5o1+Aadhwaq3/6mlhfbXs1q591ENs2CQth/dfErhsHbMrRro4ZNAOmlB2fwQ9u",
	"IlnW9feYdnBBo4dPD/8/AAD//8TOlGiWogAA",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	for rawPath, rawFunc := range externalRef0.PathToRawSpec(path.Join(path.Dir(pathToFile), "../../../antfly-go/libaf/chunking/openapi.yaml")) {
		if _, ok := res[rawPath]; ok {
			// it is not possible to compare functions in golang, so always overwrite the old value
		}
		res[rawPath] = rawFunc
	}
	for rawPath, rawFunc := range externalRef1.PathToRawSpec(path.Join(path.Dir(pathToFile), "../../../antfly-go/libaf/logging/openapi.yaml")) {
		if _, ok := res[rawPath]; ok {
			// it is not possible to compare functions in golang, so always overwrite the old value
		}
		res[rawPath] = rawFunc
	}
	for rawPath, rawFunc := range externalRef2.PathToRawSpec(path.Join(path.Dir(pathToFile), "../../../antfly-go/libaf/s3/openapi.yaml")) {
		if _, ok := res[rawPath]; ok {
			// it is not possible to compare functions in golang, so always overwrite the old value
		}
		res[rawPath] = rawFunc
	}
	for rawPath, rawFunc := range externalRef3.PathToRawSpec(path.Join(path.Dir(pathToFile), "../../../antfly-go/libaf/scraping/openapi.yaml")) {
		if _, ok := res[rawPath]; ok {
			// it is not possible to compare functions in golang, so always overwrite the old value
		}
		res[rawPath] = rawFunc
	}
	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
