// Package oapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.1 DO NOT EDIT.
package oapi

import (
	"bytes"
	"compress/gzip"
	"context"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"path"
	"strings"

	externalRef0 "github.com/antflydb/antfly-go/libaf/chunking"
	externalRef1 "github.com/antflydb/antfly-go/libaf/logging"
	externalRef2 "github.com/antflydb/antfly-go/libaf/s3"
	externalRef3 "github.com/antflydb/antfly-go/libaf/scraping"
	"github.com/getkin/kin-openapi/openapi3"
	"github.com/oapi-codegen/runtime"
)

// Defines values for ConfigModelStrategies.
const (
	ConfigModelStrategiesBounded ConfigModelStrategies = "bounded"
	ConfigModelStrategiesEager   ConfigModelStrategies = "eager"
	ConfigModelStrategiesLazy    ConfigModelStrategies = "lazy"
)

// Defines values for ImageURLContentPartType.
const (
	ImageURLContentPartTypeImageUrl ImageURLContentPartType = "image_url"
)

// Defines values for TextContentPartType.
const (
	TextContentPartTypeText TextContentPartType = "text"
)

// Chunk A chunk of text with position information.
type Chunk = externalRef0.Chunk

// ChunkConfig Configuration for chunking requests to Termite API.
// This is a simplified config for the HTTP API - differs from the full ChunkerConfig
// which includes provider selection and caching configuration.
type ChunkConfig struct {
	// MaxChunks Maximum number of chunks to return
	MaxChunks int `json:"max_chunks,omitempty,omitzero"`

	// Model The chunking model to use. Either 'fixed' for simple token-based chunking, or a model name from models/chunkers/{name}/.
	Model string `json:"model,omitempty,omitzero"`

	// OverlapTokens Number of overlapping tokens between chunks
	OverlapTokens int `json:"overlap_tokens,omitempty,omitzero"`

	// Separator Text separator for fixed chunking
	Separator string `json:"separator,omitempty,omitzero"`

	// TargetTokens Target number of tokens per chunk
	TargetTokens int `json:"target_tokens,omitempty,omitzero"`

	// Threshold Confidence threshold for ONNX models (0.0-1.0)
	Threshold float32 `json:"threshold,omitempty,omitzero"`
}

// ChunkRequest defines model for ChunkRequest.
type ChunkRequest struct {
	// Config Configuration for chunking requests to Termite API.
	// This is a simplified config for the HTTP API - differs from the full ChunkerConfig
	// which includes provider selection and caching configuration.
	Config ChunkConfig `json:"config,omitempty,omitzero"`

	// Text Text to chunk
	Text string `json:"text"`
}

// ChunkResponse defines model for ChunkResponse.
type ChunkResponse struct {
	// CacheHit Whether result was served from cache
	CacheHit bool `json:"cache_hit"`

	// Chunks Array of text chunks
	Chunks []Chunk `json:"chunks"`

	// Model Chunking model actually used (may differ from requested if fallback occurred)
	Model string `json:"model"`
}

// Config defines model for Config.
type Config struct {
	// ApiUrl URL of the Termite embedding/chunking service
	ApiUrl          string                             `json:"api_url"`
	ContentSecurity externalRef3.ContentSecurityConfig `json:"content_security,omitempty,omitzero"`

	// Gpu GPU acceleration mode:
	// - "auto": Auto-detect GPU availability (default). Uses CUDA on Linux if nvidia-smi is available, CoreML on macOS.
	// - "true": Force GPU on. Will fail at runtime if GPU is not available.
	// - "false": Force GPU off (CPU only).
	//
	// On macOS, CoreML is always used when available (no configuration needed).
	// On Linux, CUDA is auto-detected via nvidia-smi or CUDA library presence.
	// Legacy env var ANTFLY_USE_CUDA=1 still works but this config takes precedence.
	Gpu string `json:"gpu,omitempty,omitzero"`

	// KeepAlive How long to keep models loaded in memory after last use (Ollama-compatible).
	// Models are automatically unloaded after this duration of inactivity.
	// Use Go duration format: "5m" (5 minutes), "1h" (1 hour), "0" (never unload, eager loading).
	// When set to "0" or omitted, models are loaded eagerly at startup and never unloaded (legacy behavior).
	KeepAlive string `json:"keep_alive,omitempty,omitzero"`

	// Log Logging configuration for Termite services
	Log externalRef1.Config `json:"log,omitempty,omitzero"`

	// MaxConcurrentRequests Maximum number of concurrent inference requests allowed.
	// Additional requests will be queued up to max_queue_size.
	// Set to 0 for unlimited (default).
	MaxConcurrentRequests int `json:"max_concurrent_requests,omitempty,omitzero"`

	// MaxLoadedModels Maximum number of models to keep loaded in memory simultaneously.
	// When this limit is reached, the least recently used model is unloaded (LRU eviction).
	// Set to 0 for unlimited (default). Only effective when keep_alive is non-zero.
	MaxLoadedModels int `json:"max_loaded_models,omitempty,omitzero"`

	// MaxMemoryMb Maximum memory (in MB) to use for loaded models.
	// When this limit is approached, least recently used models are unloaded.
	// Set to 0 for unlimited (default). This is an advisory limit - actual memory
	// usage depends on model sizes and may temporarily exceed this value.
	// Works alongside max_loaded_models for fine-grained control.
	MaxMemoryMb int `json:"max_memory_mb,omitempty,omitzero"`

	// MaxQueueSize Maximum number of requests to queue when max_concurrent_requests is reached.
	// When the queue is full, new requests receive 503 Service Unavailable with Retry-After header.
	// Set to 0 for unlimited queue (default). Only effective when max_concurrent_requests > 0.
	MaxQueueSize int `json:"max_queue_size,omitempty,omitzero"`

	// ModelStrategies Per-model loading strategy overrides. Maps model names to their loading strategy.
	// Models not in this map use the default strategy based on keep_alive:
	// - If keep_alive="0" (default): eager loading (load at startup, never unload)
	// - If keep_alive>0: lazy loading (load on demand, unload after idle)
	//
	// When a model has strategy "eager" in this map:
	// - It is loaded at startup (as part of preload)
	// - It is never unloaded, even when keep_alive>0 (pinned in memory)
	//
	// This allows mixing eager and lazy models in the same pool.
	ModelStrategies map[string]ConfigModelStrategies `json:"model_strategies,omitempty,omitzero"`

	// ModelsDir Base directory containing model subdirectories. Termite auto-discovers models from:
	// - `{models_dir}/embedders/` - Embedding models (ONNX)
	// - `{models_dir}/chunkers/` - Chunking models (ONNX)
	// - `{models_dir}/rerankers/` - Reranking models (ONNX)
	//
	// Defaults to ~/.termite/models (set via viper). If not set, only built-in fixed chunking is available.
	ModelsDir string `json:"models_dir,omitempty,omitzero"`

	// Preload List of model names to preload at startup (Ollama-compatible).
	// These models are loaded immediately when Termite starts, avoiding first-request latency.
	// Model names should match those in models_dir/embedders/ (e.g., "bge-small-en-v1.5").
	// Only effective when keep_alive is non-zero (lazy loading mode).
	Preload []string `json:"preload,omitempty,omitzero"`

	// RequestTimeout Maximum time to wait for a request to complete, including queue wait time.
	// Use Go duration format: "30s", "1m", "0" (no timeout, default).
	// Requests exceeding this timeout receive 504 Gateway Timeout.
	RequestTimeout string                   `json:"request_timeout,omitempty,omitzero"`
	S3Credentials  externalRef2.Credentials `json:"s3_credentials,omitempty,omitzero"`
}

// ConfigModelStrategies defines model for Config.ModelStrategies.
type ConfigModelStrategies string

// ContentPart A content part for multimodal embedding (text or image)
type ContentPart struct {
	union json.RawMessage
}

// EmbedRequest defines model for EmbedRequest.
type EmbedRequest struct {
	// Input Input content to embed. Supports three formats:
	// - Single text string: `"hello world"`
	// - Array of text strings: `["hello", "world"]`
	// - Array of content parts (multimodal): `[{"type": "text", "text": "hello"}, {"type": "image_url", "image_url": {"url": "data:image/png;base64,..."}}]`
	Input EmbedRequest_Input `json:"input"`

	// Model Name of the embedder model from models_dir/embedders/
	Model string `json:"model"`

	// Truncate Truncate input to fit model context length
	Truncate bool `json:"truncate,omitempty,omitzero"`
}

// EmbedRequestInput0 Single text string (backward compatible)
type EmbedRequestInput0 = string

// EmbedRequestInput1 Array of text strings (backward compatible)
type EmbedRequestInput1 = []string

// EmbedRequestInput2 Array of multimodal content parts (text or images)
type EmbedRequestInput2 = []ContentPart

// EmbedRequest_Input Input content to embed. Supports three formats:
// - Single text string: `"hello world"`
// - Array of text strings: `["hello", "world"]`
// - Array of content parts (multimodal): `[{"type": "text", "text": "hello"}, {"type": "image_url", "image_url": {"url": "data:image/png;base64,..."}}]`
type EmbedRequest_Input struct {
	union json.RawMessage
}

// EmbedResponse defines model for EmbedResponse.
type EmbedResponse struct {
	// Embeddings Array of embedding vectors (one per input string)
	Embeddings [][]float32 `json:"embeddings"`

	// Model Model used for embedding
	Model string `json:"model"`
}

// Error defines model for Error.
type Error struct {
	// Error Error message
	Error string `json:"error"`
}

// ImageURL Image URL or data URI
type ImageURL struct {
	// Url URL or data URI (data:image/png;base64,...)
	Url string `json:"url"`
}

// ImageURLContentPart Image content for embedding (OpenAI-compatible format)
type ImageURLContentPart struct {
	// ImageUrl Image URL or data URI
	ImageUrl ImageURL                `json:"image_url"`
	Type     ImageURLContentPartType `json:"type"`
}

// ImageURLContentPartType defines model for ImageURLContentPart.Type.
type ImageURLContentPartType string

// ModelsResponse defines model for ModelsResponse.
type ModelsResponse struct {
	// Chunkers Available chunking models (always includes "fixed")
	Chunkers []string `json:"chunkers"`

	// Embedders Available embedding models from models_dir/embedders/
	Embedders []string `json:"embedders"`

	// Rerankers Available reranking models
	Rerankers []string `json:"rerankers"`
}

// RerankRequest defines model for RerankRequest.
type RerankRequest struct {
	// Model Name of reranking model from models_dir/rerankers/
	Model string `json:"model"`

	// Prompts Pre-rendered document texts to rerank. The client is responsible for extracting
	// and rendering document fields/templates before calling this endpoint.
	Prompts []string `json:"prompts"`

	// Query Search query for relevance scoring
	Query string `json:"query"`
}

// RerankResponse defines model for RerankResponse.
type RerankResponse struct {
	// Model Name of model used for reranking
	Model string `json:"model"`

	// Scores Relevance scores (one per prompt, same order as input)
	Scores []float32 `json:"scores"`
}

// TextContentPart Text content for embedding
type TextContentPart struct {
	// Text Text content to embed
	Text string              `json:"text"`
	Type TextContentPartType `json:"type"`
}

// TextContentPartType defines model for TextContentPart.Type.
type TextContentPartType string

// VersionResponse defines model for VersionResponse.
type VersionResponse struct {
	// BuildTime Build timestamp
	BuildTime string `json:"build_time"`

	// GitCommit Git commit hash
	GitCommit string `json:"git_commit"`

	// GoVersion Go runtime version
	GoVersion string `json:"go_version"`

	// Version Termite version
	Version string `json:"version"`
}

// ChunkTextJSONRequestBody defines body for ChunkText for application/json ContentType.
type ChunkTextJSONRequestBody = ChunkRequest

// GenerateEmbeddingsJSONRequestBody defines body for GenerateEmbeddings for application/json ContentType.
type GenerateEmbeddingsJSONRequestBody = EmbedRequest

// RerankPromptsJSONRequestBody defines body for RerankPrompts for application/json ContentType.
type RerankPromptsJSONRequestBody = RerankRequest

// AsTextContentPart returns the union data inside the ContentPart as a TextContentPart
func (t ContentPart) AsTextContentPart() (TextContentPart, error) {
	var body TextContentPart
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromTextContentPart overwrites any union data inside the ContentPart as the provided TextContentPart
func (t *ContentPart) FromTextContentPart(v TextContentPart) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeTextContentPart performs a merge with any union data inside the ContentPart, using the provided TextContentPart
func (t *ContentPart) MergeTextContentPart(v TextContentPart) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsImageURLContentPart returns the union data inside the ContentPart as a ImageURLContentPart
func (t ContentPart) AsImageURLContentPart() (ImageURLContentPart, error) {
	var body ImageURLContentPart
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromImageURLContentPart overwrites any union data inside the ContentPart as the provided ImageURLContentPart
func (t *ContentPart) FromImageURLContentPart(v ImageURLContentPart) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeImageURLContentPart performs a merge with any union data inside the ContentPart, using the provided ImageURLContentPart
func (t *ContentPart) MergeImageURLContentPart(v ImageURLContentPart) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t ContentPart) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *ContentPart) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}

// AsEmbedRequestInput0 returns the union data inside the EmbedRequest_Input as a EmbedRequestInput0
func (t EmbedRequest_Input) AsEmbedRequestInput0() (EmbedRequestInput0, error) {
	var body EmbedRequestInput0
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromEmbedRequestInput0 overwrites any union data inside the EmbedRequest_Input as the provided EmbedRequestInput0
func (t *EmbedRequest_Input) FromEmbedRequestInput0(v EmbedRequestInput0) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeEmbedRequestInput0 performs a merge with any union data inside the EmbedRequest_Input, using the provided EmbedRequestInput0
func (t *EmbedRequest_Input) MergeEmbedRequestInput0(v EmbedRequestInput0) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsEmbedRequestInput1 returns the union data inside the EmbedRequest_Input as a EmbedRequestInput1
func (t EmbedRequest_Input) AsEmbedRequestInput1() (EmbedRequestInput1, error) {
	var body EmbedRequestInput1
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromEmbedRequestInput1 overwrites any union data inside the EmbedRequest_Input as the provided EmbedRequestInput1
func (t *EmbedRequest_Input) FromEmbedRequestInput1(v EmbedRequestInput1) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeEmbedRequestInput1 performs a merge with any union data inside the EmbedRequest_Input, using the provided EmbedRequestInput1
func (t *EmbedRequest_Input) MergeEmbedRequestInput1(v EmbedRequestInput1) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsEmbedRequestInput2 returns the union data inside the EmbedRequest_Input as a EmbedRequestInput2
func (t EmbedRequest_Input) AsEmbedRequestInput2() (EmbedRequestInput2, error) {
	var body EmbedRequestInput2
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromEmbedRequestInput2 overwrites any union data inside the EmbedRequest_Input as the provided EmbedRequestInput2
func (t *EmbedRequest_Input) FromEmbedRequestInput2(v EmbedRequestInput2) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeEmbedRequestInput2 performs a merge with any union data inside the EmbedRequest_Input, using the provided EmbedRequestInput2
func (t *EmbedRequest_Input) MergeEmbedRequestInput2(v EmbedRequestInput2) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t EmbedRequest_Input) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *EmbedRequest_Input) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}

// RequestEditorFn  is the function signature for the RequestEditor callback function
type RequestEditorFn func(ctx context.Context, req *http.Request) error

// Doer performs HTTP requests.
//
// The standard http.Client implements this interface.
type HttpRequestDoer interface {
	Do(req *http.Request) (*http.Response, error)
}

// Client which conforms to the OpenAPI3 specification for this service.
type Client struct {
	// The endpoint of the server conforming to this interface, with scheme,
	// https://api.deepmap.com for example. This can contain a path relative
	// to the server, such as https://api.deepmap.com/dev-test, and all the
	// paths in the swagger spec will be appended to the server.
	Server string

	// Doer for performing requests, typically a *http.Client with any
	// customized settings, such as certificate chains.
	Client HttpRequestDoer

	// A list of callbacks for modifying requests which are generated before sending over
	// the network.
	RequestEditors []RequestEditorFn
}

// ClientOption allows setting custom parameters during construction
type ClientOption func(*Client) error

// Creates a new Client, with reasonable defaults
func NewClient(server string, opts ...ClientOption) (*Client, error) {
	// create a client with sane default values
	client := Client{
		Server: server,
	}
	// mutate client and add all optional params
	for _, o := range opts {
		if err := o(&client); err != nil {
			return nil, err
		}
	}
	// ensure the server URL always has a trailing slash
	if !strings.HasSuffix(client.Server, "/") {
		client.Server += "/"
	}
	// create httpClient, if not already present
	if client.Client == nil {
		client.Client = &http.Client{}
	}
	return &client, nil
}

// WithHTTPClient allows overriding the default Doer, which is
// automatically created using http.Client. This is useful for tests.
func WithHTTPClient(doer HttpRequestDoer) ClientOption {
	return func(c *Client) error {
		c.Client = doer
		return nil
	}
}

// WithRequestEditorFn allows setting up a callback function, which will be
// called right before sending the request. This can be used to mutate the request.
func WithRequestEditorFn(fn RequestEditorFn) ClientOption {
	return func(c *Client) error {
		c.RequestEditors = append(c.RequestEditors, fn)
		return nil
	}
}

// The interface specification for the client above.
type ClientInterface interface {
	// ChunkTextWithBody request with any body
	ChunkTextWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	ChunkText(ctx context.Context, body ChunkTextJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GenerateEmbeddingsWithBody request with any body
	GenerateEmbeddingsWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	GenerateEmbeddings(ctx context.Context, body GenerateEmbeddingsJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// ListModels request
	ListModels(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error)

	// RerankPromptsWithBody request with any body
	RerankPromptsWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	RerankPrompts(ctx context.Context, body RerankPromptsJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetVersion request
	GetVersion(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error)
}

func (c *Client) ChunkTextWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewChunkTextRequestWithBody(c.Server, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) ChunkText(ctx context.Context, body ChunkTextJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewChunkTextRequest(c.Server, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GenerateEmbeddingsWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGenerateEmbeddingsRequestWithBody(c.Server, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GenerateEmbeddings(ctx context.Context, body GenerateEmbeddingsJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGenerateEmbeddingsRequest(c.Server, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) ListModels(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewListModelsRequest(c.Server)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) RerankPromptsWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewRerankPromptsRequestWithBody(c.Server, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) RerankPrompts(ctx context.Context, body RerankPromptsJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewRerankPromptsRequest(c.Server, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetVersion(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetVersionRequest(c.Server)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// NewChunkTextRequest calls the generic ChunkText builder with application/json body
func NewChunkTextRequest(server string, body ChunkTextJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewChunkTextRequestWithBody(server, "application/json", bodyReader)
}

// NewChunkTextRequestWithBody generates requests for ChunkText with any type of body
func NewChunkTextRequestWithBody(server string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/chunk")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewGenerateEmbeddingsRequest calls the generic GenerateEmbeddings builder with application/json body
func NewGenerateEmbeddingsRequest(server string, body GenerateEmbeddingsJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewGenerateEmbeddingsRequestWithBody(server, "application/json", bodyReader)
}

// NewGenerateEmbeddingsRequestWithBody generates requests for GenerateEmbeddings with any type of body
func NewGenerateEmbeddingsRequestWithBody(server string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/embed")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewListModelsRequest generates requests for ListModels
func NewListModelsRequest(server string) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/models")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewRerankPromptsRequest calls the generic RerankPrompts builder with application/json body
func NewRerankPromptsRequest(server string, body RerankPromptsJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewRerankPromptsRequestWithBody(server, "application/json", bodyReader)
}

// NewRerankPromptsRequestWithBody generates requests for RerankPrompts with any type of body
func NewRerankPromptsRequestWithBody(server string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/rerank")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewGetVersionRequest generates requests for GetVersion
func NewGetVersionRequest(server string) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/version")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

func (c *Client) applyEditors(ctx context.Context, req *http.Request, additionalEditors []RequestEditorFn) error {
	for _, r := range c.RequestEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	for _, r := range additionalEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	return nil
}

// ClientWithResponses builds on ClientInterface to offer response payloads
type ClientWithResponses struct {
	ClientInterface
}

// NewClientWithResponses creates a new ClientWithResponses, which wraps
// Client with return type handling
func NewClientWithResponses(server string, opts ...ClientOption) (*ClientWithResponses, error) {
	client, err := NewClient(server, opts...)
	if err != nil {
		return nil, err
	}
	return &ClientWithResponses{client}, nil
}

// WithBaseURL overrides the baseURL.
func WithBaseURL(baseURL string) ClientOption {
	return func(c *Client) error {
		newBaseURL, err := url.Parse(baseURL)
		if err != nil {
			return err
		}
		c.Server = newBaseURL.String()
		return nil
	}
}

// ClientWithResponsesInterface is the interface specification for the client with responses above.
type ClientWithResponsesInterface interface {
	// ChunkTextWithBodyWithResponse request with any body
	ChunkTextWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*ChunkTextResponse, error)

	ChunkTextWithResponse(ctx context.Context, body ChunkTextJSONRequestBody, reqEditors ...RequestEditorFn) (*ChunkTextResponse, error)

	// GenerateEmbeddingsWithBodyWithResponse request with any body
	GenerateEmbeddingsWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*GenerateEmbeddingsResponse, error)

	GenerateEmbeddingsWithResponse(ctx context.Context, body GenerateEmbeddingsJSONRequestBody, reqEditors ...RequestEditorFn) (*GenerateEmbeddingsResponse, error)

	// ListModelsWithResponse request
	ListModelsWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*ListModelsResponse, error)

	// RerankPromptsWithBodyWithResponse request with any body
	RerankPromptsWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*RerankPromptsResponse, error)

	RerankPromptsWithResponse(ctx context.Context, body RerankPromptsJSONRequestBody, reqEditors ...RequestEditorFn) (*RerankPromptsResponse, error)

	// GetVersionWithResponse request
	GetVersionWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*GetVersionResponse, error)
}

type ChunkTextResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *ChunkResponse
	JSON400      *Error
	JSON500      *Error
}

// Status returns HTTPResponse.Status
func (r ChunkTextResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r ChunkTextResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type GenerateEmbeddingsResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *EmbedResponse
	JSON400      *Error
	JSON404      *Error
	JSON500      *Error
}

// Status returns HTTPResponse.Status
func (r GenerateEmbeddingsResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GenerateEmbeddingsResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type ListModelsResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *ModelsResponse
	JSON500      *Error
}

// Status returns HTTPResponse.Status
func (r ListModelsResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r ListModelsResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type RerankPromptsResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *RerankResponse
	JSON400      *Error
	JSON404      *Error
	JSON500      *Error
	JSON503      *Error
}

// Status returns HTTPResponse.Status
func (r RerankPromptsResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r RerankPromptsResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type GetVersionResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *VersionResponse
}

// Status returns HTTPResponse.Status
func (r GetVersionResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetVersionResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ChunkTextWithBodyWithResponse request with arbitrary body returning *ChunkTextResponse
func (c *ClientWithResponses) ChunkTextWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*ChunkTextResponse, error) {
	rsp, err := c.ChunkTextWithBody(ctx, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseChunkTextResponse(rsp)
}

func (c *ClientWithResponses) ChunkTextWithResponse(ctx context.Context, body ChunkTextJSONRequestBody, reqEditors ...RequestEditorFn) (*ChunkTextResponse, error) {
	rsp, err := c.ChunkText(ctx, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseChunkTextResponse(rsp)
}

// GenerateEmbeddingsWithBodyWithResponse request with arbitrary body returning *GenerateEmbeddingsResponse
func (c *ClientWithResponses) GenerateEmbeddingsWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*GenerateEmbeddingsResponse, error) {
	rsp, err := c.GenerateEmbeddingsWithBody(ctx, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGenerateEmbeddingsResponse(rsp)
}

func (c *ClientWithResponses) GenerateEmbeddingsWithResponse(ctx context.Context, body GenerateEmbeddingsJSONRequestBody, reqEditors ...RequestEditorFn) (*GenerateEmbeddingsResponse, error) {
	rsp, err := c.GenerateEmbeddings(ctx, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGenerateEmbeddingsResponse(rsp)
}

// ListModelsWithResponse request returning *ListModelsResponse
func (c *ClientWithResponses) ListModelsWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*ListModelsResponse, error) {
	rsp, err := c.ListModels(ctx, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseListModelsResponse(rsp)
}

// RerankPromptsWithBodyWithResponse request with arbitrary body returning *RerankPromptsResponse
func (c *ClientWithResponses) RerankPromptsWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*RerankPromptsResponse, error) {
	rsp, err := c.RerankPromptsWithBody(ctx, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseRerankPromptsResponse(rsp)
}

func (c *ClientWithResponses) RerankPromptsWithResponse(ctx context.Context, body RerankPromptsJSONRequestBody, reqEditors ...RequestEditorFn) (*RerankPromptsResponse, error) {
	rsp, err := c.RerankPrompts(ctx, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseRerankPromptsResponse(rsp)
}

// GetVersionWithResponse request returning *GetVersionResponse
func (c *ClientWithResponses) GetVersionWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*GetVersionResponse, error) {
	rsp, err := c.GetVersion(ctx, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetVersionResponse(rsp)
}

// ParseChunkTextResponse parses an HTTP response from a ChunkTextWithResponse call
func ParseChunkTextResponse(rsp *http.Response) (*ChunkTextResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &ChunkTextResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest ChunkResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	}

	return response, nil
}

// ParseGenerateEmbeddingsResponse parses an HTTP response from a GenerateEmbeddingsWithResponse call
func ParseGenerateEmbeddingsResponse(rsp *http.Response) (*GenerateEmbeddingsResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GenerateEmbeddingsResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest EmbedResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	case rsp.StatusCode == 200:
		// Content-type (application/octet-stream) unsupported

	}

	return response, nil
}

// ParseListModelsResponse parses an HTTP response from a ListModelsWithResponse call
func ParseListModelsResponse(rsp *http.Response) (*ListModelsResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &ListModelsResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest ModelsResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	}

	return response, nil
}

// ParseRerankPromptsResponse parses an HTTP response from a RerankPromptsWithResponse call
func ParseRerankPromptsResponse(rsp *http.Response) (*RerankPromptsResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &RerankPromptsResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest RerankResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 503:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON503 = &dest

	}

	return response, nil
}

// ParseGetVersionResponse parses an HTTP response from a GetVersionWithResponse call
func ParseGetVersionResponse(rsp *http.Response) (*GetVersionResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetVersionResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest VersionResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+x8a3MbOZLgX0HUXISlueJDku1282I+qNV2r27lx0ry9O41HRRYlSQxQgHVAIoS26H7",
	"7ReZQL2Lkrw9PTcfJsIRFquARCKRb2TW1yjRWa4VKGej2dfIJhvIOP15tinULf6Rgk2MyJ3QKppFpyzB",
	"F0yvmIN7x+6E27BcW4HvmVArbTKOf4+jOMqNzsE4AQQRVLpINtz0gZ5tuOGJA9OExLQRa6G4DAttwEBY",
	"HFRq2QHcJ7KwYguHURy5XQ7RLBLKwRpM9BBHIu0vdAW/FqASYKrIlmBoF5sS6sE0ZkcxO47ZeDwegBlH",
	"96O1HoWnhVDu5BgXso4b93faGcGyg/vBsf0Friv0E60cKFfPtc4ItY4eHuLIwK+FMJBGs1+QLgFYC/W4",
	"Pp8vFQi9/BskDlcndjjTaiXWA7uk54Whg2crbTxKQq0ZrgzWWeY0uwaTCQfs9NP5eK6uN8IyYRlnVmS5",
	"FCsBKW5iJdYEAg/m366vP+FwNmKpWK3AWLYyOqN3q0JKRmiB8QjM1d1GJBsmVCKLFCzLjd6KFAyzICEh",
	"5LhKWcKTDeKWNNEez1WPYzN+v6CdWL/nFS+ki2avpnGHAO/5vciKrMFWfhru2oArDMKGe57lEvz8/vlm",
	"OgXZWidaiXvA09pz5LgHmoXLFBbG7K1wGzDsBU18QWQk4gJz+hbUaMktEjlMjpk2jAcQimfgiUu/7STx",
	"pLWTr/jqYTJubqFCrcNrcaS3YCTPF7TgU3T7UNErTMtxT34qW4K7A1CBlE8T0ELODXfatIk4V3SyHRqi",
	"4FUTiFC0o4o2rc0GEL29Om7W4Ia32tvrNQ1uah6/zRyCuLR3OLhFtzFgN1qmrcWm41fxkESmpOqqObTL",
	"jx8+/Gc4YXYwHU9HR+PpYXNlAua1OB6z1LyhUjzypFKGNcSlF3dEry1KSaU6/oeBVTSL/jSpTc8k2J1J",
	"U8vsV3l4dk73iRbVKkVqtWapTooMlGNuwx1TACkJ5BKYzaVwTCinmc24lOUR2PF4/KQCJay+7KeAzbWy",
	"QBavxOxrhDoHFhvhotmKSwtxVCqWX7xl1KuVBRfNjvDkM3A85Y5Hs6+VgSkHTEu6VNslbSiMdX4TuIeH",
	"uAP1+yegfj8M1kKiVdqA+6VSVEEFPHSVZmOn3ZP7eQOknwzYQjp2xy2zYLaQesVDM2vyL7WWwBWu0FTC",
	"LW/EGL6rfJFKUQgHmX0Wr0U1J3OE1VHEbVPeUrk8cQWXcoeKN2UHGd8FE+X3EuwepEys2IpLueTJLdNJ",
	"UhgD6eFzdGmH7ardefziBqEHmbESuPbx8FwsCjOwv8+XF6U/VBpqyJaQpkKtJ5W9wfMSCbTw3ziXzyYT",
	"qRMuN9q62Zvpm2nU0CKFEUPqM3gsCwtJYYTbPXViXLmV3I3WeiHFkq8WNjEcDcZC56BwX2ce4FWAVyuS",
	"dV60jQIvnO4ZhZ8+fWY8SUBC8GSQ0rO5GrE5TZhHM3ZaOD1KwUHiGI3fciH5UkjhduwgLHA4Zp8tWHb2",
	"+cdTphW7EKq4R0ZQW5EKPrKZIDXl50qI2Zk28P4Cx2Y8+Xg19os6UwAu+k6bBGg5rcbsZyElW3EhGXfM",
	"FMqJDBA4vheWKe1qyAEQqZwOpNWKHZwRSLk7HKOJ+xhWr9BBHOUd31nP5HcbUDVodqB024UiFQspAvsY",
	"Nh17GiCgmnCQsq3gTWJo48dJsTTc7FhuwKLxGs/VBax5smOgtmzLDTv9cP3u4r8Wn6/eLnDGX46YdUiP",
	"O21uLVsWqOyFLf1Ix2/JDYQE0gCvxbmBDXqceQuQL7gUW2izzbTHM/+m77yxcZrhrNK2Ss1TFH7FMsi0",
	"2TG+wihAcuuQmOzgo5Q84yNkc+7EUgKS7b2fzA0QvTCSSrySUQGgB0N7TEuy6xUTiidObIXbjefqswX2",
	"k67fezmcsXn0KptH7OAVy4QqHNjDmM2jow0+O2IbXRh6MMXfCrZgwrIxA75G5DVHZYCI/oysYIHssJ+h",
	"DdOZcA7SuKQBbiOgTQDkDjmW7E6RkyfeXAW1qPSHvYQN3wptDrvn9SobOi2p19+qOqRerzuaI6gK8vm1",
	"Ij2t3KKMX9oO1zP8/woEBsVgyBWrgiEupb6DdDxXp2lKYSGX9ds7ZOglsF8LKCBlRY5URrzowcKK35CR",
	"rzz1p+TWFUoKVNlpQwe1afdyMObg9wtP+4U/s2/dZjjpkvl7XG9FVkjHFejCyl3JOMS+hDBqBgNoyNKY",
	"TI8ElBAUWOVK4+oNrrANRrm4/MxgKyimO3wOMdhHJXcMViuMA7fgdVkt5l5xqtFvYHSHcCf7COe3uMiW",
	"zyNaoMiBUOz9D4chZCN8w6Y8LYdpxPPc6ECmvSTyElcS6VlUqTxmxXi6FRYx9IuOgocT8J6rwvI1sBRy",
	"yr4E6ygZcqMlYUYXyEGWa8ONQGLfJwCp38iWywKZ9mdS0xw1phUpsB4DhlBMwWhtuFA+JeCMll12nn7/",
	"et/B1GLyrezczFYQFM8ne3RCg3nrUwtii+9WhZQxU3BXw8VTQ3Z7NT1hV96VYp9VbVMpnXYJzuxGp6Tp",
	"N8BTMPvP0i/2BJ/vw39eTKcnwKYd2h5N9ycoFtYZ7mBdepOV+vrUyfUVGTqtpPejOJL8t10UR0tdqBTS",
	"hsNaa/H22XwCM/IMFqwOCwvvKFVgRAp2zN7z3DbyF3RubgPC9GbVxhX9IxHkK+M5SSEeWyBhvY5Pluim",
	"miBn8HzVePKXYC/LA5i1bSU7wD8aZi9u2bzDHjx/JNMZQ4p1oGjFUsi4SuMwPXgDIpVwiA4csWCZ0Nlg",
	"dFXuZe5PYh41t+53Q/ql9C5q83zALcu5cSgWuYEaWxrfNtwxgy2ork4NW2EHuVCqaRUIV9I8ZActy8Q9",
	"7tJTDlUJbT4oBOGlyvIMWK57iuBrtFzDiKL4EajR9mj8KppVfJdstLrdRTPPgENpC7/KIhUD2dsfuAWW",
	"CgOJQ8WImogLVceAtliWbwWyYxk3eV9X2ARZ1ZYbwbiQSH7ztV70YeKDLDB2csNG7G0ZclVJmo8fPvzn",
	"YX9alZ7DWe3YdP8kA4bXsy7p18C0ufrRszMJ1P+djJ3f2KQch54fuvBbkYM5HCMLo1hZcDHFE2xZCOlG",
	"QnWyaq2op+vc9dYZ8vUCK/bP6kJYV3kktTYI41ucPeh6X2/AwoDnKrIMUsEdyJ1n8PKQfao+ZnyrBR0Y",
	"pWBGQbkyyR2opNI7ASO70YVEU+mSDXMbbYHEojqiBjewAxivx+iQ9xh8HvkY67keDTtoaRNcruse/jIg",
	"RnGUSJGPtsJR4niUI9Ynx6i9qwxLPyfayaYEeiwwStWFeyqeKm0yBbVOszsuHJk8XhpRSv1pxNpBHHL9",
	"uKtgr3E8Tn40DjqZ2nlEwU/m//cxj2YBy5g1vOjL0lx6h4Yy1Ki8wtiGTX/JfuIO7viOXft3XRY/mQ4y",
	"tT1ZJAYjVCe4tN+cBjmpw5gGlG7+qEz87EkWOVDuEzdu8MrPv/b2AA8DnXqR6ZTLOkfEDigJpw0TGV/T",
	"pZxW8HFFGc7H9nMN966JwEP8+PhzBP/58qI158tDHJHu3JuBFiovBnZ3jo+rHTrtNzRmV0Wea4MacGMA",
	"Au9Y0t9XQq0l+JyjP8QZu5lHG5BSszttZDqPbnBgOz3ph9oZu/klDPa8F2Z8aU9p0tyyg5rihwjg65wO",
	"cR4hNyN0D8r/hc8C/IeYtYbS0SAb+PGNnzMcGP6aRyl3fEZvJ7la/y8U/9cv4/F4PI8eHhDTtu5obD1C",
	"HzzZCEWxnEFriSxXs0LnRrZHS3aw5MntHTcpa2joAbF5PBkcqL0X2rM12N5lGkLQOayWINjDZ2ekW0LQ",
	"wePL/sz0B3SNQuq2tB/BDjYu9DrmpaWXhnR/ny6mUAl37aDKmQJ6N11hICORQ5laCRcQIkrdOyZBrd1m",
	"INnf0VplsttL75DuClI/eOtSKScbzX75ZTqeHh2fxKPpePry1et4Op5+9+b7LzE+Pz55Sc9fvf4On7/5",
	"/kvjoqNPnd6lR3OhvQxTq8ot+YyWHWgFdAHoKeVp3eKX6o+nruT6lveZ9xrePaEsAqr2CslvZZA9B9eg",
	"zODpGeMvbDv0LB+3caXRLANr+RqeRMEDGVq1NCED5gDfMLoLMQy1IPt8ed4rDNh/gVJPYgd7lWj7+md4",
	"mPjrDx8v76b//tNaP+dScp9lHzKWezZdKrEWF7CDjzmo0/OGtxxs4WGPKpU1eUrRVeSvuLTOGNRAvjx5",
	"EYtv48EZNQF81N/UD53ryhBHDchtlZVJuuFVuBWpCk3m/g5vHh227WJ5s+fD0FGGouqCIJH5kEKtCy5H",
	"R9/mVFdq/DGsoRtKPs8YDEcCvWcj8Wb0q/vWWCCEn4+hbTpRaR+3EsxoezzKTr4FhaErVUSniVqTukMM",
	"5aPmvW7mEza6s7vemdQRek//drY9GBzrLHcD1P1kcLpKwUDaKIuAexdKlBDymFFlkRR0aWGZ8TJTijyD",
	"e2d44oRazxVXKfMARbPQYiVApnbiIMsx/rVsCSttgCVcyipuApXmWijXi0DPlTM6LXyhFl15tP1Irwd/",
	"pIuG8IitCpVyXJtLKt74Jn78tQCzG6oS5CbZMHpLOzcgYctVAswm2nRtYxdNxvNcioRiTvtsO+lxqc/w",
	"Mdbbp8ue4L2sbekrVhwMSRNtYICTLlukgIYL4xGPfaJOG/RBufWOTcuj+VZHZg+9AoJDZOoGlMMVRIPm",
	"rmfTHilB6saMgz5zx7p1aoceN2x7C43+CsYKrfYzwrIQMqWUy0BSE99R8sI6nuUtVj6eHr8cTY9GR6+u",
	"j6azk+lsOv0/Q9taC7dIdJYNFfn8JJA0+I5tuN2079uXydHxyctBkHqx9dsaAKmrOodyTBPqWh+Nj1+N",
	"p0Ng98Is03hDALdH4+kQuM4x1VMb9IibxG9ta+gku7mc0tOoMzr/KsP+Vxn2fn7ZU8fQz477cZ16HVR9",
	"VTrb30baHr9I2IL8vfUVFwSETmnnQ/PfA+2KgAxWoT4PkVYSGqWll4cuCbYFs0SW2TFPh7hS5SksizVl",
	"Jmj6HfdF3mXMWWuTMKCnmp63yxaqdD+iuNyLri5cXrgQoTEi9pi9KKf5ivBES23Eb/5q3WoJMXvxN6tV",
	"qBd3pkhcgY7i/776+CFmL6RerzLn3/oyclitREJu4i3s/kJ3+yznwtiYvVBa52XluQTlxg2SNdDHBSMq",
	"3VllKAI4rU22xuAnSbcnBd4vfkwSsHZxC7vFkF46/fmK+SG4MXb+YyMNfAs769CXtTvl+L3fISQGHJNa",
	"3xb5mL3jUlpGhZ5Os9OfrxanZ2dvr64W//72vxbnPzJQW2G0Ik95y42gcEdUV2ftAvudLszIIzO6hd1I",
	"DPoXpS89oGNPmiF7Oa68VHphT8Y8479pxe/sONHZC6YNHnVZwvn9dDr1x/heqPOP7YxFd3IUR5lQFz6l",
	"NzsacieJUoua/sPEDwStz+D3HsDV27PLt9eNc/hvHIJfpHEWg/4yWDTyvhegv7mPeSjy8ruksV6YvFiF",
	"spkda9wDfdPeh9CmVUYeowGUCwsLa+WT6dy3imh0dXUxub64orWvTlB3KN9TY6vqhxnD+TTi9OermFHZ",
	"aShxSrisWWkg6fukJn9mtW9f5n2t3QLZ2g7VpAsHMlweh7EMx9KF7eT8ky9JkkLdslTfUcWDpRtvyHK3",
	"i3EOjQ9lmwECukWQO5YbseUOGMIRK7aUOrldhIcLkftCe1PA4bgdC4c/g3QlqRq3nxx9fzyejo/H35g4",
	"KomRc7d5LjFwLMsNrMQ9lPVZEmaTCZVq2BP86/PlRY8otEaTKGP2rjG5sMD40mpZOAhjg3KafLZg7CTl",
	"jk8O/SS/Ck5ZFsktuInHp5yR7UbheZHTAU269GzCRHXVm/BtdOyd45NS9APOaBWY1azBDFdrjKWPjr/D",
	"yGM8nbyJ2dG08fd3x+Oj1/Tr6DhmePpHr9/4369jdvT6+/Hxq5fh9+FgD0XJvOVN/ML3drQxP+m3LYVb",
	"bjx3oVKxFWnBZSUKDEXNpzrQpS5hNusnp2QdRIY+wNG+mr0KOyt+g8Vy56CN2NH05ZtX372e7i3iw3nI",
	"tSWgUDnoC3CZB9iqcavgVchNn4g1hHKvX5YI+6xzKjJQdYAZkD2evnyzD0+ax+5E6jaTDYj1hvDLxT0l",
	"lv2NYVUBbAC31W4X8cAfo2hfm+IjckN9J5bjCXkMqOLQ8pKmjWJ/rUHtHHY2mayF2xRL1DfBIU+Xk1Cg",
	"06/XK8MIX0saKmykuIWg+usiaOr4MVUzWuhJfH9R17/O1Z/+xH7ecMpCBsBUMhbWCG2dtrQqFw3oFAjX",
	"GDRcoNNP53R7/+c/1zVWP4EK3PvnP88YZXWokrW+2T04uzj/dNjLpXtANKGsvUIIV5Bx5URS3xgQPs2m",
	"u7LTcEQMW3YGeXhVQRbCqjNtBkYh7xgMP6UnfRNVwORdgS47Tvvw9jJmieTWilVIQsa0qXXY6xaq6jXy",
	"LlguuVKQUtlXKdVUis0dUKGxBI662rGSMzw7jIWepDqxk8osVkcHlL/9bGHo+BKumCkUBtkq5VIroD7U",
	"utyQK+ZZkiWysA4MndsFHXZNys6ho46CeweGvKxP56FSGVQigIjU54ibCc+FvwW5qT3kVj6QZlanWneZ",
	"lWdxefoTy0UOUii/SvPUykw/qc4MuRbS8vR+LbgUbodTzkA5wyVFZOFkMBZXa8YTo61lqUBDtCwcpEzp",
	"1C/0Ca1HshtRq4wf3hIEun0MdZoS+BYsQ7cQRxheBXmH4cjeAcef4QT/xIZExHOav09DTmtydavisezn",
	"21vn6CGdfjonMM87l1JCfMoTnYKMO8LjB6HQc65KcGMKXMudvK9lObjTQaY9QH/1WW2XAOJr1ihH/xvx",
	"BR7+yGvvWhvYnCcQINEVfhMvusit7oMtO7jZeyN8c4gygF6UBxYuXc8qoiBA6ilrl5qEQP/g5r9V5RPq",
	"eW4CLVBez7gFwt4TxnNrzIgRR56MBpwRsOUyZlth0RmwIhOSG+JnT/WWZuwyzrta/1XCVF6pVtWhh+x/",
	"NjmsAYP9GPhsh8BO99ba7i2Y9bDO/FcAEMbxyDdEsevri7JPg7org3INSppwb4WY3erW8o5lxYWsZKnS",
	"6s/dQ1OwBjbSKOL1EP+jQPX0W2XHTtutY8g1v/ohdaeIWNWkbvAvTm9dFpLKC3dS7CBcDm64SiXGAgJk",
	"Wt0LanVIN3pSJBBuJUoHQ0p2ia6OZZfgO3573kZtUySsOeUKnXC+rbv+bkTUyOhH2yMu8w0/os8O+KAw",
	"mkUn4+n4JIqjKsTxJ0+BobZDmZJcCvTIcacDLeGssL7xNRiBtgHvlAaU3sv7wLSeA4jh6yLtPq/7qsLe",
	"hxqoTd1VbkT4RgIO/lzWKv+lKj3Ax++49R5MCj59JqwTSYkG8dX7Spz6zkrV8VAqmaZgj9j7x3R94w67",
	"LWnfLDEsSCb+uvRODkWRJJHN5jLUzcdlL+OYpgEl7qq6jKV2m7IXFMniGvd25VG99Y41/rq5ufmbRUP3",
	"da5Yq5xyz5cFSIHGfrBfxqtYxRg+oq15AOGQ4vJV69MROOTVdFq9bH9Dw7+tXlZfrfCA53OF/yJ8/TBX",
	"D7QLksMqMjtPy/b1a3/fEKLQH3S6KyMC8DnExtX1hFK01UeBntVOX1ZFPLRvOzAepgfeeJNUHk+nf++1",
	"w20oLT50X0tsmTJbUCZvVUhJsfzLvyMmvpxtAINzteVSpGUCANd99Y9ZN7jEIeyCMDCObJFl3OxK1hjQ",
	"fxbWGX0ZCod7f2y/Fg1+IthQ3NjwoUPuoFln7XWq7Lj0tvwsUOWMUyt35Rj6YIr8xRe27SYGR8gnU+9d",
	"7EtUMCBQqWUi3JD2a9kaoV4ZDyGMhgvYV+mdLu1HdWGzu6fuQQnNCRhl+V34GY0oxGlGebi6NbCBTRl7",
	"jqjXJguOVZkM65VqHc7YaULZyGZldPBG6v134ZCX3J6KNA0piq3gtWsbSNRygX2TV6N2nggWiAzpH1pJ",
	"P9Tjs7+6/lkF9d5X/mPK6QeKLA9/py1stJ/TfULSbDBHCCmkhdc2GPoHH4eOYyUpK+Wbp7YIwkBaqJQr",
	"R59ZKAWiG4vh4+rGguQK/ZmqSmaXB64JDOU7W31DXFPx6cSBG1lngGc3VXRnwQiMkf3FdRnrxSzT1rHq",
	"PvKwBw3V6M2MIsKyoC3okcZnr0hVNEL+pl/g+Ri5rlkT2+OuWd97aFj/gQ6u4DWQWsRBv3TYHvmpW1k2",
	"j77UFn6u3g924fRZ6XHcBnu8hvAj/+NJOeEs32inKY/DEu5QaAam/j7JCcXRQYAQ/JdHXJ/SNNVR/h/k",
	"A7UakP7BPlC7DQLX3idUbZidWwqStlEpbZD2mxaaH/ZZ0vCBWpeeH1LTvkxE/hN5Yi+nL//4dUMbqEYH",
	"o1DpP5UHWEpIQwt6p6/+Ksga3FA1qCuMsuSqWBL5fvV53PjeoC8bbtd3V3FY6Sl5D6efBBn2qnDsf1TZ",
	"DbrRV86yDd8CuxmJNzfMFquVuC/taYhN/SKn++r42UHZwUwm5ZMsLONq9zhWzbg3WMiQqXnGljpZnbdZ",
	"7na+LqGcUtZu+VR9wwlt+J/oYobPSjS/s5OUH6no6cYLYd37ss7+D1NOnSaMfdJhy9zigG74p5GViyG3",
	"3EuLP8P9MdKlv8jxn6Tak2OrcjB10bnTjIdqdO+nESPtk6Mzn6O7LKv3hRROBDemru/PCutmc3U0Zm99",
	"+q5cryzi9xxaJjrsXB2P2SVhTIJQlfjP1cmYXYFKB/ZU9mByy27C/m6qbz+kYMXad6zbZlO9AwnWf1Em",
	"fB7Co0x35klhnc7Eb9DoPpB6LZJ+lFbnq54Tp3XEr/Jje4nTAz9rUb0Ya6XufQq9nXjNDdAXa3/ta6d2",
	"9vWpNFTHkWz3gVSeGjGIH/VoR0I1IZxIw7mb91ow3gdIFwHSzH8xaF2IFF37LRhb58AQAHVnlKPZu0Z3",
	"xox9gMJwyRQ4/7U2boAmd/y3uXqnTcV5IRVaczs5793Mc1x9xsUzy8iKFObqRorlpJp6w3Ke3NL1O30n",
	"uExj16z0dLtKW3t6Bf8ptGz8MU5lu9/oH+xVdjpOBlRm2Hw4oH85df9fDRWufvLHr15/OKZ0NgrV/i5k",
	"z2U57FhRD6K2erva3nlb2mjceNT17PRxxGxd9Z/E9Bka3+vifc9+I8l4IFp0f60aO/4wweq28AxQOQxp",
	"dnP03HZX7qMziipSkTPswDcXGvdpgX+q27gJz0X08OXh/wUAAP//lsXe9xlgAAA=",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	for rawPath, rawFunc := range externalRef0.PathToRawSpec(path.Join(path.Dir(pathToFile), "../../../antfly-go/libaf/chunking/openapi.yaml")) {
		if _, ok := res[rawPath]; ok {
			// it is not possible to compare functions in golang, so always overwrite the old value
		}
		res[rawPath] = rawFunc
	}
	for rawPath, rawFunc := range externalRef1.PathToRawSpec(path.Join(path.Dir(pathToFile), "../../../antfly-go/libaf/logging/openapi.yaml")) {
		if _, ok := res[rawPath]; ok {
			// it is not possible to compare functions in golang, so always overwrite the old value
		}
		res[rawPath] = rawFunc
	}
	for rawPath, rawFunc := range externalRef2.PathToRawSpec(path.Join(path.Dir(pathToFile), "../../../antfly-go/libaf/s3/openapi.yaml")) {
		if _, ok := res[rawPath]; ok {
			// it is not possible to compare functions in golang, so always overwrite the old value
		}
		res[rawPath] = rawFunc
	}
	for rawPath, rawFunc := range externalRef3.PathToRawSpec(path.Join(path.Dir(pathToFile), "../../../antfly-go/libaf/scraping/openapi.yaml")) {
		if _, ok := res[rawPath]; ok {
			// it is not possible to compare functions in golang, so always overwrite the old value
		}
		res[rawPath] = rawFunc
	}
	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
