//go:build go1.22

// Package termite provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.1 DO NOT EDIT.
package termite

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"

	externalRef0 "github.com/antflydb/antfly-go/libaf/chunking"
	externalRef1 "github.com/antflydb/antfly-go/libaf/logging"
	externalRef2 "github.com/antflydb/antfly-go/libaf/s3"
	externalRef3 "github.com/antflydb/antfly-go/libaf/scraping"
	"github.com/getkin/kin-openapi/openapi3"
	"github.com/oapi-codegen/runtime"
)

// Defines values for ConfigModelStrategies.
const (
	ConfigModelStrategiesBounded ConfigModelStrategies = "bounded"
	ConfigModelStrategiesEager   ConfigModelStrategies = "eager"
	ConfigModelStrategiesLazy    ConfigModelStrategies = "lazy"
)

// Defines values for FinishReason.
const (
	FinishReasonContentFilter FinishReason = "content_filter"
	FinishReasonFunctionCall  FinishReason = "function_call"
	FinishReasonLength        FinishReason = "length"
	FinishReasonStop          FinishReason = "stop"
	FinishReasonToolCalls     FinishReason = "tool_calls"
)

// Defines values for GenerateChunkObject.
const (
	GenerateChunkObjectChatCompletionChunk GenerateChunkObject = "chat.completion.chunk"
)

// Defines values for GenerateResponseObject.
const (
	GenerateResponseObjectChatCompletion GenerateResponseObject = "chat.completion"
)

// Defines values for ImageURLContentPartType.
const (
	ImageURLContentPartTypeImageUrl ImageURLContentPartType = "image_url"
)

// Defines values for MediaContentPartType.
const (
	MediaContentPartTypeMedia MediaContentPartType = "media"
)

// Defines values for RecognizerCapability.
const (
	RecognizerCapabilityAnswers   RecognizerCapability = "answers"
	RecognizerCapabilityLabels    RecognizerCapability = "labels"
	RecognizerCapabilityRelations RecognizerCapability = "relations"
	RecognizerCapabilityZeroshot  RecognizerCapability = "zeroshot"
)

// Defines values for Role.
const (
	RoleAssistant Role = "assistant"
	RoleSystem    Role = "system"
	RoleTool      Role = "tool"
	RoleUser      Role = "user"
)

// Defines values for TextContentPartType.
const (
	TextContentPartTypeText TextContentPartType = "text"
)

// Defines values for ToolType.
const (
	ToolTypeFunction ToolType = "function"
)

// Defines values for ToolCallType.
const (
	ToolCallTypeFunction ToolCallType = "function"
)

// Defines values for ToolCallDeltaType.
const (
	ToolCallDeltaTypeFunction ToolCallDeltaType = "function"
)

// Defines values for ToolChoice0.
const (
	ToolChoice0Auto     ToolChoice0 = "auto"
	ToolChoice0None     ToolChoice0 = "none"
	ToolChoice0Required ToolChoice0 = "required"
)

// Defines values for ToolChoice1Type.
const (
	ToolChoice1TypeFunction ToolChoice1Type = "function"
)

// ChatMessage defines model for ChatMessage.
type ChatMessage struct {
	// Content Message content. Supports two formats:
	// - Simple string: "Hello, how are you?"
	// - Array of content parts (OpenAI multimodal format): [{"type": "text", "text": "Hello"}]
	Content ChatMessageContent `json:"content,omitempty,omitzero"`

	// Role The role of a message sender in a conversation
	Role Role `json:"role"`

	// ToolCallId ID of the tool call this message is responding to (only for role=tool)
	ToolCallId string `json:"tool_call_id,omitempty,omitzero"`

	// ToolCalls Tool calls made by the assistant (only for role=assistant)
	ToolCalls []ToolCall `json:"tool_calls,omitempty,omitzero"`
}

// ChatMessageContent Message content. Supports two formats:
// - Simple string: "Hello, how are you?"
// - Array of content parts (OpenAI multimodal format): [{"type": "text", "text": "Hello"}]
type ChatMessageContent struct {
	union json.RawMessage
}

// ChatMessageContent0 Simple text content
type ChatMessageContent0 = string

// ChatMessageContent1 Array of content parts (OpenAI multimodal format)
type ChatMessageContent1 = []ContentPart

// Chunk A chunk of content. Text chunks have mime_type text/plain.
type Chunk = externalRef0.Chunk

// ChunkConfig Configuration for chunking requests to Termite API.
// This is a simplified config for the HTTP API - differs from the full ChunkerConfig
// which includes provider selection and caching configuration.
type ChunkConfig struct {
	// MaxChunks Maximum number of chunks to return
	MaxChunks int `json:"max_chunks,omitempty,omitzero"`

	// Model The chunking model to use. Either 'fixed' for simple token-based chunking, or a model name from models/chunkers/{name}/.
	Model string `json:"model,omitempty,omitzero"`

	// OverlapDurationMs Overlap duration in ms between audio chunks (default: 0)
	OverlapDurationMs int `json:"overlap_duration_ms,omitempty,omitzero"`

	// OverlapTokens Number of overlapping tokens between chunks
	OverlapTokens int `json:"overlap_tokens,omitempty,omitzero"`

	// Separator Text separator for fixed chunking
	Separator string `json:"separator,omitempty,omitzero"`

	// TargetTokens Target number of tokens per chunk
	TargetTokens int `json:"target_tokens,omitempty,omitzero"`

	// Threshold Confidence threshold for ONNX models (0.0-1.0)
	Threshold float32 `json:"threshold,omitempty,omitzero"`

	// WindowDurationMs Window duration in ms for audio chunking (default: 30000)
	WindowDurationMs int `json:"window_duration_ms,omitempty,omitzero"`
}

// ChunkRequest defines model for ChunkRequest.
type ChunkRequest struct {
	// Config Configuration for chunking requests to Termite API.
	// This is a simplified config for the HTTP API - differs from the full ChunkerConfig
	// which includes provider selection and caching configuration.
	Config ChunkConfig `json:"config,omitempty,omitzero"`

	// Input Input content to chunk. Supports two formats:
	// - Text string: `"This is a long document..."` (backward compatible)
	// - ContentPart: `{"type": "media", "data": "<base64>", "mime_type": "audio/wav"}`
	// - ContentPart: `{"type": "text", "text": "..."}`
	Input ChunkRequest_Input `json:"input,omitempty,omitzero"`

	// Text DEPRECATED: Use 'input' instead. Text to chunk.
	// Deprecated: this property has been marked as deprecated upstream, but no `x-deprecated-reason` was set
	Text string `json:"text,omitempty,omitzero"`
}

// ChunkRequestInput0 Text to chunk (backward compatible)
type ChunkRequestInput0 = string

// ChunkRequest_Input Input content to chunk. Supports two formats:
// - Text string: `"This is a long document..."` (backward compatible)
// - ContentPart: `{"type": "media", "data": "<base64>", "mime_type": "audio/wav"}`
// - ContentPart: `{"type": "text", "text": "..."}`
type ChunkRequest_Input struct {
	union json.RawMessage
}

// ChunkResponse defines model for ChunkResponse.
type ChunkResponse struct {
	// CacheHit Whether result was served from cache
	CacheHit bool `json:"cache_hit"`

	// Chunks Array of text chunks
	Chunks []Chunk `json:"chunks"`

	// Model Chunking model actually used (may differ from requested if fallback occurred)
	Model string `json:"model"`
}

// ClassifyRequest defines model for ClassifyRequest.
type ClassifyRequest struct {
	// HypothesisTemplate Custom hypothesis template for NLI-based classification.
	// Use "{}" as placeholder for the label.
	// Default: "This example is {}."
	HypothesisTemplate string `json:"hypothesis_template,omitempty,omitzero"`

	// Labels Candidate labels for zero-shot classification.
	// The model will predict which label(s) best describe each text.
	Labels []string `json:"labels"`

	// Model Name of classifier model from models_dir/classifiers/
	Model string `json:"model"`

	// MultiLabel If true, allows multiple labels per text (independent scoring).
	// If false (default), scores are normalized across labels.
	MultiLabel bool `json:"multi_label,omitempty,omitzero"`

	// Texts Texts to classify
	Texts []string `json:"texts"`
}

// ClassifyResponse defines model for ClassifyResponse.
type ClassifyResponse struct {
	// Classifications Array of classification results (one per input text).
	// Each result is an array of ClassifyResult sorted by score descending.
	Classifications [][]ClassifyResult `json:"classifications"`

	// Model Name of model used for classification
	Model string `json:"model"`
}

// ClassifyResult defines model for ClassifyResult.
type ClassifyResult struct {
	// Label The predicted class/category
	Label string `json:"label"`

	// Score Confidence score (0.0 to 1.0)
	Score float32 `json:"score"`
}

// Config defines model for Config.
type Config struct {
	// ApiUrl URL of the Termite embedding/chunking service
	ApiUrl string `json:"api_url"`

	// BackendPriority Backend priority order for model loading with optional device specifiers.
	// Format: `backend` or `backend:device` where device defaults to `auto`.
	//
	// Termite tries entries in order and uses the first available backend+device
	// combination that supports the model.
	//
	// **Backends** (depend on build tags):
	// - `go` - Pure Go inference (always available, CPU only, slowest)
	// - `onnx` - ONNX Runtime (requires -tags="onnx,ORT", fastest)
	// - `xla` - GoMLX XLA (requires -tags="xla,XLA", TPU/CUDA/CPU)
	//
	// **Devices**:
	// - `auto` - Auto-detect best available (default)
	// - `cuda` - NVIDIA CUDA GPU
	// - `coreml` - Apple CoreML (macOS only, used by ONNX)
	// - `tpu` - Google TPU (used by XLA)
	// - `cpu` - Force CPU only
	//
	// **Examples**:
	// - `["onnx", "xla", "go"]` - Try backends with auto device detection
	// - `["onnx:cuda", "xla:tpu", "onnx:cpu", "go"]` - Prefer GPU, fall back to CPU
	// - `["onnx:coreml", "go"]` - macOS with CoreML acceleration
	BackendPriority []string                           `json:"backend_priority,omitempty,omitzero"`
	ContentSecurity externalRef3.ContentSecurityConfig `json:"content_security,omitempty,omitzero"`

	// KeepAlive How long to keep models loaded in memory after last use (Ollama-compatible).
	// Models are automatically unloaded after this duration of inactivity.
	// Use Go duration format: "5m" (5 minutes), "1h" (1 hour), "0" (eager loading).
	// Defaults to "5m" (lazy loading) like Ollama. Set to "0" to explicitly enable eager loading
	// where all models are loaded at startup and never unloaded.
	KeepAlive string `json:"keep_alive,omitempty,omitzero"`

	// Log Logging configuration for Termite services
	Log externalRef1.Config `json:"log,omitempty,omitzero"`

	// MaxConcurrentRequests Maximum number of concurrent inference requests allowed.
	// Additional requests will be queued up to max_queue_size.
	// Set to 0 for unlimited (default).
	MaxConcurrentRequests int `json:"max_concurrent_requests,omitempty,omitzero"`

	// MaxLoadedModels Maximum number of models to keep loaded in memory simultaneously.
	// When this limit is reached, the least recently used model is unloaded (LRU eviction).
	// Set to 0 for unlimited (default). Only effective when keep_alive is non-zero.
	MaxLoadedModels int `json:"max_loaded_models,omitempty,omitzero"`

	// MaxMemoryMb Maximum memory (in MB) to use for loaded models.
	// When this limit is approached, least recently used models are unloaded.
	// Set to 0 for unlimited (default). This is an advisory limit - actual memory
	// usage depends on model sizes and may temporarily exceed this value.
	// Works alongside max_loaded_models for fine-grained control.
	MaxMemoryMb int `json:"max_memory_mb,omitempty,omitzero"`

	// MaxQueueSize Maximum number of requests to queue when max_concurrent_requests is reached.
	// When the queue is full, new requests receive 503 Service Unavailable with Retry-After header.
	// Set to 0 for unlimited queue (default). Only effective when max_concurrent_requests > 0.
	MaxQueueSize int `json:"max_queue_size,omitempty,omitzero"`

	// ModelStrategies Per-model loading strategy overrides. Maps model names to their loading strategy.
	// Models not in this map use the default strategy based on keep_alive:
	// - If keep_alive>0 (default "5m"): lazy loading (load on demand, unload after idle)
	// - If keep_alive="0": eager loading (load at startup, never unload)
	//
	// When a model has strategy "eager" in this map:
	// - It is loaded at startup (as part of preload)
	// - It is never unloaded, even when keep_alive>0 (pinned in memory)
	//
	// This allows mixing eager and lazy models in the same pool.
	ModelStrategies map[string]ConfigModelStrategies `json:"model_strategies,omitempty,omitzero"`

	// ModelsDir Base directory containing model subdirectories. Termite auto-discovers models from:
	// - `{models_dir}/embedders/` - Embedding models (ONNX)
	// - `{models_dir}/chunkers/` - Chunking models (ONNX)
	// - `{models_dir}/rerankers/` - Reranking models (ONNX)
	// - `{models_dir}/recognizers/` - Recognition models (ONNX)
	// - `{models_dir}/rewriters/` - Seq2Seq rewriter models (ONNX)
	//
	// Defaults to ~/.termite/models (set via viper). If not set, only built-in fixed chunking is available.
	ModelsDir string `json:"models_dir,omitempty,omitzero"`

	// PoolSize Number of concurrent inference pipelines per model. Each pipeline loads
	// a copy of the model, so higher values use more memory but allow more
	// concurrent requests. Set to 0 to use the default (min(NumCPU, 4)).
	PoolSize int `json:"pool_size,omitempty,omitzero"`

	// Preload List of model names to preload at startup (Ollama-compatible).
	// These models are loaded immediately when Termite starts, avoiding first-request latency.
	// Model names should match those in models_dir/embedders/ (e.g., "BAAI/bge-small-en-v1.5").
	// Only effective when keep_alive is non-zero (lazy loading mode).
	Preload []string `json:"preload,omitempty,omitzero"`

	// RequestTimeout Maximum time to wait for a request to complete, including queue wait time.
	// Use Go duration format: "30s", "1m", "0" (no timeout, default).
	// Requests exceeding this timeout receive 504 Gateway Timeout.
	RequestTimeout string                   `json:"request_timeout,omitempty,omitzero"`
	S3Credentials  externalRef2.Credentials `json:"s3_credentials,omitempty,omitzero"`
}

// ConfigModelStrategies defines model for Config.ModelStrategies.
type ConfigModelStrategies string

// ContentPart A content part for multimodal input (text, image URL, or inline media)
type ContentPart struct {
	union json.RawMessage
}

// EmbedRequest defines model for EmbedRequest.
type EmbedRequest struct {
	// Input Input content to embed. Supports three formats:
	// - Single text string: `"hello world"`
	// - Array of text strings: `["hello", "world"]`
	// - Array of content parts (multimodal): `[{"type": "text", "text": "hello"}, {"type": "image_url", "image_url": {"url": "data:image/png;base64,..."}}]`
	Input EmbedRequest_Input `json:"input"`

	// Model Name of the embedder model from models_dir/embedders/
	Model string `json:"model"`

	// Truncate Truncate input to fit model context length
	Truncate bool `json:"truncate,omitempty,omitzero"`
}

// EmbedRequestInput0 Single text string (backward compatible)
type EmbedRequestInput0 = string

// EmbedRequestInput1 Array of text strings (backward compatible)
type EmbedRequestInput1 = []string

// EmbedRequestInput2 Array of multimodal content parts (text or images)
type EmbedRequestInput2 = []ContentPart

// EmbedRequest_Input Input content to embed. Supports three formats:
// - Single text string: `"hello world"`
// - Array of text strings: `["hello", "world"]`
// - Array of content parts (multimodal): `[{"type": "text", "text": "hello"}, {"type": "image_url", "image_url": {"url": "data:image/png;base64,..."}}]`
type EmbedRequest_Input struct {
	union json.RawMessage
}

// EmbedResponse defines model for EmbedResponse.
type EmbedResponse struct {
	// Embeddings Array of embedding vectors (one per input string)
	Embeddings [][]float32 `json:"embeddings"`

	// Model Model used for embedding
	Model string `json:"model"`
}

// Error defines model for Error.
type Error struct {
	// Error Error message
	Error string `json:"error"`
}

// FinishReason Reason why generation stopped
type FinishReason string

// FunctionDefinition Definition of a function that can be called by the model
type FunctionDefinition struct {
	// Description A description of what the function does
	Description string `json:"description,omitempty,omitzero"`

	// Name The name of the function to call
	Name string `json:"name"`

	// Parameters JSON Schema object describing the function parameters
	Parameters map[string]interface{} `json:"parameters,omitempty,omitzero"`

	// Strict Whether to enforce strict parameter validation
	Strict bool `json:"strict,omitempty,omitzero"`
}

// GenerateChoice defines model for GenerateChoice.
type GenerateChoice struct {
	// FinishReason Reason why generation stopped
	FinishReason FinishReason `json:"finish_reason"`

	// Index Index of this choice in the list
	Index int `json:"index"`

	// Logprobs Log probability information (not supported, always null)
	Logprobs map[string]interface{} `json:"logprobs,omitzero"`
	Message  GenerateMessage        `json:"message"`
}

// GenerateChunk Streaming generation chunk (SSE event data)
type GenerateChunk struct {
	Choices []GenerateChunkChoice `json:"choices"`
	Created int                   `json:"created"`
	Id      string                `json:"id"`
	Model   string                `json:"model"`
	Object  GenerateChunkObject   `json:"object"`
}

// GenerateChunkObject defines model for GenerateChunk.Object.
type GenerateChunkObject string

// GenerateChunkChoice defines model for GenerateChunkChoice.
type GenerateChunkChoice struct {
	// Delta Delta content for streaming
	Delta GenerateDelta `json:"delta"`

	// FinishReason Reason why generation stopped
	FinishReason FinishReason `json:"finish_reason,omitempty,omitzero"`
	Index        int          `json:"index"`
}

// GenerateDelta Delta content for streaming
type GenerateDelta struct {
	// Content Token content delta
	Content string `json:"content,omitzero"`

	// Role The role of a message sender in a conversation
	Role Role `json:"role,omitempty,omitzero"`

	// ToolCalls Tool call deltas for streaming tool calls
	ToolCalls []ToolCallDelta `json:"tool_calls,omitempty,omitzero"`
}

// GenerateMessage defines model for GenerateMessage.
type GenerateMessage struct {
	// Content The generated message content (null when tool_calls is present)
	Content string `json:"content,omitzero"`

	// Role The role of a message sender in a conversation
	Role Role `json:"role"`

	// ToolCalls Tool calls made by the model (only present when finish_reason is tool_calls)
	ToolCalls []ToolCall `json:"tool_calls,omitempty,omitzero"`
}

// GenerateRequest defines model for GenerateRequest.
type GenerateRequest struct {
	// MaxTokens Maximum tokens to generate
	MaxTokens int `json:"max_tokens,omitempty,omitzero"`

	// Messages Conversation messages (OpenAI-compatible format)
	Messages []ChatMessage `json:"messages"`

	// Model Name of the generator model from models_dir/generators/
	Model string `json:"model"`

	// Stream If true, partial message deltas will be sent as SSE events
	Stream bool `json:"stream,omitempty,omitzero"`

	// Temperature Sampling temperature (0.0 = deterministic, higher = more random)
	Temperature float32 `json:"temperature,omitempty,omitzero"`

	// ToolChoice Controls how the model uses tools. Options:
	// - "auto": Model decides whether to call a tool (default)
	// - "none": Model will not call any tools
	// - "required": Model must call at least one tool
	// - object: Force a specific function to be called
	ToolChoice ToolChoice `json:"tool_choice,omitempty,omitzero"`

	// Tools List of tools (functions) the model can call.
	// Only supported by models with tool_call_format configured.
	Tools []Tool `json:"tools,omitempty,omitzero"`

	// TopK Top-k sampling (Termite extension, not in OpenAI API)
	TopK int `json:"top_k,omitempty,omitzero"`

	// TopP Nucleus sampling probability
	TopP float32 `json:"top_p,omitempty,omitzero"`
}

// GenerateResponse OpenAI-compatible chat completion response
type GenerateResponse struct {
	// Choices List of completion choices (currently always 1)
	Choices []GenerateChoice `json:"choices"`

	// Created Unix timestamp (seconds) when the completion was created
	Created int `json:"created"`

	// Id A unique identifier for the chat completion
	Id string `json:"id"`

	// Model Model used for generation
	Model string `json:"model"`

	// Object The object type, always "chat.completion"
	Object GenerateResponseObject `json:"object"`
	Usage  GenerateUsage          `json:"usage"`
}

// GenerateResponseObject The object type, always "chat.completion"
type GenerateResponseObject string

// GenerateUsage defines model for GenerateUsage.
type GenerateUsage struct {
	// CompletionTokens Number of tokens in the completion
	CompletionTokens int `json:"completion_tokens"`

	// PromptTokens Number of tokens in the prompt
	PromptTokens int `json:"prompt_tokens"`

	// TotalTokens Total tokens used (prompt + completion)
	TotalTokens int `json:"total_tokens"`
}

// ImageURL Image URL or data URI
type ImageURL struct {
	// Url URL or data URI (data:image/png;base64,...)
	Url string `json:"url"`
}

// ImageURLContentPart Image content for embedding (OpenAI-compatible format)
type ImageURLContentPart struct {
	// ImageUrl Image URL or data URI
	ImageUrl ImageURL                `json:"image_url"`
	Type     ImageURLContentPartType `json:"type"`
}

// ImageURLContentPartType defines model for ImageURLContentPart.Type.
type ImageURLContentPartType string

// MediaContentPart Inline binary media content (audio, image, etc.)
type MediaContentPart struct {
	// Data Base64-encoded binary data
	Data []byte `json:"data"`

	// MimeType MIME type (audio/wav, image/gif, image/png, etc.)
	MimeType string               `json:"mime_type"`
	Type     MediaContentPartType `json:"type"`
}

// MediaContentPartType defines model for MediaContentPart.Type.
type MediaContentPartType string

// ModelsResponse defines model for ModelsResponse.
type ModelsResponse struct {
	// Chunkers Available chunking models (always includes "fixed")
	Chunkers []string `json:"chunkers"`

	// Classifiers Available zero-shot classification models
	Classifiers []string `json:"classifiers"`

	// Embedders Available embedding models from models_dir/embedders/
	Embedders []string `json:"embedders"`

	// Extractors Available GLiNER extractor models (zero-shot recognition with custom labels)
	Extractors []string `json:"extractors,omitempty,omitzero"`

	// Generators Available generator/LLM models from models_dir/generators/
	Generators []string `json:"generators"`

	// Readers Available reader/OCR models from models_dir/readers/
	Readers []string `json:"readers"`

	// RecognizerInfo Detailed information about recognizer models including capabilities.
	// Map of model name to model info. Use this to determine what capabilities
	// each recognizer supports (labels, zeroshot, relations, answers).
	RecognizerInfo map[string]RecognizerModelInfo `json:"recognizer_info,omitempty,omitzero"`

	// Recognizers Available recognizer models from models_dir/recognizers/
	Recognizers []string `json:"recognizers"`

	// Rerankers Available reranking models
	Rerankers []string `json:"rerankers"`

	// Rewriters Available Seq2Seq rewriter models from models_dir/rewriters/
	Rewriters []string `json:"rewriters"`

	// Transcribers Available transcriber/speech-to-text models from models_dir/transcribers/
	Transcribers []string `json:"transcribers"`
}

// ReadRequest defines model for ReadRequest.
type ReadRequest struct {
	// Images Images to read text from. Supports:
	// - Data URIs: `data:image/png;base64,...`
	// - URLs (if content_security allows)
	Images []ImageURL `json:"images"`

	// MaxTokens Maximum tokens to generate
	MaxTokens int `json:"max_tokens,omitempty,omitzero"`

	// Model Name of reader model from models_dir/readers/
	Model string `json:"model"`

	// Prompt Optional task prompt for document understanding models.
	// - TrOCR: Not used (pure OCR)
	// - Donut CORD: "<s_cord-v2>" for receipt parsing
	// - Donut DocVQA: "<s_docvqa><s_question>What is the total?</s_question><s_answer>"
	// - Florence-2: "<OCR>" for OCR, "<CAPTION>" for captioning
	Prompt string `json:"prompt,omitempty,omitzero"`
}

// ReadResponse defines model for ReadResponse.
type ReadResponse struct {
	// Model Name of model used for reading
	Model string `json:"model"`

	// Results Array of read results (one per input image)
	Results []ReadResult `json:"results"`
}

// ReadResult defines model for ReadResult.
type ReadResult struct {
	// Fields Structured fields extracted by document understanding models (Donut, Florence-2).
	// Fields are flattened with dot notation for nested structures.
	// Only present for models that output structured data.
	Fields map[string]string `json:"fields,omitempty,omitzero"`

	// Regions Individual text regions with bounding boxes and recognized text.
	// Populated by multi-stage OCR models (Surya, PaddleOCR).
	Regions []TextRegion `json:"regions,omitempty,omitzero"`

	// Text Extracted text from the image
	Text string `json:"text"`
}

// RecognizeEntity defines model for RecognizeEntity.
type RecognizeEntity struct {
	// End Character offset where entity ends (exclusive)
	End int `json:"end"`

	// Label Entity type (PER, ORG, LOC, MISC)
	Label string `json:"label"`

	// Score Confidence score (0.0 to 1.0)
	Score float32 `json:"score"`

	// Start Character offset where entity begins
	Start int `json:"start"`

	// Text The entity text
	Text string `json:"text"`
}

// RecognizeRequest defines model for RecognizeRequest.
type RecognizeRequest struct {
	// Labels Custom entity labels to extract (GLiNER models only).
	// When using a GLiNER model, you can specify any entity types to extract,
	// enabling zero-shot NER without model retraining.
	// If not provided, the model's default labels are used.
	Labels []string `json:"labels,omitempty,omitzero"`

	// Model Name of recognizer model from models_dir/recognizers/
	Model string `json:"model"`

	// RelationLabels Relation types to extract (for models with 'relations' capability).
	// Only used when the model supports relation extraction (GLiNER multitask, REBEL).
	// If not provided, the model extracts all relations it can detect.
	RelationLabels []string `json:"relation_labels,omitempty,omitzero"`

	// Texts Texts to extract entities from
	Texts []string `json:"texts"`
}

// RecognizeResponse defines model for RecognizeResponse.
type RecognizeResponse struct {
	// Entities Array of entity arrays (one per input text)
	Entities [][]RecognizeEntity `json:"entities"`

	// Model Name of model used for NER
	Model string `json:"model"`

	// Relations Array of relation arrays (one per input text).
	// Only present when using a model with 'relations' capability (GLiNER multitask, REBEL).
	Relations [][]Relation `json:"relations,omitempty,omitzero"`
}

// RecognizerCapability Capability that a recognizer model supports:
// - labels: Entity extraction (NER) - extracts labeled spans like PER, ORG, LOC
// - zeroshot: Supports arbitrary labels at inference time (GLiNER models)
// - relations: Relation extraction between entities (GLiNER multitask, REBEL)
// - answers: Extractive question answering (GLiNER multitask)
type RecognizerCapability string

// RecognizerModelInfo Detailed information about a recognizer model
type RecognizerModelInfo struct {
	// Capabilities List of capabilities this recognizer model supports
	Capabilities []RecognizerCapability `json:"capabilities,omitempty,omitzero"`
}

// Relation defines model for Relation.
type Relation struct {
	Head RecognizeEntity `json:"head"`

	// Label The relationship type
	Label string `json:"label"`

	// Score Confidence score for the relation (0.0 to 1.0)
	Score float32         `json:"score"`
	Tail  RecognizeEntity `json:"tail"`
}

// RerankRequest defines model for RerankRequest.
type RerankRequest struct {
	// Model Name of reranking model from models_dir/rerankers/
	Model string `json:"model"`

	// Prompts Pre-rendered document texts to rerank. The client is responsible for extracting
	// and rendering document fields/templates before calling this endpoint.
	Prompts []string `json:"prompts"`

	// Query Search query for relevance scoring
	Query string `json:"query"`
}

// RerankResponse defines model for RerankResponse.
type RerankResponse struct {
	// Model Name of model used for reranking
	Model string `json:"model"`

	// Scores Relevance scores (one per prompt, same order as input)
	Scores []float32 `json:"scores"`
}

// RewriteRequest defines model for RewriteRequest.
type RewriteRequest struct {
	// Inputs Input texts to rewrite/transform
	Inputs []string `json:"inputs"`

	// Model Name of Seq2Seq rewriter model from models_dir/rewriters/
	Model string `json:"model"`
}

// RewriteResponse defines model for RewriteResponse.
type RewriteResponse struct {
	// Model Name of model used for rewriting
	Model string `json:"model"`

	// Texts Rewritten texts (array of arrays, one per input, multiple per beam)
	Texts [][]string `json:"texts"`
}

// Role The role of a message sender in a conversation
type Role string

// TextContentPart Text content for embedding
type TextContentPart struct {
	// Text Text content to embed
	Text string              `json:"text"`
	Type TextContentPartType `json:"type"`
}

// TextContentPartType defines model for TextContentPart.Type.
type TextContentPartType string

// TextRegion defines model for TextRegion.
type TextRegion struct {
	// Bbox Bounding box [x1, y1, x2, y2] in pixel coordinates
	Bbox []float32 `json:"bbox"`

	// Confidence Recognition confidence score (0-1)
	Confidence float32 `json:"confidence,omitempty,omitzero"`

	// Label Semantic label from layout analysis (e.g., text, title, table)
	Label string `json:"label,omitempty,omitzero"`

	// Text Recognized text within the region
	Text string `json:"text"`
}

// Tool A tool (function) that the model can call
type Tool struct {
	// Function Definition of a function that can be called by the model
	Function FunctionDefinition `json:"function"`

	// Type The type of tool (currently only "function" is supported)
	Type ToolType `json:"type"`
}

// ToolType The type of tool (currently only "function" is supported)
type ToolType string

// ToolCall A tool call made by the model
type ToolCall struct {
	// Function The function called by the model
	Function ToolCallFunction `json:"function"`

	// Id Unique identifier for this tool call
	Id string `json:"id"`

	// Type The type of tool call (currently only "function")
	Type ToolCallType `json:"type"`
}

// ToolCallType The type of tool call (currently only "function")
type ToolCallType string

// ToolCallDelta Incremental tool call data for streaming
type ToolCallDelta struct {
	// Function Incremental function call data for streaming
	Function ToolCallFunctionDelta `json:"function,omitempty,omitzero"`

	// Id Unique identifier (only in first delta for this index)
	Id string `json:"id,omitempty,omitzero"`

	// Index Index of the tool call in the array
	Index int `json:"index,omitempty,omitzero"`

	// Type The type of tool call (only in first delta)
	Type ToolCallDeltaType `json:"type,omitempty,omitzero"`
}

// ToolCallDeltaType The type of tool call (only in first delta)
type ToolCallDeltaType string

// ToolCallFunction The function called by the model
type ToolCallFunction struct {
	// Arguments JSON string of the arguments to the function
	Arguments string `json:"arguments"`

	// Name The name of the function called
	Name string `json:"name"`
}

// ToolCallFunctionDelta Incremental function call data for streaming
type ToolCallFunctionDelta struct {
	// Arguments Incremental arguments JSON string
	Arguments string `json:"arguments,omitempty,omitzero"`

	// Name Function name (only in first delta)
	Name string `json:"name,omitempty,omitzero"`
}

// ToolChoice Controls how the model uses tools. Options:
// - "auto": Model decides whether to call a tool (default)
// - "none": Model will not call any tools
// - "required": Model must call at least one tool
// - object: Force a specific function to be called
type ToolChoice struct {
	union json.RawMessage
}

// ToolChoice0 defines model for ToolChoice.0.
type ToolChoice0 string

// ToolChoice1 Force a specific function to be called
type ToolChoice1 struct {
	Function struct {
		// Name The name of the function to call
		Name string `json:"name"`
	} `json:"function"`
	Type ToolChoice1Type `json:"type"`
}

// ToolChoice1Type defines model for ToolChoice.1.Type.
type ToolChoice1Type string

// TranscribeRequest defines model for TranscribeRequest.
type TranscribeRequest struct {
	// Audio Base64-encoded audio data (WAV, MP3, FLAC, etc.)
	Audio []byte `json:"audio"`

	// Language Force specific language for transcription (optional, model-dependent)
	Language string `json:"language,omitempty,omitzero"`

	// Model Name of transcriber model from models_dir/transcribers/
	Model string `json:"model,omitempty,omitzero"`
}

// TranscribeResponse defines model for TranscribeResponse.
type TranscribeResponse struct {
	// Language Detected or forced language
	Language string `json:"language,omitempty,omitzero"`

	// Model Name of model used for transcription
	Model string `json:"model"`

	// Text Transcribed text from the audio
	Text string `json:"text"`
}

// VersionResponse defines model for VersionResponse.
type VersionResponse struct {
	// BuildTime Build timestamp
	BuildTime string `json:"build_time"`

	// GitCommit Git commit hash
	GitCommit string `json:"git_commit"`

	// GoVersion Go runtime version
	GoVersion string `json:"go_version"`

	// Version Termite version
	Version string `json:"version"`
}

// ChunkTextJSONRequestBody defines body for ChunkText for application/json ContentType.
type ChunkTextJSONRequestBody = ChunkRequest

// ClassifyTextJSONRequestBody defines body for ClassifyText for application/json ContentType.
type ClassifyTextJSONRequestBody = ClassifyRequest

// GenerateEmbeddingsJSONRequestBody defines body for GenerateEmbeddings for application/json ContentType.
type GenerateEmbeddingsJSONRequestBody = EmbedRequest

// GenerateContentJSONRequestBody defines body for GenerateContent for application/json ContentType.
type GenerateContentJSONRequestBody = GenerateRequest

// ReadImagesJSONRequestBody defines body for ReadImages for application/json ContentType.
type ReadImagesJSONRequestBody = ReadRequest

// RecognizeEntitiesJSONRequestBody defines body for RecognizeEntities for application/json ContentType.
type RecognizeEntitiesJSONRequestBody = RecognizeRequest

// RerankPromptsJSONRequestBody defines body for RerankPrompts for application/json ContentType.
type RerankPromptsJSONRequestBody = RerankRequest

// RewriteTextJSONRequestBody defines body for RewriteText for application/json ContentType.
type RewriteTextJSONRequestBody = RewriteRequest

// TranscribeAudioJSONRequestBody defines body for TranscribeAudio for application/json ContentType.
type TranscribeAudioJSONRequestBody = TranscribeRequest

// AsChatMessageContent0 returns the union data inside the ChatMessageContent as a ChatMessageContent0
func (t ChatMessageContent) AsChatMessageContent0() (ChatMessageContent0, error) {
	var body ChatMessageContent0
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromChatMessageContent0 overwrites any union data inside the ChatMessageContent as the provided ChatMessageContent0
func (t *ChatMessageContent) FromChatMessageContent0(v ChatMessageContent0) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeChatMessageContent0 performs a merge with any union data inside the ChatMessageContent, using the provided ChatMessageContent0
func (t *ChatMessageContent) MergeChatMessageContent0(v ChatMessageContent0) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsChatMessageContent1 returns the union data inside the ChatMessageContent as a ChatMessageContent1
func (t ChatMessageContent) AsChatMessageContent1() (ChatMessageContent1, error) {
	var body ChatMessageContent1
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromChatMessageContent1 overwrites any union data inside the ChatMessageContent as the provided ChatMessageContent1
func (t *ChatMessageContent) FromChatMessageContent1(v ChatMessageContent1) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeChatMessageContent1 performs a merge with any union data inside the ChatMessageContent, using the provided ChatMessageContent1
func (t *ChatMessageContent) MergeChatMessageContent1(v ChatMessageContent1) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t ChatMessageContent) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *ChatMessageContent) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}

// AsChunkRequestInput0 returns the union data inside the ChunkRequest_Input as a ChunkRequestInput0
func (t ChunkRequest_Input) AsChunkRequestInput0() (ChunkRequestInput0, error) {
	var body ChunkRequestInput0
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromChunkRequestInput0 overwrites any union data inside the ChunkRequest_Input as the provided ChunkRequestInput0
func (t *ChunkRequest_Input) FromChunkRequestInput0(v ChunkRequestInput0) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeChunkRequestInput0 performs a merge with any union data inside the ChunkRequest_Input, using the provided ChunkRequestInput0
func (t *ChunkRequest_Input) MergeChunkRequestInput0(v ChunkRequestInput0) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsContentPart returns the union data inside the ChunkRequest_Input as a ContentPart
func (t ChunkRequest_Input) AsContentPart() (ContentPart, error) {
	var body ContentPart
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromContentPart overwrites any union data inside the ChunkRequest_Input as the provided ContentPart
func (t *ChunkRequest_Input) FromContentPart(v ContentPart) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeContentPart performs a merge with any union data inside the ChunkRequest_Input, using the provided ContentPart
func (t *ChunkRequest_Input) MergeContentPart(v ContentPart) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t ChunkRequest_Input) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *ChunkRequest_Input) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}

// AsTextContentPart returns the union data inside the ContentPart as a TextContentPart
func (t ContentPart) AsTextContentPart() (TextContentPart, error) {
	var body TextContentPart
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromTextContentPart overwrites any union data inside the ContentPart as the provided TextContentPart
func (t *ContentPart) FromTextContentPart(v TextContentPart) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeTextContentPart performs a merge with any union data inside the ContentPart, using the provided TextContentPart
func (t *ContentPart) MergeTextContentPart(v TextContentPart) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsImageURLContentPart returns the union data inside the ContentPart as a ImageURLContentPart
func (t ContentPart) AsImageURLContentPart() (ImageURLContentPart, error) {
	var body ImageURLContentPart
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromImageURLContentPart overwrites any union data inside the ContentPart as the provided ImageURLContentPart
func (t *ContentPart) FromImageURLContentPart(v ImageURLContentPart) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeImageURLContentPart performs a merge with any union data inside the ContentPart, using the provided ImageURLContentPart
func (t *ContentPart) MergeImageURLContentPart(v ImageURLContentPart) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsMediaContentPart returns the union data inside the ContentPart as a MediaContentPart
func (t ContentPart) AsMediaContentPart() (MediaContentPart, error) {
	var body MediaContentPart
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromMediaContentPart overwrites any union data inside the ContentPart as the provided MediaContentPart
func (t *ContentPart) FromMediaContentPart(v MediaContentPart) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeMediaContentPart performs a merge with any union data inside the ContentPart, using the provided MediaContentPart
func (t *ContentPart) MergeMediaContentPart(v MediaContentPart) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t ContentPart) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *ContentPart) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}

// AsEmbedRequestInput0 returns the union data inside the EmbedRequest_Input as a EmbedRequestInput0
func (t EmbedRequest_Input) AsEmbedRequestInput0() (EmbedRequestInput0, error) {
	var body EmbedRequestInput0
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromEmbedRequestInput0 overwrites any union data inside the EmbedRequest_Input as the provided EmbedRequestInput0
func (t *EmbedRequest_Input) FromEmbedRequestInput0(v EmbedRequestInput0) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeEmbedRequestInput0 performs a merge with any union data inside the EmbedRequest_Input, using the provided EmbedRequestInput0
func (t *EmbedRequest_Input) MergeEmbedRequestInput0(v EmbedRequestInput0) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsEmbedRequestInput1 returns the union data inside the EmbedRequest_Input as a EmbedRequestInput1
func (t EmbedRequest_Input) AsEmbedRequestInput1() (EmbedRequestInput1, error) {
	var body EmbedRequestInput1
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromEmbedRequestInput1 overwrites any union data inside the EmbedRequest_Input as the provided EmbedRequestInput1
func (t *EmbedRequest_Input) FromEmbedRequestInput1(v EmbedRequestInput1) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeEmbedRequestInput1 performs a merge with any union data inside the EmbedRequest_Input, using the provided EmbedRequestInput1
func (t *EmbedRequest_Input) MergeEmbedRequestInput1(v EmbedRequestInput1) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsEmbedRequestInput2 returns the union data inside the EmbedRequest_Input as a EmbedRequestInput2
func (t EmbedRequest_Input) AsEmbedRequestInput2() (EmbedRequestInput2, error) {
	var body EmbedRequestInput2
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromEmbedRequestInput2 overwrites any union data inside the EmbedRequest_Input as the provided EmbedRequestInput2
func (t *EmbedRequest_Input) FromEmbedRequestInput2(v EmbedRequestInput2) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeEmbedRequestInput2 performs a merge with any union data inside the EmbedRequest_Input, using the provided EmbedRequestInput2
func (t *EmbedRequest_Input) MergeEmbedRequestInput2(v EmbedRequestInput2) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t EmbedRequest_Input) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *EmbedRequest_Input) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}

// AsToolChoice0 returns the union data inside the ToolChoice as a ToolChoice0
func (t ToolChoice) AsToolChoice0() (ToolChoice0, error) {
	var body ToolChoice0
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromToolChoice0 overwrites any union data inside the ToolChoice as the provided ToolChoice0
func (t *ToolChoice) FromToolChoice0(v ToolChoice0) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeToolChoice0 performs a merge with any union data inside the ToolChoice, using the provided ToolChoice0
func (t *ToolChoice) MergeToolChoice0(v ToolChoice0) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsToolChoice1 returns the union data inside the ToolChoice as a ToolChoice1
func (t ToolChoice) AsToolChoice1() (ToolChoice1, error) {
	var body ToolChoice1
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromToolChoice1 overwrites any union data inside the ToolChoice as the provided ToolChoice1
func (t *ToolChoice) FromToolChoice1(v ToolChoice1) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeToolChoice1 performs a merge with any union data inside the ToolChoice, using the provided ToolChoice1
func (t *ToolChoice) MergeToolChoice1(v ToolChoice1) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t ToolChoice) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *ToolChoice) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Chunk text into smaller segments
	// (POST /chunk)
	ChunkText(w http.ResponseWriter, r *http.Request)
	// Zero-shot text classification
	// (POST /classify)
	ClassifyText(w http.ResponseWriter, r *http.Request)
	// Generate embeddings
	// (POST /embed)
	GenerateEmbeddings(w http.ResponseWriter, r *http.Request)
	// Generate text using LLM (OpenAI-compatible)
	// (POST /generate)
	GenerateContent(w http.ResponseWriter, r *http.Request)
	// List available models
	// (GET /models)
	ListModels(w http.ResponseWriter, r *http.Request)
	// Read text from images (OCR/document understanding)
	// (POST /read)
	ReadImages(w http.ResponseWriter, r *http.Request)
	// Recognize named entities
	// (POST /recognize)
	RecognizeEntities(w http.ResponseWriter, r *http.Request)
	// Rerank prompts by relevance
	// (POST /rerank)
	RerankPrompts(w http.ResponseWriter, r *http.Request)
	// Rewrite text using Seq2Seq models
	// (POST /rewrite)
	RewriteText(w http.ResponseWriter, r *http.Request)
	// Transcribe audio to text (speech-to-text)
	// (POST /transcribe)
	TranscribeAudio(w http.ResponseWriter, r *http.Request)
	// Get version information
	// (GET /version)
	GetVersion(w http.ResponseWriter, r *http.Request)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// ChunkText operation middleware
func (siw *ServerInterfaceWrapper) ChunkText(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ChunkText(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ClassifyText operation middleware
func (siw *ServerInterfaceWrapper) ClassifyText(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ClassifyText(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GenerateEmbeddings operation middleware
func (siw *ServerInterfaceWrapper) GenerateEmbeddings(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GenerateEmbeddings(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GenerateContent operation middleware
func (siw *ServerInterfaceWrapper) GenerateContent(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GenerateContent(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListModels operation middleware
func (siw *ServerInterfaceWrapper) ListModels(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListModels(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ReadImages operation middleware
func (siw *ServerInterfaceWrapper) ReadImages(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ReadImages(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// RecognizeEntities operation middleware
func (siw *ServerInterfaceWrapper) RecognizeEntities(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.RecognizeEntities(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// RerankPrompts operation middleware
func (siw *ServerInterfaceWrapper) RerankPrompts(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.RerankPrompts(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// RewriteText operation middleware
func (siw *ServerInterfaceWrapper) RewriteText(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.RewriteText(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// TranscribeAudio operation middleware
func (siw *ServerInterfaceWrapper) TranscribeAudio(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.TranscribeAudio(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetVersion operation middleware
func (siw *ServerInterfaceWrapper) GetVersion(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetVersion(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{})
}

// ServeMux is an abstraction of http.ServeMux.
type ServeMux interface {
	HandleFunc(pattern string, handler func(http.ResponseWriter, *http.Request))
	ServeHTTP(w http.ResponseWriter, r *http.Request)
}

type StdHTTPServerOptions struct {
	BaseURL          string
	BaseRouter       ServeMux
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, m ServeMux) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseRouter: m,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, m ServeMux, baseURL string) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseURL:    baseURL,
		BaseRouter: m,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options StdHTTPServerOptions) http.Handler {
	m := options.BaseRouter

	if m == nil {
		m = http.NewServeMux()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	m.HandleFunc("POST "+options.BaseURL+"/chunk", wrapper.ChunkText)
	m.HandleFunc("POST "+options.BaseURL+"/classify", wrapper.ClassifyText)
	m.HandleFunc("POST "+options.BaseURL+"/embed", wrapper.GenerateEmbeddings)
	m.HandleFunc("POST "+options.BaseURL+"/generate", wrapper.GenerateContent)
	m.HandleFunc("GET "+options.BaseURL+"/models", wrapper.ListModels)
	m.HandleFunc("POST "+options.BaseURL+"/read", wrapper.ReadImages)
	m.HandleFunc("POST "+options.BaseURL+"/recognize", wrapper.RecognizeEntities)
	m.HandleFunc("POST "+options.BaseURL+"/rerank", wrapper.RerankPrompts)
	m.HandleFunc("POST "+options.BaseURL+"/rewrite", wrapper.RewriteText)
	m.HandleFunc("POST "+options.BaseURL+"/transcribe", wrapper.TranscribeAudio)
	m.HandleFunc("GET "+options.BaseURL+"/version", wrapper.GetVersion)

	return m
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+y9a1McOZYA+ld0azbC0JP1AOyebm5MbGCMPewCZgC3Z7fLAapMVZWGTCktKYFqh+9v",
	"v6FzJOW7KPzo2djt6A9tsvQ8OjovncenQSyzXAomjB7sfxroeMkyCv88XFJzyrSmC2b/zJXMmTKcwY+x",
	"FIYJY//5b4rNB/uDP43LkcZumHFljEPX43M0UDJlj/W8sG0+RwMjZXod0zS95ontkzAdK54bLsVgf3D8",
	"isg5MUtGbDti2xGz5JpkOCnhmiimcykSLhbESLIlRboic6mIXcVfbbftQTQwq5wN9gfaKC4WtXl1e9Yr",
	"P5cmGU0Yma1gCVRrrg0VpjlJ+MHOxA3L9GO7tzMc0jSFleDSqFJ0Nfhswcc+FlyxZLD/K4LyQ2gkZ/9k",
	"McC4A/KtfbjfiTvMEbks8lwqo4m5l3b5GTV6fyqG5JJnecoIgmefTAd/Y2kqI7KU94QqRlay+PfpwLY8",
	"sMu0h+IGJTm1A269zZk4OCZZkRqeyYSmbvztffLrpymsfzqwIxv2YKaDKPwrzDYdfP4wFYNoIAV7Ox/s",
	"/9rcjluk7eZn7zjZZq8nL3jTM3RgP6fKtI/xAxxRIW7tKDRN3YbKra0bmQozT1fDhbxO+YzOr2M7EBeL",
	"a5kzQXN+fcUeTHnfvnKwl1xQtQrDfbAD1olB1828ZB8LJmJGRJHNmPLXFEYnW5OI7ERkNyKj0ahy/bgw",
	"bMHUIBo8DBdy6L4WXJi9XQvDjGfsGr+2cPn49IjYn/YBAcZ5SrmICC0SLsf39C4iPKMLNs7FIiLMxKM2",
	"ajSuFk8G1Rnbl+xD1EQlt70SmUbkCrDRftZkSe8YCSNW1jkaeHQ4lGLOF+3t4fdCUfs3UBZ/TsSumWl7",
	"aSW5YirjhpGD8+PRVFxZSsg1oUTbq8HnnCV2ZXO+gCHsgfzt6urcNidDkvD5nClN5kpm8Nu8SFMCy2IK",
	"FzAV90seLwkXcVokTJNcyTueMEU0S1kMi6MiITGNl3ZtcXXZI7i9ddTJ6ANinCOzc1qkZrD/YtKE7Sl9",
	"4FmRVdDJAdVIopgplB2bPVBLArB/A6cs+siEpbV5BnP+wOw5Nwi8x1S7B+hlpyk0G5EjbpZMkWfQ8RmA",
	"UTu6I2+ZGM6otkB2nSMiFaFuCEEzhsCFv/U4RtDq8Sf70+fxqLqFsLQWa5J3TKU0v04cXK+zOvBasHuL",
	"HYjvQLggmSYzZu4ZE3hHPDi33DD7ZNJxMSuzw3YfO7WzcFquW45s2HYN87vzf/T4NMupokaq+hFOBeBV",
	"4wTttQsd4JgAnuFkaqB2Q7SFAKoWzHRvtbXXK2hcpXe4zZy5y1rfYecWzVIxvZRpUj/Q0Yuoix4kQGBD",
	"H9jl27Ozfzj8IluT0WS4M4KDDDPDYMjKLJKlkla4JC7eruSei0Te9+LY3mTShsB76NNEM7uqCopZBCiR",
	"DMbpQrTPnTJNIW4vkNx1iqSOdK6XSEsq+zkacJEXHZLRsf0cJALjlr5GQEJ8c+LRzXRQkt5UigVJZFxk",
	"lh+MRtPBDdma0fj2nipLjbOcGj5L2bYdpiIz7JObmlyUsYRTFIwSaih+nBaTyV5sac6Pz+HfDFsEJoPN",
	"AhecDj7fPDJPl/wFy7Y910hfAAEPqe4ddkpjG4tQVmSyS8LTyhWLqbGc2qiCNTHx1dH5xdHhwdXRq33y",
	"TjPyDM75GeFCG0YTx5bDudaIQc/REbOkhgjGEuA5M0Z0nnJDuDCS6Iymqb/nejTqli76ENrqJxpkmrCK",
	"TwPLQtn1kpvB/pymmkUDzyd//TRgIrmOl1QN9nfsNbQC2CQaaEOVcd8nHlhhP8DRudJOHLGLtPCvDPWz",
	"G2qnPtTP3WNpFkuRVAb7EDis412fm9y+sqcm+rxfMmCsiukiNeSeaqKZumMJckzoWQJ1JmXKqLAzVKWH",
	"TrnelBLYxqI7kOuW0F6TIGrUuC4r0NgUNE1XVmJIyFZGV062wr04gY0lhM/JnKapvStExnGhFEu2NxEC",
	"GqJq2B2uL6oAulM3TK1GOl/1ktLlKpdmyTTX14ZleUpNh8R9WGgjM1K2Jb4tkPyzk2MvDOF0PPZSoL2R",
	"08Gnz9MBoZrkKY2Z5V9MBak0pTOWjqbilecTjqI6wFgU/PR5ZDXO9tWF82YPuWJaM3uNP30mmgnDgQB3",
	"sXmYrQOFDqlIeGI3hC1geb8xJYd6KU17X1ZsRAy452lKcsUSHhuCIjMMsaW3yYxpQ3CiGSOMxktY8qi+",
	"l18HudTc8DuL9YItaPhnYRRN7bkGVG7LLZuh7ZkVSK0k7TbClFt+RUi9Trgalw30uAbwU6m4+e2EFoqp",
	"cfaKvTy6uKLDuz04+WEmUj58ECnvAjoo1tcAlZpk4Yhdgx/PCZB5QtNU3mvUyi0iuIOxMhac+xYXCcuZ",
	"SCzF1rG0s22PpuIYbppmQfTYjuBniyCKEWFZecp/YwmhsZJau4FHVbmwQnTsXF2GIfsZ2Iq7YfUTPSap",
	"vGNooMqVTIrY/D+DCLQNS+t4zIDuGaaU5ZejpxxygyJ4QoALDSi+nhqUfKhBtmuIvo7W1ls6Yq7JlhQM",
	"zgjYMJyUPZQji/uO4FuGKwj1A1UWZX/VUll6OVvhocH1YWDTwxMKUNqMvNcG77owT7xAeGuA2oNqXoPC",
	"o9Q7EO0GmB85LLgtzaOq3KemQuvIkSfIYys+LaSq4WiV6LQQDkDfY5pAVQQPx6od9hK0NY+fN1A9GsDB",
	"DfnJO0ES5P46KGjOrwvVAYx3FyfeHOXtJSybscSi0zjoKO5G1qCzNCbfH49TGdN0KbXZ/2ny02RQ2VOh",
	"OmmdZfBWzsoVtwRzVSN4vw6kEA+DaPCQ0kE0WMhBy7D0EvsT359I5bklol4qKRi477lZEgndaEoSBjRF",
	"5yxG4j2aitew1H1y49Z0Q6QKf+xjjxtyv2Rwy6C/WykQthtaGHkzsgqzh51RnGnCBP6fC7c4KhJ7I6py",
	"J72jPKWzlBE3359xhqmIZTbjAokGyNk6KFqep8KcP/zgQKF/+MGSckvpiRRkVvA0IYYu9DaoYzcLeUOG",
	"5LxQjLyRhIs5U4ChWzS9pytdLiUih+fviBTpKiI6lfdMG9DEbuyh2DFAob4oQH4gWw41NRnayf46hbOL",
	"3l5cWZVpTrUJ/R9Saru/kacn/yD/ODno6PuQ0ugfJwe269X5u/Hhu1cH48Pzd9u401cAG/3DD7gjADwZ",
	"koPCyGHCDIsNihIlVANvgw5xkcAKzn45fnV8QOzo5M35O/xNKpalMFxu2eihVOz0xIqq8dtLBw0gZ7MV",
	"AABHNHmBW5KLlNklky3f6B8nB25WbPNaqpgF0OKGjvAehR39itBDZfMhdcrtQk4HH+wQV2rl8UQjYlsQ",
	"lEhp0N5YHWrf7jmMt2/yAv/A3/xfYYZzxaxQ/ub8XQRyOExnsfzQgSkMC+Bq9EZYwcIc+Ggcs5Sh8aMp",
	"zYXl4UW3awNlGhfmPuK/kAJsLt05M8W1ZnHhqctTLP46VjSvWvyd2n3pxiutJbeM5dc0tfyhZoJ7kbUM",
	"cH+T96g/G0lsN2+TspTKaj6CZCyTakXo3DBFUqqNxTiy9TZNaUaHFbPBaCpOsbMV1SwSZNTwGDUs4QbE",
	"YUC0CvYnOSdc0NjwO25WTu94I8vf544WTgcvsumAbL0gGReFYXrbHvTO0n7bIUtZKPgwsX8zurDLRXq7",
	"XaooQB39QCn9bRXakJTfMoLbGpFLZrClHc1Iq6ikPOYmXREm4BbXZpgKJMUWO7MSCH7ThoCiXuRAbgW7",
	"YyqApKFQ4CG1dR+5eCq+pHKxaKCLww+w5ksBiqww1/5lYr11usOyH4aoUO7wzAEqAGzvIEm4Y3XhV9C8",
	"Zox8LFjBElLkFsh2XfDhWvPf2Ggq3ClMgIUWIuWWkyUlAW3A7nnnawJ9uEZIX+PJPHWb7jz9BWndDM2t",
	"mkMFk4VOLf6+XzKBKA4Lxsdtq+knEWrNzN4ixWImjLc+oHzAdXlTtk4u3hFLRO3CtjcBBnkrLHrO55bi",
	"3jErHQhS0gI7upBiaDXjBuD2+gCHW7zOZpsBzUFkiwty+nLbPcbAet2mEJbdMKJ5rqQDUy+I8F5V7s7j",
	"UAmGQkFocse1XSFOOnQmILfuqSjgnR3lFW0FFjwWi40arm5GV2A+kYoqboH9EDOW4EbuaFpYpH0v1a1F",
	"fykWmieMtBDQPXMINlwoygU+9hkl0yY6T37+se9gymvyVHSuvkPCKIgnPTShgrzlqblra3+bF2kaEcHu",
	"y3HtqVl0ezHZI5dOX34nSvEHWPEFM2o1PABusGQ0Yar/LHGyR/C8b/1obieTBmx3Jv1Pj9faKKt0eQUl",
	"kK/zmuLCRJFZkQEYAejuv1klbSYLkbCkogOVVLx+NudMDet6gZt4Bc9wiidMj8gpzXXlZRLOzSwZV61e",
	"JQMW0pJk52JDc7iF9tgcCMt50PInq2QChL7jeeULgnASTsDxz+19UmWgZMv+w46VsIyKJHK31LF8nri3",
	"k9rQfwUGu19npm6kkmtGNZYJcjdgon+xXVJdbmmKBzIdVCGAmwIy0+bJW1SDN4m9Hblibg7fvs6tI8Lu",
	"mGiS1gChnAtRZQ6wViBA3iLGH+wOcb+WogAIHV3geLk0zRjJZYsefBq8PDg4Hs8WbAgPGUMmhnc7oxeD",
	"/YCDGVdmOY6XUtyuhpm98sa1BVNcysWioOlwZ7CP6Nr12lEaFNs6+UuqGUm4YrGxZNTSLcpFaVLXxcz/",
	"yi3yeuWTgjbEdWwRW/v9zpXMUMf4VE76eYxaPlN6bOX3I6/zh+fSUtOpdQvP9LZX3dTf30kxRcteF/DX",
	"Rt1iuRD8t7Ij/A3i6qNd7xU3vuMl+7h7yT4S/7XZuy64/n/jkUGIjn07zQy545Tc8Zyp7ZG9Xvb2a2Yi",
	"0OlA5zZDLhoP68ARPU1uyqCtebpEUouhG3Cgs/XyYs5zlnLB0DiMJgQCFkf/C9xYPRWUxDJfeZMQtIyI",
	"lmTJF0umkP1qIHWZVMzLIrPC4N2Dr1NRWYTnEUHan3iJpUortzIuts6K7NCqn8+3mzLnThcbcVSkfX9O",
	"uDalJTLQc9e+RpQ6FayrJdOsQ8PgGbw7G5aukDb5iwfD6YjQO8nhEoGJZ+i2TlJqmIgD53Ar0ktZpFbY",
	"MfGSmKXUDCha+dBQ3lCyxUaLkVW7umnTdGCXvblgWlfKYM7t1pNLDxmMBqDq8HGc8nx4xw0+b+R2G3u7",
	"T1PWHYCuDc+Y9K4HXo+eDPrELLA+GUnuKTfoUeGxDJ4bpN2BYZFzzLI7dCKYbW87r1V/9yYajRs7Gf4f",
	"VF0hiVtlRCqK0YWXgFBGBYceeHfDthUx7Tl5Qw27pytyhb81ycHepJMA6L3rWLGECcNpqp9sztgrNdPK",
	"KE3DsjcP95iUg99B+7Gj5imKRtjSSRRfOLYMezDO5ZC8uzgBPzAugOrAhdqueVKsdQUufTmdK+n69sd2",
	"zncXJ0/pc2qX1HK2AAbZ+0a8qecMXOmq58xSMdZwLhYL77dbcaFZsjSV5F6qNJkObmq+xZWmeh/MdEv0",
	"ELa463p8uFnnjlye2LYd4FEPGDf+54jUmsIBWzTC9pU/921D9y/02NkPDqj/LzrsROhW8/nDTZMOVbZu",
	"ZS9wpgT1XlmRyKJsvw90E5ZPcMVZ50DhoN072sYUsHeayiVqHBYswF4gC0D97RywH3nVs8zaM6Seh/GS",
	"X9XoWi8faQNHFSIO7hWOD3R5NF25hv4JVZI5N25VAK4HQ1ImFmbZ8WDd8+CIV7iLALqr3+mYFN7K9GD/",
	"118no8nO7l40nIwmz1/8GE1Gk7/89POHyH7f3XsO31/8+Bf7/aefP1Q8hHpA1HIZqs7WizqhEbkDFaH1",
	"4owA3+58KX7cF/ILX4dP66/CYZFfhCo9R1gBT+c5KoXusg2g+s/1BUNrHzrz6BJwkK5ZX3PB9fKCUW2H",
	"bc6C38n9ckUWTLjnEqKNzHNwdfLmD/tlEA1KpC4jcso3jzlPDSio80KAQRNadNpIXrsWr9ico0bVXlv5",
	"m0UrSvyo+CgZU0FmDCJ/8NUr6Astv/basG0JovK3nejejo4e926+RLKaR/TgDcMWXse4ZxT85bgAR8U+",
	"V4NoYCXvbocAUaFz5UYl7K8294KZazdfp75GFc2Y1Tz7rVpdJO0/Lt+ekUsg1gSRx7tFoUxZWVVliprd",
	"ouH84MHQud2YmxVYRrShVlS2+gW5pIK8VlTEXMcyIocHj6J9mKQL81sf7CCxedzBybs/WoFJzOHxFLuW",
	"W7eKKE8a59xH4uHUu1b4Bq8cO1xKHnfAcA5391qFy7uOw9YuOnhTJ+yhSyZM2ANiGtckhpm9TSrl2nTG",
	"GaRykSs56yD7J3JB7E90xlN7plwgCbeIsgU2CpQ1WRIR99wvihTC/Oz/6cziDiJk20ZVBjyu27iHoo+P",
	"bMUOASDK4aIGXNefjAsLa0h2RjGa2ZtRoZrO2fry8gjMh4ZYQXO7RY0Q5Js7SNWW4jCl6+FZMXTB/tRx",
	"fjzplAYDr2yHtSAkKgbweEnNyOm2XIoRRlF82Chwy41WLrLiHOug8egh9N2RhKWGbgrDV9D4c/SNblZH",
	"nEQX4uES1+3wld9EkwOmhgYBHMKbPOK10aovsPRK3jIRBsG19F6+EgO+KC54XXwuTq3r2yhDhfVTw3HD",
	"WbZ8L3vBvEkEdZtXuSvOkhDI7IG5ZaGIhq4SBAQcSplmGGL8+wO6HgiNWgkGQbtl4YprVwDiCMLgv2No",
	"tD+aXtNGRh+6Yr52X/zYa57DUC8jw8lV5RTo2PEmiEerO10q75jSSON9Mx+SXLHcPjkkuRLS/3QvV1Mi",
	"puxTiMPvDY14AT5j4wXLMjrcG+7Mhtx0mv7glj7BITynynB4adfujR1uvHcDAdyjmgQOqXv8ubPcrrtQ",
	"dU18pznvpd0QEJGyBzq8/hVc0lRmUdzwOPLPB3/FVwNFRSKzhj/sXzaJxMM7EljRo3ejZNdSdl1a/1QA",
	"P5MtL2Pr7crdtZqOvZbexB4kKnvF3SsBPLeX6RlwIyHi1/sfbXynOxVtmV/fPhJieiXz4S3R/ly2gkvv",
	"g2FCcyki/2rtIvoPzo+7I1vtbPn64z8r4pQVupyuIocOnuzb7AWSQAjWU6vSGtMI722RhRi01SA4uRQY",
	"mq0TDLuRpDKIa0u2nAqarrx0vbMxAWpoH+tlyobXtuAP8MagDc1ysoXhZ3rb8UKr4JVrvaealIJf+ab2",
	"l8nznd295930uCuNwQEpBP9YMMLhIQFiZHyQUgPKNXpnf4uzPB3SWbyzu9cZALOR1agU9jtDwYPM3JYh",
	"nEpt+wQ9aNqUqaeDisWl8VunFaV4inr0rls52lA+95OtuxXv+oQrv4kaI+9+PnbMmzexaND9Aiuz3Dx5",
	"VOzWQ3YMTXsHvLK/+sEwnhDHIn+uLLUngroK9frCow4QNZbSBXb/uNSh4/unLiIVaKHk3cVxi970x2OU",
	"nchW72tJPTayuxn/5eXbi/vJf75ZyL443CpY+p4Au57RejZdVZZKS/Raaa3xlOafjR67VwH8gXCWynI5",
	"yKMKMvwadfYoAdB6E+ww68B75gzyw+CzZqmmQMi5ewHFhCvtfdsD7HYF+vH5kIlYJlbgwOGhbYXDzlam",
	"M0hpkxQxbnXVtDALPm9liOnOC9UAO2x7Y5C7XazLKhMhB9BrwvGcP1IHtwq+kHHTTckxgJC4ZYqhxdPB",
	"dv3p0Qccb+zw9bRQhTKQdN3q+2JsSXAaqqx40xjUJy00POytWyZrepBt9jy4xs+k+4d9/tMTV/9gFIWH",
	"sHXLf3PCz44uSGgccKUEv6q4n4G8H2PQN4aTbrdDXCy5ywrBzWq8sNRBXeNO7nZHOy7epdUEMcpQffu0",
	"XZa65rpdhlbjk5PTvoPqUVt/7dNb7T4UxoSN37jf3p6d/eOpvkD0MRTDJuO3hxd9S3eDNNad8VhJLedm",
	"bJSMlXNYUlY4sLdb0DumhnEq7+iQP4wTKQrn1DTngplCsGQYS5UM757s3uT9F6+5mMt1bs5rjU9hGCCG",
	"x3aolpvzK2YoT8ErtnwAoDPng+T6ly6w3jEqpjlqbJzp0VSc0rzuOAcBIxg1IeZyBPlD0MFJBhWf4ZNd",
	"daipYBjOHGYOMYxbeF0ioGv2XkVEsRSjfCNChb5nSm+3nHITnfJsDJQXjubs6AKTaJSThghZPfjw+fHr",
	"1d87Gvi1DewhusUNooFbXf/w1Qu+0fgfOu2lFcfX9fehebDt+1B60NbvRBc8o+rXlKqF//zoXp94LZw3",
	"8Pq91Z2Ee3iGH2t4tzvM9p66DucjvG4dfa7DbUh7h+P6StPs42I8T6kYmheOkemPBU2GHxeDqP4rnEP4",
	"8UlbMYoKzKGxfjeVdmOdMxYvh0YOwV+mZ1/VkRtbc36g90uuc6aGhotV6R3qv9pNfUXqhiDeVdGmKpHU",
	"OF/95lRPuC5tldymAbouCfSC0TWOf1m30RqUE5ePjyboNWZBW/r+gbffK6fm6X1y06voge/eu4sTTbZ4",
	"8N0LAa4u5mG74Tbn1MvN9MLPHzY0WbV1rorB/Hd6KFhvl8eD7THId4kHj0kHbQ8PtF50WB5d+KXlLs7G",
	"AWpwSJpVCDu7oaIiJo8gYZp6e3ixT86k8VaNQjHy9vACIhteWYGEHL69eFVmOdPXTiLxic4wwS6LGc/B",
	"TUJDvKzv/ErGv/z9oNo9kfHdR+p6u2+A41wK/PreMnWX3gpsIf+O7cbNhr47cke/IDv561RC/MFwt5z6",
	"7eFFbc1vDy+i8OPhwfnV8duzWoOYAmBhP/VEhV2Q2NhZzN3c/hvfp3E+Lf2JRTl8Lm4/PGJCmDWufEA7",
	"evLGwPo3tjW7LXVmeOkBkF/eGgh1Zl2Zc5Yma2P6HonYuzSqiE2hLARhLK+V4YvL2utEtgDhowrqWVny",
	"NY5DFSPzlBrDBEtQh0ukIUKaMpWswGxk2i9C+2cf/3g7L5VDcISThXFelX7Vlua2BNiMiWIkMnjQnM8Z",
	"g6cOUYxyBW9Zg3/bG72YeLOj/Xtnd2/0/MWgWz5cdOceOhYJv+NJYamQZTmuIW4VYiYtqGbywUXaBnaZ",
	"+LRb5zIvUuoft6ywPNSGLoAaBRhfFmpFI3JOkyRllkw95XmLPZgLWFanIBNyGtZ8McP5B0YKZAnuQI0m",
	"HIs7cKgCS/E+8UB81CJlp+1GdAegI2FcNomG96hIulLgUVivInI+18y4FDIMxiAQ9rzFHuK00PyObdcj",
	"Zjvdv7oTGeGanBXv/OgiIm8v3kTk5O1hRE6PLw/rFuJzEOW/RyKjnzd5uYUYqaeCasYWXNRk/+5MsZ1Y",
	"c7UM40CDKjD+Qy4Fucx41UN8HW5EZe4l2EcEB78uE1PAnF7ZsTfTHpqV3NJdUjfIjgG3gGw5W5W7jVKk",
	"q20fNl5Yvk8oqTaJyEoW8IqNyY9WhIpVgMwqZ9XRo6mA1Bt2mNL0ZceyNEQW3s1eMaMwKBUTyglpfP5r",
	"l4AB2j3TIcTPbQQyC+hWRo5fBzlTGt6Z4JEAdAmXFw5txeybpvlr6s4bq849mnMHd0e7wXXfMV+4Bq0j",
	"IFsVFgOU+1kwQjwrzSyrEPMHwkZ4+fUxws7e4rv60cEx1KOHN4ZE5OLo5dHJ9tqz9CNAmHVptCEcncEx",
	"CVHrWOcuUj8a3Et1q6+BOoDfMEuuuXiinvtIqkEPQUBuzlCdra+nvPnkHnNIGJfEaTSIBpgB6ljEIyv6",
	"ckEOC7ixQn67BISPUIs+udPvaV3oB95pWER3osEnpwdsMsBvnh/wkeuzXjx2qL1mw03p7b5KJX1+0t4r",
	"tvamfAEscYrHgdgX4OJRYC0KqcOw/q40rmFvIL3SNiXUVQsFUq994mSNKhE5O7rYJsOSKkBTKzrnVGhM",
	"9FQTSuxw3vC5X8ZAUjXjRlEVWB2tRq5jprkaxwOlOBzXPrnooHA+nX4gBL0HaQdzdt194gRNfgfJV7Qr",
	"4WB/hFfs5hjO6OJePze2Hnege5eNv8MdudfG3z7GtntTzRjd6+NUaYWW/l78aBg627bt6Ikkpoq4G/kV",
	"hwvVTtrMMDHAE0nbmoyh4SSXPCfuBbuSmjpwuS8WsL0nVaBqX5c6NBpYZHkyDBqUB+Dohoo2yD+KuT36",
	"nYkfE8pqRv8OmcznEekOG2y8BvQa7zrw/1zZ7iJhoMCHNPdesMCRRwRip1IO2TV8NS3t/VkCARKLqUD1",
	"2g7Iq4nz0aIx9tnBNZmxuT39mKZpyB7ARJJLLtrC1LEwKBK76LRmNDQ6+byCDGruE5kXIqF2bppCMv4n",
	"CVwfC6ZWXQWNqIqXBH51Zq6U3VGPzM24zuYyCc3zNKT23dRih2spz3Ad/n0r453Dx9573S3XV0DBKmIJ",
	"LjzC1EMuMaxGYaUmmD01CLcHXm6B3WCCh5H1+Qx0X0KDyq2AYfCRyK66jq1X9jPkwDeSvGEqo2KfdBRL",
	"+6aKXfeD3YbvdY88121oWUbgrYX7t8JPO1wPfvboSrgEY5VFOMatkGYcpeiI1KToqEwvb7/NGM26lYjH",
	"dbev1JBcmE4HZ5YpwwhlH/egge5iOHBcCR+pBlSvtGEZuNVCIG8oS+iCqzultGb6kU5FtNsFsiWO9dis",
	"qgP4hCGbuN41LJjrPe96zZ0V42wLNWcz2RHO+rJiVCa/PuxEZLUTkYfdiKx2P9gTyPkDZGWQKuHCcryO",
	"/BglYcvowzH++DwaZFyUf3Qk+nXyUxeOl55acduQOdzZ7iKqPcLfJcuoMDxG9QQJSUpXIHULmq401z4/",
	"Eya6MdykLCKG9uQW6Tn6i7otHtRS5zCNZvxNLZVwUJ2na/G6w6sfYgBD7Ms2Kobt+JcWCvsej8ZvtpMN",
	"VDC4faHBoO2CcqoRFhBDNw3TTgdWBgvRONuV2x1WtumN6OhQhxtE2fXBDsIrW0F/XwwvP5+HW188xrue",
	"aAwXS9jOXQCxSf1BGBueCOx23bF82UnwQOc2PI6eoN1jESuG8m5lveBQvz6C90uPJwTCbnZGGAoKqQKV",
	"dgHB5cFBzHIn1Xg8n0C18K+jHEguO99MnnLYHUve/JB7D/B1BeDtZYR8F5ukGKFqAfpVh8ADmTVc+icH",
	"ptDapXkNc9Vuy6dpyG+Biata+TGmg8/fIMsI7m/zJCNd2S2iCgQ+bADyDe5ObX2b3J81Z1AdtwR+5WQ2",
	"B6PfAcKyDzM3xcIQSdoyzhglUw1qSskJsYSHlKkeEXT3QSPpdEALIy2SYMBawmKeME3uy0QmAETqWFq1",
	"NMV0IKRgZV8I1hXSuB5ihRNiU3/uZfOs0L6pcQm9rfxu+9guuN19V4KC+vIncS3HTUjj06hp6K+33dwg",
	"gnUOKrj34fG0aZtNu5YS13/54gQ+G9yh/hw2n76LYPHBImHwPuzVxSE859HIICwqCrd06/3BLxE5Pd+L",
	"yOuTg8MyfufReKGUikXhYgi7DjIco2+IfMvtATM4bfmKOxFemmEoQVZ3R2DiCXGgIeq+dNbs0et7/VV7",
	"3FXXHyLCvpOgVg6uT5nvB+creCtlCcFyvDFLAki/HkgNI0HteDZXR8oNNr1uECjVZbZtOsTIhK7+fWOb",
	"Sa9G+gtTmkvRD2SodgQZZDvuCFZC8nHStTXvTnafDyc7w50XVzuT/b3J/mTy313QWXBzHcss66rT+YZD",
	"zHPGDVlSvayNj2L2884h5fUdbqtjSElcLA3xbeqpI3ZGuy9Gk65he8f0WQC6BrzbGU26hmucU9m1Ao+o",
	"CvzatrpO8om19duH2RVaCW+3SNeGgTplzFDwwfvqIEuyBXnGCFDU87M3T6ClTCBgQrHomt5or9A+wbrS",
	"hAlEUsj/zNOUu3D+wSavPHNFM3adsJSuuqcSHF8K90nCdZ7SFYHGHZO1lQQcvEfzqIwM7Vz5i86BsITu",
	"hvCAxl8Kkc9fgnohzRhNUyf8bJaQ+NGRKybDRzMPP/GGWAGiZbhPugxYHwuwf1Wqsfua/mRrEpGdiOxG",
	"xIWUN84uGjwMF3LovhZcmL3dTUOL94FxjPOUchGRVphxiC0ebGQaWBcn3CoSeOC2VyY7dmWuXWX/Jb1j",
	"JIxYWedoI3ypnup6Gy4GijacHHWbMpWVp/s9JLEeJdaSl4ovuPB+vug0iVvucC/tu4/fZkLMfj94mmMm",
	"djUVUG1q3qwsPSrBtgnH6anV1ZVTcQHBkS59T+kcHhL+Y8Ud3TrGlN2x9GtriJ3AIHBKq8dzkz022iUM",
	"shFd7F5ILSs/BLJGPQC7Y2pmUWZFEA6lhShhs2IBb2PQ/Z4qEEN81txSHnENWux0s13WlorRqTTtXa7z",
	"3HfJmgDYI/LMd3uG0ScylQqM8rEUWqYsIs/+qaV45o0h3un/Py7fnkXkWSoX88zgrxDfNGTzOY/BY+CW",
	"rf4KBTRITrnSEXkmpMzdSDx1FbnLF52w/H+iYyyODZq4zOtgqzR+FHQ9NQHaimccM62vb9nqujMb0PtL",
	"gk3sxsjxq0pe+1u20kYqRvRKGPqAO2SxYoakUt4W+Yi8hkx5vsjkwfvL64PDw6PLy+v/PPqv6+NXhIk7",
	"rqQAp4k7qjjEL/JQd2VUk2JXslBDXMzwlq2GPOkRycCtooNF7lVTk/h2/lnnmd4b0Yz+JgW916NYZs+s",
	"3vasrHz782QywWM85eL4bV3RbXYGViZOMJNzpbJJxbMAIHVdwr8b+A6g5Rl87QFcHh1eHF1VzuELDgEn",
	"qZxFp+sE0zrk2lkTSYe7hLZ4mfBaudJwK1IpjPGkvXctG2YZ4oo6Uz2xa63TR1PTH2HdysvLk/HVySXM",
	"fblnaYfACq06WP/2IWkftDh4fxm5kuxYxi+maYlKHdmNH6XkG5Yxbd95rCd5bdG6Q05/v+SGpc5V0LUl",
	"ti2UtBkfn2N60ZSLW5LIeyjnpaFcEstys4KS9dDelS91I1hpheWG5IrfUcOIHYfPySyV8e21+3jNc0jt",
	"aYG2Pao7mrh/utsVJ2JU/7Lz8+5oMnpyoLoHRk7NclNg2LYkV2zOH5ivQZiy/fEYs23v2X+9uzhpAQXm",
	"qAJlRF5XOheaETrTMi0Mc20dcRq/00zpsdVWx9vYCWexXWZFfMvMGNfje2Srofte5HBA4yY8q2NactXq",
	"8DQ4ts7x0Vv00vaoFVEsUYMoKiAD6M7uX0YT+9/4p4jsTCr//svuaOdH+GtnNyL29Hd+/An//jEiOz/+",
	"PNp98dz9vd2ZA9Mjry9NdO0V0OrK99r5F13ZnzlUuAmxeH40InOXvw5iC0qltqwROgHuwDMrA+z01aUM",
	"q9P8N3Y9WxlWX9jO5PlPL/7y46S3UKXtZ7HWD+SqY2LRMIID1qLSwnhhcZNHVEUuzI/P/YIxu1bCM8xC",
	"WQ8Qnzz/qW+dWDPonidmOV4yvlia4FKiyRaG8Ib0porZbSU17ouDr4Nom5p+/uzkVJeYmGJSQXx6GBwA",
	"pR1ELr5+aUyu98fjBTfLYmbpjRPIk9nYVXdrR7h6NQLrpboaZOAwj6S/dH+3ioZ71397dvaPIZaSPD0p",
	"o8en4k9/Ij5W2w1crUjvAnm05yonldGxkHhYQUUEOjg/hpetH34oKwO+CdkXf/hhH7VpqNZalqrZOjw5",
	"Pt9upYLCgaCDrxhoRwiONSE/F6wHasz72DaFBfWGgLBzmqZWXsHxQhlBO1bpdKnY0LmgOsYPnqoumBl7",
	"ntGMJT6ioeIrZAdyEQAEo9F0RKRaUMF/8wlq/Iuwy5QBRZHK7V14hzyAkPeKRDUXg068e6IPpQ1hBmVu",
	"y8j51Va/gNkRChV6UgL1AqhhUME3ZdQyCEM8OiIOjrgcJzLW48CLA75AymxI59OBMzEVRBWCQHA1TaVg",
	"9iQqBTypIHgPSJwW2jAFyHICGFaeXwPTLGFkD4YpEO3Oj4l/GYohY9CwAw1vxjTnmDnsphTLa4510DOg",
	"kgk2Ho8AFwdvyvKHtm0VVby7OdDrzF4VlniU+VjQlJuV7XLIhFE0BTXQxUAwdQeOzLGSWpOEW+43KwxL",
	"iJAJTnRuWVa8GkLoETav3T5I7egqn6aM3jFNrCxqWygaNMttd2SvGeRXdif4J9J1LxETMWWexcDqVaoV",
	"B2UJom9vSVAc6eD8GIbZ7Fz8tcSXGiuJZNTAOpzpPrx7R6At+52clgTEyfCOkOCAmFcybBcGtD+TSp3n",
	"fwJe2MMfIssoSZDOaczcSOC9XF0XGP5Dsk1NttZkYdm2d8CKbjiYy2h5GIBiB3ynmW4U7HLWha2bL6qV",
	"5qqi3ThY2Pt6SDWD1SNgEFsjAog4RDAqZhRndzSNyB3XVgLRPOMpVYDPCPUaOW4izuuS6IbL5LMmhnqm",
	"2+TPVQyrjEFeOTxb2cEOesvS9taWxbEOIWwAaOnuMOPCyr5XVye+6GhM46U72deOM8Daa3ptsx6rfx6d",
	"U56GuxRYyaZ7qF6sjo1U6t3iiH8vLHn6LTBPO1xGDY9pivG72pIb26Qswc7nJagr+Gu714JVgOS5mAiy",
	"5YJTllQkqVVAOEuTSmAcRqylPGbuMdVLNWlKLqx8pckFUCvwyqiLOCVPSdmCYo5ybkCH9ozj4Px4UHmI",
	"HNzt0DRf0h1Iz4ya6GB/sDeajPYG0SDoVXjyoI1K3WWeyVNu1QC7Uy6MJOCZz5S35iNr1Z4J1KWGRvZP",
	"LzKdOqRFDACEL+sZt3EdazNaodKZ9VAS03ZlJsguFjtSmkPCJl9C9q8huyikxKEaxaZagny/DMCr03Cd",
	"2hJSKCXuiUz1Yg9d1x5aX/GSqN+0J98Y4m6m/evCpaehEMQUL6uFuYE27xK8unoE3RhYC0Pq1Zk0S2do",
	"B7BUXwQw/CnoTMcJPE4U4vYKXwKcfvhSJqtGEZFKfNH4n67CDNrLH68KUZTxa5/rTxBWU8W8PcDhAHV3",
	"J5NvPbfzdIDJu16W4OwSoguwsc2LNAUt+/k3XAmWyutYwbHAB3HlIRQNXvw+8zq50SlEzDWMBrrIMqpW",
	"HjU6iIRmC3RLtM3HLg/cqp/aHPpMcVWKU0Ypx9SwBVRed3Tn7OTYUYNHUvV60vM3eU+ODXkv1S1cqP/u",
	"6waM4czKfTQlJ97n6riUIM9OjrfByc1tyukjXtpG1IWwQpeso/TjhBr43mOi3BOGOGbOjdEl+NRTsZT3",
	"5J6hD6MFynTAhAGKMCCQ6zOmIuEJNQzjJNpktqROim1Aocp0fUikgnm3mnLZ80rQnUO645DmGGT3UmoF",
	"Ev23Ah5/XtOY2ZMbn56dHPth2IMr7GEkkGK3hyB1TZ2EfcnAQ0cYcuAiQEAo9YdgFSV4Ob1jY8EW1P2j",
	"sDqEUxZlzmPfwZ02DOHO4TeMJIBW/jD9EXpZAMg/OpK53sfoZA4ChVUjDHjZNvRUZwiGwyi1eRyHcEHz",
	"XMlccXuQIQ5plXu9A4V1D313JqA6LrsOoJmMZGcy+XPwdNMj8l8uMU0Df7kAx9ey0ErwN8Qb5xIFcFeK",
	"0v/ayS/cyN+TZbgp/lVcI0zfzzjqmBZKpP/PYSLPJ8+//7yu+r40BML1/9XMy86+9/1nb5y9c10ghQjC",
	"LVS3dySwLFm03WCvJZdCGa02LPJWjFbsZay+Tol2lYkrRhxnMa+WS3dXvWFTskz0qhojT7iuVN92JkQw",
	"WDzTdTuF08TxCfHBRBijD6WREshihH1blSoqBk5HkWCMig2izeyewuoqZhcCfghUmSIfTQUm2/bWFuxR",
	"MYMZCQVDSyWluhpvkhxCgETmNHv/BNSdWn97nxzE8BBXrXLudOISCM3BwFZT72oB66zzd5yWBhYHp5oh",
	"BrlHpQ4+QC3Q/u9aFZ9stWxb2/2V8jcqjo8Wm+9TGr+jjsr2V2pkUvgiyhiiFoP5yL272RESlhRIk1gy",
	"FU7ThuOYp/AgA49zWHBVsaQQCRUGUmv5W9G0CNrPdWnOatU1YQOwxiHUEpL2AhrcVMmjjA0zQwxHugk2",
	"Rs0Up6kztQSLY0QyqQ0JrjjbrdEssb3Zx5Akz6qRIFSS4QO9qBieW9KGp3CltfI7yRyuJv2/ROCo18O3",
	"c/cdS33MLnfuoT8vlrQL19fcrKF5h49gi9+VsK9UDv1DzvkfoqT7G1K5Ryg7hBTgG4gPlfc0lA8q1Uwc",
	"U4JCJGQPkv/aQ2/JCJaxuiKIh1aJOAwlwDQ5OD/+OpZeKaHyDXn6n/5EQuFrIKLMkBu8aehMdINJWWLG",
	"7xi5hEMYWl2VHEG1T6iNvY3b52VE5lSgbxVWCx2RI6vOI0GH528uNKHkxkKpBBIYW25cfOEI9T9cCjog",
	"wyT4mkJ+ffX27OjDzaiD+9tP8GjSU7fRyWxIiH3tV8xY4tZmkUDJlE3FFub0iED9jUjI6LENdDu4gXdA",
	"rV4SORDO0RoKfxiclr8HeW9W5f2dKXyrzOZn58s9BrTopO4bl1Dv1FF6anSOyAUzhRIuVhjyc0sxrJ4V",
	"iirRVEjVhfLNo3WSzVYVASCZ4x9M4X+j8lu+jX+54htYVoXtWIbTIYwjK3MVa/Y/DRasM9ELorQl9Bq8",
	"KdpF1KLwABOVbgpRWb8rImdHF1FIchW5uhcRvqE0o2QD+zjyqiaqiO1nzG611Lb9e3ifBEdge7cgiOZm",
	"yH+6IbqYz/mD10Xc6xJOctBXbI9szQqemiEXII6fp4UGs9/aVVVfrpx24d5aN9hS4132KMvNCt2Z21jg",
	"hn8TODmO36yb1sf1Nx2/TH652QbKpNQwxbGHaj0nuKV6nYXrwqwu+xnO2XBK6pjWJ0uDSa9eQGT52dD+",
	"4+XBxRWi3cnp39+QDn+m4B/gpqYlAv7CNZfikblpiYRQKCUirRoPvpIIvqx2Fohw019V4sPd5qEO0to1",
	"1ILKYSHvMYo8Iu/p3e4vLN6NyN+Kl0cXV8hwaqWVGsJjRW60kqGjSk5CRFEFlPYu6eOEa3Pq62F9N/bf",
	"qLnZx0y09zP5V+lXL+n/zIfIky4JHlmDcnlpuzWcI59KuQy4d1Y05Drt6wIPX/VbIVXlYnydGhPu3je2",
	"S9r1gh+LK3MEl8aVXBovqUiqKQqxD2wOXqq6y7+AhlAJx3KxXVuuJJKOQJXQzo+qBJAdEmybQyjbdAcQ",
	"djafLQBrWX8oIr/8/cAb3K5s83N0uwFlTGZ+o8FMXKkEhTQ54XN4uzXVXNW2k973wCmrPdml3XQWObrp",
	"q/bku2O9p9oAjxd8Go1GT6jwhGtw7mV/P2jClbgjvmlUfboJ9vcKCFqdDxHmlQFqlaFunMMmXTBSuUEd",
	"BNNyG6zF9p00tWp1uN9ZS6uVqeoiVUg6oIjUH/av//WqDgpWX67mXNQKFXrGY2nguFui2vYszcmk/Xwt",
	"CLka7OhJJS3/o372zve9dGNwvBDk5GpJ5oamg979V9514RJc2VVCDuXZyUmt+o0LdDg/Qp4EC4J1BmPi",
	"tFI1ZDpwPOTtxRtwjq6uu+yAJUXwuacsKhI6n7w9tJ1PQjRB6HjG7sl/SXWLXSHdHAvdTo8vod8p1zFL",
	"UyqYLHSA5le63LSUi/BI87Gt+21Bx2v+00gK8bD9mKeNFY2dk1T7zGznuv7iGWjcVQrpjlMUP/DvG8sA",
	"acYMU50MoJrgnn9HPtAo9/S7M4NmAZmupxF/7cqCen8whv8DjKG8cF/BHRx+NSi45wGKrnPgvsCgLKZJ",
	"3uu6Hlyby1oCRhLqgqFqRL9eGtqT/EN0fb/wRRlCLXJ8nXCe8Vmhzf5U7IxCqJebz9dmQMLoWZ6eit0R",
	"ucCE4pCN0VdumIq9EblkIunYk3M8IFSTG7e/G1wH11Zi5QtBbhnLdZlRxFDDUqaxLiPW9HVLhvhXpIQW",
	"/mVRiVQueDz6aqpfs4l10Hz/sIa9rsMPQPkxMqUez5ArNmeqk23Ugxqm4nWlPm7gD/54MblXI4IBnncw",
	"gRFAZ6h5wqbiJuWzcehqeUJ8C7GjSx4vQzhECbvHy240+Ygd2ul7342HVIun/O4MpFY5o4OOuM27A/qD",
	"d/zf4B3+Mn4F57BDlGR+VRJ4zzzAuryOezTKjKwLqO0wToMC8fV0smYDb0wLTyGYQFABXYxIwuCvIRfc",
	"uE8Y91M2gvQOukt23syW3nJM/7vvUY/VDi9YfkTH5NCeMwQUspyYcqXDQGrVN4ouq//4GotVfgnKFFU0",
	"XyqqQ3w2QM8HVFQMYfdSJT5C3NWL8RHmZfkY28uXdAvu451UGqb5js7ejco5vzuRrteP6YsRUqHIyx80",
	"+o837o2IdOV+dhFWJNXlQ1g/tS5f2LTLSm1kbdzWexs8YnS8qEnlHtW+7hWj/nr3bZ8y3KrBEATeAM+0",
	"30ngSNWApQiWC6JyGdSS+CAeZ+XxEMBo5pjNpLy14+JnsjuahLGPxCLlejmcy7jQLHEDINQa3d37pO+p",
	"WTof6iK3GIM9AcSQiRVdtOyXgzKtuF7KIk3IjJFZLV9uyLyF+abBgxszO1hlLiTPByvb+4Nf4ElGZpmV",
	"xBMyJIrek/PDU1j56fkexKOeHECx0NPnB+MD+0+06GFOF/vXzc2NvTtT8WkqCJliFmn0oO7I8j0dRNgM",
	"sBGbvbtN31xwcKyeis8woh34veW94VyWXFhV8ZvO5n70c+DvTFSX0eJq5Y06cKm3vwdna6ei/52ZW0dK",
	"9Q5qhxhpKtnJ/2Bx/+tZ3FWtxMAXc7kSwxqcaavuseFeNioJ1dc6cjXyq0dkEfLCR2QWctCj/N9O8D7q",
	"cDI1v4SE69/tvjVT63fA3TWpFhz+13h3NBzyjIddfWXQDPBTQ+bu7qxbB+fHDotDigvL/QefP3z+/wMA",
	"AP//RC7vBALiAAA=",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	for rawPath, rawFunc := range externalRef0.PathToRawSpec(path.Join(path.Dir(pathToFile), "../../../antfly-go/libaf/chunking/openapi.yaml")) {
		if _, ok := res[rawPath]; ok {
			// it is not possible to compare functions in golang, so always overwrite the old value
		}
		res[rawPath] = rawFunc
	}
	for rawPath, rawFunc := range externalRef1.PathToRawSpec(path.Join(path.Dir(pathToFile), "../../../antfly-go/libaf/logging/openapi.yaml")) {
		if _, ok := res[rawPath]; ok {
			// it is not possible to compare functions in golang, so always overwrite the old value
		}
		res[rawPath] = rawFunc
	}
	for rawPath, rawFunc := range externalRef2.PathToRawSpec(path.Join(path.Dir(pathToFile), "../../../antfly-go/libaf/s3/openapi.yaml")) {
		if _, ok := res[rawPath]; ok {
			// it is not possible to compare functions in golang, so always overwrite the old value
		}
		res[rawPath] = rawFunc
	}
	for rawPath, rawFunc := range externalRef3.PathToRawSpec(path.Join(path.Dir(pathToFile), "../../../antfly-go/libaf/scraping/openapi.yaml")) {
		if _, ok := res[rawPath]; ok {
			// it is not possible to compare functions in golang, so always overwrite the old value
		}
		res[rawPath] = rawFunc
	}
	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
