//go:build go1.22

// Package termite provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.1 DO NOT EDIT.
package termite

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"

	externalRef0 "github.com/antflydb/antfly-go/libaf/chunking"
	externalRef1 "github.com/antflydb/antfly-go/libaf/logging"
	externalRef2 "github.com/antflydb/antfly-go/libaf/s3"
	externalRef3 "github.com/antflydb/antfly-go/libaf/scraping"
	"github.com/getkin/kin-openapi/openapi3"
	"github.com/oapi-codegen/runtime"
)

// Defines values for ConfigModelStrategies.
const (
	ConfigModelStrategiesBounded ConfigModelStrategies = "bounded"
	ConfigModelStrategiesEager   ConfigModelStrategies = "eager"
	ConfigModelStrategiesLazy    ConfigModelStrategies = "lazy"
)

// Defines values for FinishReason.
const (
	FinishReasonContentFilter FinishReason = "content_filter"
	FinishReasonFunctionCall  FinishReason = "function_call"
	FinishReasonLength        FinishReason = "length"
	FinishReasonStop          FinishReason = "stop"
	FinishReasonToolCalls     FinishReason = "tool_calls"
)

// Defines values for GenerateChunkObject.
const (
	GenerateChunkObjectChatCompletionChunk GenerateChunkObject = "chat.completion.chunk"
)

// Defines values for GenerateResponseObject.
const (
	GenerateResponseObjectChatCompletion GenerateResponseObject = "chat.completion"
)

// Defines values for ImageURLContentPartType.
const (
	ImageURLContentPartTypeImageUrl ImageURLContentPartType = "image_url"
)

// Defines values for RecognizerCapability.
const (
	RecognizerCapabilityAnswers   RecognizerCapability = "answers"
	RecognizerCapabilityLabels    RecognizerCapability = "labels"
	RecognizerCapabilityRelations RecognizerCapability = "relations"
	RecognizerCapabilityZeroshot  RecognizerCapability = "zeroshot"
)

// Defines values for Role.
const (
	RoleAssistant Role = "assistant"
	RoleSystem    Role = "system"
	RoleUser      Role = "user"
)

// Defines values for TextContentPartType.
const (
	TextContentPartTypeText TextContentPartType = "text"
)

// ChatMessage defines model for ChatMessage.
type ChatMessage struct {
	// Content Message content. Supports two formats:
	// - Simple string: "Hello, how are you?"
	// - Array of content parts (OpenAI multimodal format): [{"type": "text", "text": "Hello"}]
	Content ChatMessageContent `json:"content"`

	// Role The role of a message sender in a conversation
	Role Role `json:"role"`
}

// ChatMessageContent Message content. Supports two formats:
// - Simple string: "Hello, how are you?"
// - Array of content parts (OpenAI multimodal format): [{"type": "text", "text": "Hello"}]
type ChatMessageContent struct {
	union json.RawMessage
}

// ChatMessageContent0 Simple text content
type ChatMessageContent0 = string

// ChatMessageContent1 Array of content parts (OpenAI multimodal format)
type ChatMessageContent1 = []ContentPart

// Chunk A chunk of text with position information.
type Chunk = externalRef0.Chunk

// ChunkConfig Configuration for chunking requests to Termite API.
// This is a simplified config for the HTTP API - differs from the full ChunkerConfig
// which includes provider selection and caching configuration.
type ChunkConfig struct {
	// MaxChunks Maximum number of chunks to return
	MaxChunks int `json:"max_chunks,omitempty,omitzero"`

	// Model The chunking model to use. Either 'fixed' for simple token-based chunking, or a model name from models/chunkers/{name}/.
	Model string `json:"model,omitempty,omitzero"`

	// OverlapTokens Number of overlapping tokens between chunks
	OverlapTokens int `json:"overlap_tokens,omitempty,omitzero"`

	// Separator Text separator for fixed chunking
	Separator string `json:"separator,omitempty,omitzero"`

	// TargetTokens Target number of tokens per chunk
	TargetTokens int `json:"target_tokens,omitempty,omitzero"`

	// Threshold Confidence threshold for ONNX models (0.0-1.0)
	Threshold float32 `json:"threshold,omitempty,omitzero"`
}

// ChunkRequest defines model for ChunkRequest.
type ChunkRequest struct {
	// Config Configuration for chunking requests to Termite API.
	// This is a simplified config for the HTTP API - differs from the full ChunkerConfig
	// which includes provider selection and caching configuration.
	Config ChunkConfig `json:"config,omitempty,omitzero"`

	// Text Text to chunk
	Text string `json:"text"`
}

// ChunkResponse defines model for ChunkResponse.
type ChunkResponse struct {
	// CacheHit Whether result was served from cache
	CacheHit bool `json:"cache_hit"`

	// Chunks Array of text chunks
	Chunks []Chunk `json:"chunks"`

	// Model Chunking model actually used (may differ from requested if fallback occurred)
	Model string `json:"model"`
}

// Config defines model for Config.
type Config struct {
	// ApiUrl URL of the Termite embedding/chunking service
	ApiUrl string `json:"api_url"`

	// BackendPriority Backend priority order for model loading with optional device specifiers.
	// Format: `backend` or `backend:device` where device defaults to `auto`.
	//
	// Termite tries entries in order and uses the first available backend+device
	// combination that supports the model.
	//
	// **Backends** (depend on build tags):
	// - `go` - Pure Go inference (always available, CPU only, slowest)
	// - `onnx` - ONNX Runtime (requires -tags="onnx,ORT", fastest)
	// - `xla` - GoMLX XLA (requires -tags="xla,XLA", TPU/CUDA/CPU)
	//
	// **Devices**:
	// - `auto` - Auto-detect best available (default)
	// - `cuda` - NVIDIA CUDA GPU
	// - `coreml` - Apple CoreML (macOS only, used by ONNX)
	// - `tpu` - Google TPU (used by XLA)
	// - `cpu` - Force CPU only
	//
	// **Examples**:
	// - `["onnx", "xla", "go"]` - Try backends with auto device detection
	// - `["onnx:cuda", "xla:tpu", "onnx:cpu", "go"]` - Prefer GPU, fall back to CPU
	// - `["onnx:coreml", "go"]` - macOS with CoreML acceleration
	BackendPriority []string                           `json:"backend_priority,omitempty,omitzero"`
	ContentSecurity externalRef3.ContentSecurityConfig `json:"content_security,omitempty,omitzero"`

	// KeepAlive How long to keep models loaded in memory after last use (Ollama-compatible).
	// Models are automatically unloaded after this duration of inactivity.
	// Use Go duration format: "5m" (5 minutes), "1h" (1 hour), "0" (eager loading).
	// Defaults to "5m" (lazy loading) like Ollama. Set to "0" to explicitly enable eager loading
	// where all models are loaded at startup and never unloaded.
	KeepAlive string `json:"keep_alive,omitempty,omitzero"`

	// Log Logging configuration for Termite services
	Log externalRef1.Config `json:"log,omitempty,omitzero"`

	// MaxConcurrentRequests Maximum number of concurrent inference requests allowed.
	// Additional requests will be queued up to max_queue_size.
	// Set to 0 for unlimited (default).
	MaxConcurrentRequests int `json:"max_concurrent_requests,omitempty,omitzero"`

	// MaxLoadedModels Maximum number of models to keep loaded in memory simultaneously.
	// When this limit is reached, the least recently used model is unloaded (LRU eviction).
	// Set to 0 for unlimited (default). Only effective when keep_alive is non-zero.
	MaxLoadedModels int `json:"max_loaded_models,omitempty,omitzero"`

	// MaxMemoryMb Maximum memory (in MB) to use for loaded models.
	// When this limit is approached, least recently used models are unloaded.
	// Set to 0 for unlimited (default). This is an advisory limit - actual memory
	// usage depends on model sizes and may temporarily exceed this value.
	// Works alongside max_loaded_models for fine-grained control.
	MaxMemoryMb int `json:"max_memory_mb,omitempty,omitzero"`

	// MaxQueueSize Maximum number of requests to queue when max_concurrent_requests is reached.
	// When the queue is full, new requests receive 503 Service Unavailable with Retry-After header.
	// Set to 0 for unlimited queue (default). Only effective when max_concurrent_requests > 0.
	MaxQueueSize int `json:"max_queue_size,omitempty,omitzero"`

	// ModelStrategies Per-model loading strategy overrides. Maps model names to their loading strategy.
	// Models not in this map use the default strategy based on keep_alive:
	// - If keep_alive>0 (default "5m"): lazy loading (load on demand, unload after idle)
	// - If keep_alive="0": eager loading (load at startup, never unload)
	//
	// When a model has strategy "eager" in this map:
	// - It is loaded at startup (as part of preload)
	// - It is never unloaded, even when keep_alive>0 (pinned in memory)
	//
	// This allows mixing eager and lazy models in the same pool.
	ModelStrategies map[string]ConfigModelStrategies `json:"model_strategies,omitempty,omitzero"`

	// ModelsDir Base directory containing model subdirectories. Termite auto-discovers models from:
	// - `{models_dir}/embedders/` - Embedding models (ONNX)
	// - `{models_dir}/chunkers/` - Chunking models (ONNX)
	// - `{models_dir}/rerankers/` - Reranking models (ONNX)
	// - `{models_dir}/recognizers/` - Recognition models (ONNX)
	// - `{models_dir}/rewriters/` - Seq2Seq rewriter models (ONNX)
	//
	// Defaults to ~/.termite/models (set via viper). If not set, only built-in fixed chunking is available.
	ModelsDir string `json:"models_dir,omitempty,omitzero"`

	// Preload List of model names to preload at startup (Ollama-compatible).
	// These models are loaded immediately when Termite starts, avoiding first-request latency.
	// Model names should match those in models_dir/embedders/ (e.g., "BAAI/bge-small-en-v1.5").
	// Only effective when keep_alive is non-zero (lazy loading mode).
	Preload []string `json:"preload,omitempty,omitzero"`

	// RequestTimeout Maximum time to wait for a request to complete, including queue wait time.
	// Use Go duration format: "30s", "1m", "0" (no timeout, default).
	// Requests exceeding this timeout receive 504 Gateway Timeout.
	RequestTimeout string                   `json:"request_timeout,omitempty,omitzero"`
	S3Credentials  externalRef2.Credentials `json:"s3_credentials,omitempty,omitzero"`
}

// ConfigModelStrategies defines model for Config.ModelStrategies.
type ConfigModelStrategies string

// ContentPart A content part for multimodal embedding (text or image)
type ContentPart struct {
	union json.RawMessage
}

// EmbedRequest defines model for EmbedRequest.
type EmbedRequest struct {
	// Input Input content to embed. Supports three formats:
	// - Single text string: `"hello world"`
	// - Array of text strings: `["hello", "world"]`
	// - Array of content parts (multimodal): `[{"type": "text", "text": "hello"}, {"type": "image_url", "image_url": {"url": "data:image/png;base64,..."}}]`
	Input EmbedRequest_Input `json:"input"`

	// Model Name of the embedder model from models_dir/embedders/
	Model string `json:"model"`

	// Truncate Truncate input to fit model context length
	Truncate bool `json:"truncate,omitempty,omitzero"`
}

// EmbedRequestInput0 Single text string (backward compatible)
type EmbedRequestInput0 = string

// EmbedRequestInput1 Array of text strings (backward compatible)
type EmbedRequestInput1 = []string

// EmbedRequestInput2 Array of multimodal content parts (text or images)
type EmbedRequestInput2 = []ContentPart

// EmbedRequest_Input Input content to embed. Supports three formats:
// - Single text string: `"hello world"`
// - Array of text strings: `["hello", "world"]`
// - Array of content parts (multimodal): `[{"type": "text", "text": "hello"}, {"type": "image_url", "image_url": {"url": "data:image/png;base64,..."}}]`
type EmbedRequest_Input struct {
	union json.RawMessage
}

// EmbedResponse defines model for EmbedResponse.
type EmbedResponse struct {
	// Embeddings Array of embedding vectors (one per input string)
	Embeddings [][]float32 `json:"embeddings"`

	// Model Model used for embedding
	Model string `json:"model"`
}

// Error defines model for Error.
type Error struct {
	// Error Error message
	Error string `json:"error"`
}

// FinishReason Reason why generation stopped
type FinishReason string

// GenerateChoice defines model for GenerateChoice.
type GenerateChoice struct {
	// FinishReason Reason why generation stopped
	FinishReason FinishReason `json:"finish_reason"`

	// Index Index of this choice in the list
	Index int `json:"index"`

	// Logprobs Log probability information (not supported, always null)
	Logprobs map[string]interface{} `json:"logprobs,omitzero"`
	Message  GenerateMessage        `json:"message"`
}

// GenerateChunk Streaming generation chunk (SSE event data)
type GenerateChunk struct {
	Choices []GenerateChunkChoice `json:"choices"`
	Created int                   `json:"created"`
	Id      string                `json:"id"`
	Model   string                `json:"model"`
	Object  GenerateChunkObject   `json:"object"`
}

// GenerateChunkObject defines model for GenerateChunk.Object.
type GenerateChunkObject string

// GenerateChunkChoice defines model for GenerateChunkChoice.
type GenerateChunkChoice struct {
	// Delta Delta content for streaming
	Delta GenerateDelta `json:"delta"`

	// FinishReason Reason why generation stopped
	FinishReason FinishReason `json:"finish_reason,omitempty,omitzero"`
	Index        int          `json:"index"`
}

// GenerateDelta Delta content for streaming
type GenerateDelta struct {
	// Content Token content delta
	Content string `json:"content,omitzero"`

	// Role The role of a message sender in a conversation
	Role Role `json:"role,omitempty,omitzero"`
}

// GenerateMessage defines model for GenerateMessage.
type GenerateMessage struct {
	// Content The generated message content
	Content string `json:"content"`

	// Role The role of a message sender in a conversation
	Role Role `json:"role"`
}

// GenerateRequest defines model for GenerateRequest.
type GenerateRequest struct {
	// MaxTokens Maximum tokens to generate
	MaxTokens int `json:"max_tokens,omitempty,omitzero"`

	// Messages Conversation messages (OpenAI-compatible format)
	Messages []ChatMessage `json:"messages"`

	// Model Name of the generator model from models_dir/generators/
	Model string `json:"model"`

	// Stream If true, partial message deltas will be sent as SSE events
	Stream bool `json:"stream,omitempty,omitzero"`

	// Temperature Sampling temperature (0.0 = deterministic, higher = more random)
	Temperature float32 `json:"temperature,omitempty,omitzero"`

	// TopK Top-k sampling (Termite extension, not in OpenAI API)
	TopK int `json:"top_k,omitempty,omitzero"`

	// TopP Nucleus sampling probability
	TopP float32 `json:"top_p,omitempty,omitzero"`
}

// GenerateResponse OpenAI-compatible chat completion response
type GenerateResponse struct {
	// Choices List of completion choices (currently always 1)
	Choices []GenerateChoice `json:"choices"`

	// Created Unix timestamp (seconds) when the completion was created
	Created int `json:"created"`

	// Id A unique identifier for the chat completion
	Id string `json:"id"`

	// Model Model used for generation
	Model string `json:"model"`

	// Object The object type, always "chat.completion"
	Object GenerateResponseObject `json:"object"`
	Usage  GenerateUsage          `json:"usage"`
}

// GenerateResponseObject The object type, always "chat.completion"
type GenerateResponseObject string

// GenerateUsage defines model for GenerateUsage.
type GenerateUsage struct {
	// CompletionTokens Number of tokens in the completion
	CompletionTokens int `json:"completion_tokens"`

	// PromptTokens Number of tokens in the prompt
	PromptTokens int `json:"prompt_tokens"`

	// TotalTokens Total tokens used (prompt + completion)
	TotalTokens int `json:"total_tokens"`
}

// ImageURL Image URL or data URI
type ImageURL struct {
	// Url URL or data URI (data:image/png;base64,...)
	Url string `json:"url"`
}

// ImageURLContentPart Image content for embedding (OpenAI-compatible format)
type ImageURLContentPart struct {
	// ImageUrl Image URL or data URI
	ImageUrl ImageURL                `json:"image_url"`
	Type     ImageURLContentPartType `json:"type"`
}

// ImageURLContentPartType defines model for ImageURLContentPart.Type.
type ImageURLContentPartType string

// ModelsResponse defines model for ModelsResponse.
type ModelsResponse struct {
	// Chunkers Available chunking models (always includes "fixed")
	Chunkers []string `json:"chunkers"`

	// Embedders Available embedding models from models_dir/embedders/
	Embedders []string `json:"embedders"`

	// Extractors Available GLiNER extractor models (zero-shot recognition with custom labels)
	Extractors []string `json:"extractors,omitempty,omitzero"`

	// Generators Available generator/LLM models from models_dir/generators/
	Generators []string `json:"generators"`

	// RecognizerInfo Detailed information about recognizer models including capabilities.
	// Map of model name to model info. Use this to determine what capabilities
	// each recognizer supports (labels, zeroshot, relations, answers).
	RecognizerInfo map[string]RecognizerModelInfo `json:"recognizer_info,omitempty,omitzero"`

	// Recognizers Available recognizer models from models_dir/recognizers/
	Recognizers []string `json:"recognizers"`

	// Rerankers Available reranking models
	Rerankers []string `json:"rerankers"`

	// Rewriters Available Seq2Seq rewriter models from models_dir/rewriters/
	Rewriters []string `json:"rewriters"`
}

// RecognizeEntity defines model for RecognizeEntity.
type RecognizeEntity struct {
	// End Character offset where entity ends (exclusive)
	End int `json:"end"`

	// Label Entity type (PER, ORG, LOC, MISC)
	Label string `json:"label"`

	// Score Confidence score (0.0 to 1.0)
	Score float32 `json:"score"`

	// Start Character offset where entity begins
	Start int `json:"start"`

	// Text The entity text
	Text string `json:"text"`
}

// RecognizeRequest defines model for RecognizeRequest.
type RecognizeRequest struct {
	// Labels Custom entity labels to extract (GLiNER models only).
	// When using a GLiNER model, you can specify any entity types to extract,
	// enabling zero-shot NER without model retraining.
	// If not provided, the model's default labels are used.
	Labels []string `json:"labels,omitempty,omitzero"`

	// Model Name of recognizer model from models_dir/recognizers/
	Model string `json:"model"`

	// RelationLabels Relation types to extract (for models with 'relations' capability).
	// Only used when the model supports relation extraction (GLiNER multitask, REBEL).
	// If not provided, the model extracts all relations it can detect.
	RelationLabels []string `json:"relation_labels,omitempty,omitzero"`

	// Texts Texts to extract entities from
	Texts []string `json:"texts"`
}

// RecognizeResponse defines model for RecognizeResponse.
type RecognizeResponse struct {
	// Entities Array of entity arrays (one per input text)
	Entities [][]RecognizeEntity `json:"entities"`

	// Model Name of model used for NER
	Model string `json:"model"`

	// Relations Array of relation arrays (one per input text).
	// Only present when using a model with 'relations' capability (GLiNER multitask, REBEL).
	Relations [][]Relation `json:"relations,omitempty,omitzero"`
}

// RecognizerCapability Capability that a recognizer model supports:
// - labels: Entity extraction (NER) - extracts labeled spans like PER, ORG, LOC
// - zeroshot: Supports arbitrary labels at inference time (GLiNER models)
// - relations: Relation extraction between entities (GLiNER multitask, REBEL)
// - answers: Extractive question answering (GLiNER multitask)
type RecognizerCapability string

// RecognizerModelInfo Detailed information about a recognizer model
type RecognizerModelInfo struct {
	// Capabilities List of capabilities this recognizer model supports
	Capabilities []RecognizerCapability `json:"capabilities,omitempty,omitzero"`
}

// Relation defines model for Relation.
type Relation struct {
	Head RecognizeEntity `json:"head"`

	// Label The relationship type
	Label string `json:"label"`

	// Score Confidence score for the relation (0.0 to 1.0)
	Score float32         `json:"score"`
	Tail  RecognizeEntity `json:"tail"`
}

// RerankRequest defines model for RerankRequest.
type RerankRequest struct {
	// Model Name of reranking model from models_dir/rerankers/
	Model string `json:"model"`

	// Prompts Pre-rendered document texts to rerank. The client is responsible for extracting
	// and rendering document fields/templates before calling this endpoint.
	Prompts []string `json:"prompts"`

	// Query Search query for relevance scoring
	Query string `json:"query"`
}

// RerankResponse defines model for RerankResponse.
type RerankResponse struct {
	// Model Name of model used for reranking
	Model string `json:"model"`

	// Scores Relevance scores (one per prompt, same order as input)
	Scores []float32 `json:"scores"`
}

// RewriteRequest defines model for RewriteRequest.
type RewriteRequest struct {
	// Inputs Input texts to rewrite/transform
	Inputs []string `json:"inputs"`

	// Model Name of Seq2Seq rewriter model from models_dir/rewriters/
	Model string `json:"model"`
}

// RewriteResponse defines model for RewriteResponse.
type RewriteResponse struct {
	// Model Name of model used for rewriting
	Model string `json:"model"`

	// Texts Rewritten texts (array of arrays, one per input, multiple per beam)
	Texts [][]string `json:"texts"`
}

// Role The role of a message sender in a conversation
type Role string

// TextContentPart Text content for embedding
type TextContentPart struct {
	// Text Text content to embed
	Text string              `json:"text"`
	Type TextContentPartType `json:"type"`
}

// TextContentPartType defines model for TextContentPart.Type.
type TextContentPartType string

// VersionResponse defines model for VersionResponse.
type VersionResponse struct {
	// BuildTime Build timestamp
	BuildTime string `json:"build_time"`

	// GitCommit Git commit hash
	GitCommit string `json:"git_commit"`

	// GoVersion Go runtime version
	GoVersion string `json:"go_version"`

	// Version Termite version
	Version string `json:"version"`
}

// ChunkTextJSONRequestBody defines body for ChunkText for application/json ContentType.
type ChunkTextJSONRequestBody = ChunkRequest

// GenerateEmbeddingsJSONRequestBody defines body for GenerateEmbeddings for application/json ContentType.
type GenerateEmbeddingsJSONRequestBody = EmbedRequest

// GenerateContentJSONRequestBody defines body for GenerateContent for application/json ContentType.
type GenerateContentJSONRequestBody = GenerateRequest

// RecognizeEntitiesJSONRequestBody defines body for RecognizeEntities for application/json ContentType.
type RecognizeEntitiesJSONRequestBody = RecognizeRequest

// RerankPromptsJSONRequestBody defines body for RerankPrompts for application/json ContentType.
type RerankPromptsJSONRequestBody = RerankRequest

// RewriteTextJSONRequestBody defines body for RewriteText for application/json ContentType.
type RewriteTextJSONRequestBody = RewriteRequest

// AsChatMessageContent0 returns the union data inside the ChatMessageContent as a ChatMessageContent0
func (t ChatMessageContent) AsChatMessageContent0() (ChatMessageContent0, error) {
	var body ChatMessageContent0
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromChatMessageContent0 overwrites any union data inside the ChatMessageContent as the provided ChatMessageContent0
func (t *ChatMessageContent) FromChatMessageContent0(v ChatMessageContent0) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeChatMessageContent0 performs a merge with any union data inside the ChatMessageContent, using the provided ChatMessageContent0
func (t *ChatMessageContent) MergeChatMessageContent0(v ChatMessageContent0) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsChatMessageContent1 returns the union data inside the ChatMessageContent as a ChatMessageContent1
func (t ChatMessageContent) AsChatMessageContent1() (ChatMessageContent1, error) {
	var body ChatMessageContent1
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromChatMessageContent1 overwrites any union data inside the ChatMessageContent as the provided ChatMessageContent1
func (t *ChatMessageContent) FromChatMessageContent1(v ChatMessageContent1) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeChatMessageContent1 performs a merge with any union data inside the ChatMessageContent, using the provided ChatMessageContent1
func (t *ChatMessageContent) MergeChatMessageContent1(v ChatMessageContent1) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t ChatMessageContent) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *ChatMessageContent) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}

// AsTextContentPart returns the union data inside the ContentPart as a TextContentPart
func (t ContentPart) AsTextContentPart() (TextContentPart, error) {
	var body TextContentPart
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromTextContentPart overwrites any union data inside the ContentPart as the provided TextContentPart
func (t *ContentPart) FromTextContentPart(v TextContentPart) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeTextContentPart performs a merge with any union data inside the ContentPart, using the provided TextContentPart
func (t *ContentPart) MergeTextContentPart(v TextContentPart) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsImageURLContentPart returns the union data inside the ContentPart as a ImageURLContentPart
func (t ContentPart) AsImageURLContentPart() (ImageURLContentPart, error) {
	var body ImageURLContentPart
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromImageURLContentPart overwrites any union data inside the ContentPart as the provided ImageURLContentPart
func (t *ContentPart) FromImageURLContentPart(v ImageURLContentPart) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeImageURLContentPart performs a merge with any union data inside the ContentPart, using the provided ImageURLContentPart
func (t *ContentPart) MergeImageURLContentPart(v ImageURLContentPart) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t ContentPart) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *ContentPart) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}

// AsEmbedRequestInput0 returns the union data inside the EmbedRequest_Input as a EmbedRequestInput0
func (t EmbedRequest_Input) AsEmbedRequestInput0() (EmbedRequestInput0, error) {
	var body EmbedRequestInput0
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromEmbedRequestInput0 overwrites any union data inside the EmbedRequest_Input as the provided EmbedRequestInput0
func (t *EmbedRequest_Input) FromEmbedRequestInput0(v EmbedRequestInput0) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeEmbedRequestInput0 performs a merge with any union data inside the EmbedRequest_Input, using the provided EmbedRequestInput0
func (t *EmbedRequest_Input) MergeEmbedRequestInput0(v EmbedRequestInput0) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsEmbedRequestInput1 returns the union data inside the EmbedRequest_Input as a EmbedRequestInput1
func (t EmbedRequest_Input) AsEmbedRequestInput1() (EmbedRequestInput1, error) {
	var body EmbedRequestInput1
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromEmbedRequestInput1 overwrites any union data inside the EmbedRequest_Input as the provided EmbedRequestInput1
func (t *EmbedRequest_Input) FromEmbedRequestInput1(v EmbedRequestInput1) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeEmbedRequestInput1 performs a merge with any union data inside the EmbedRequest_Input, using the provided EmbedRequestInput1
func (t *EmbedRequest_Input) MergeEmbedRequestInput1(v EmbedRequestInput1) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsEmbedRequestInput2 returns the union data inside the EmbedRequest_Input as a EmbedRequestInput2
func (t EmbedRequest_Input) AsEmbedRequestInput2() (EmbedRequestInput2, error) {
	var body EmbedRequestInput2
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromEmbedRequestInput2 overwrites any union data inside the EmbedRequest_Input as the provided EmbedRequestInput2
func (t *EmbedRequest_Input) FromEmbedRequestInput2(v EmbedRequestInput2) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeEmbedRequestInput2 performs a merge with any union data inside the EmbedRequest_Input, using the provided EmbedRequestInput2
func (t *EmbedRequest_Input) MergeEmbedRequestInput2(v EmbedRequestInput2) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t EmbedRequest_Input) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *EmbedRequest_Input) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Chunk text into smaller segments
	// (POST /chunk)
	ChunkText(w http.ResponseWriter, r *http.Request)
	// Generate embeddings
	// (POST /embed)
	GenerateEmbeddings(w http.ResponseWriter, r *http.Request)
	// Generate text using LLM (OpenAI-compatible)
	// (POST /generate)
	GenerateContent(w http.ResponseWriter, r *http.Request)
	// List available models
	// (GET /models)
	ListModels(w http.ResponseWriter, r *http.Request)
	// Recognize named entities
	// (POST /recognize)
	RecognizeEntities(w http.ResponseWriter, r *http.Request)
	// Rerank prompts by relevance
	// (POST /rerank)
	RerankPrompts(w http.ResponseWriter, r *http.Request)
	// Rewrite text using Seq2Seq models
	// (POST /rewrite)
	RewriteText(w http.ResponseWriter, r *http.Request)
	// Get version information
	// (GET /version)
	GetVersion(w http.ResponseWriter, r *http.Request)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// ChunkText operation middleware
func (siw *ServerInterfaceWrapper) ChunkText(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ChunkText(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GenerateEmbeddings operation middleware
func (siw *ServerInterfaceWrapper) GenerateEmbeddings(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GenerateEmbeddings(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GenerateContent operation middleware
func (siw *ServerInterfaceWrapper) GenerateContent(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GenerateContent(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListModels operation middleware
func (siw *ServerInterfaceWrapper) ListModels(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListModels(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// RecognizeEntities operation middleware
func (siw *ServerInterfaceWrapper) RecognizeEntities(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.RecognizeEntities(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// RerankPrompts operation middleware
func (siw *ServerInterfaceWrapper) RerankPrompts(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.RerankPrompts(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// RewriteText operation middleware
func (siw *ServerInterfaceWrapper) RewriteText(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.RewriteText(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetVersion operation middleware
func (siw *ServerInterfaceWrapper) GetVersion(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetVersion(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{})
}

// ServeMux is an abstraction of http.ServeMux.
type ServeMux interface {
	HandleFunc(pattern string, handler func(http.ResponseWriter, *http.Request))
	ServeHTTP(w http.ResponseWriter, r *http.Request)
}

type StdHTTPServerOptions struct {
	BaseURL          string
	BaseRouter       ServeMux
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, m ServeMux) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseRouter: m,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, m ServeMux, baseURL string) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseURL:    baseURL,
		BaseRouter: m,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options StdHTTPServerOptions) http.Handler {
	m := options.BaseRouter

	if m == nil {
		m = http.NewServeMux()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	m.HandleFunc("POST "+options.BaseURL+"/chunk", wrapper.ChunkText)
	m.HandleFunc("POST "+options.BaseURL+"/embed", wrapper.GenerateEmbeddings)
	m.HandleFunc("POST "+options.BaseURL+"/generate", wrapper.GenerateContent)
	m.HandleFunc("GET "+options.BaseURL+"/models", wrapper.ListModels)
	m.HandleFunc("POST "+options.BaseURL+"/recognize", wrapper.RecognizeEntities)
	m.HandleFunc("POST "+options.BaseURL+"/rerank", wrapper.RerankPrompts)
	m.HandleFunc("POST "+options.BaseURL+"/rewrite", wrapper.RewriteText)
	m.HandleFunc("GET "+options.BaseURL+"/version", wrapper.GetVersion)

	return m
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+y9C2/ctrYo/Ff4qR8Qu0fzsJ2k6VwUB47jZHsfO/G2nd3umwnGHIkzw1oiFZKyPS18",
	"f/sFFx+iXuNx2/Rs3FMgQDwSuUgurjcXl36NEp4XnBGmZDT5NZLJiuQY/jxaYXVGpMRLon8WghdEKErg",
	"ZcKZIkzpP/9/QRbRJPpmVEEaWTCjAMaR7fEQR4Jn5LGeF7rNg25MvpRUkDSafDIdYz/45zhS64JEk4jP",
	"fyYJwO4YcfJrlBKZCFooylk0iex7ZOEM0WVZFFwoidQdRwsucqzkZMoG6JLmRUaQVIKy5QRNo7+RLOMx",
	"WvE7hAVBa17+5zTSLQ+FwGvEFw4oKrAGuPOhIOzwBOVlpmjOU5xZ+LsT9OnXKcx/GmnIityraRT7v/xo",
	"0+jh85RFccQZ+bCIJp+ay7GT1N3c6JHHjJl69BA3ez15wlEcUUVy+eieG3jnWMCG2HlgPVz08Bm2qGQ3",
	"7V05RIl+oacES7mjaoUKLql+jygz06CcDaO4QY2EpbNkhUUb6NEKC5woIkJIiAu6pAxndqAVEcQOTlgq",
	"0Q65T7JS0luyWyGSMkWWROgl0bQ90CX5UhKWEMTKfE4ErGLloO6MY7QXo/0YDYfDDphxdD9Y8oF9WlKm",
	"Dvb1QFJhof6glQEs2bke3bY9wJWffi9RNdiTppEFVpt6XO1PN8eW7OaIswVddqwSnpcCNl5TopkSZUuk",
	"RyZSMy1HV0TkVBF0eH4ynLKrFZWISoSR1KxBF5SkehELugQQemP+dnV1rpujAUrpYkGERAvBc3i3KLMM",
	"wbSIMBOYsrsVTVaIsiQrUyJRIfgtTYlAkmQkgclhlqIEJys9tySc9hC4t06xOb6fwUqkWfMCl5mKJi/G",
	"cVNW4Xual3lAVqabXrUgqhQaNrnHWgSY/u39zXlKsto40YLeE71bPVuu1wC99DClJEN0TNWKCPQMOj4D",
	"NEord/gNYYM5lhrJtnOMuEDYgmA4Jwa58FuOEoNaOfpVv3oYDcMl+Kk1BVjEb4nIcDGDAR/D23uPL9ut",
	"0GsyXdGcqDtCmEXl4wiUpMACKy7qSJwy2NkGDjXj+Q6AKFiRx01tsRZEa60KiyVR3UttrfUKGoeSxyyz",
	"IJZd6ivsXKJaCSJXPEtrg42HL+IujkxB1Pk+sMoP79//ZHcY7YyH48HecLwbjgzAjBTX25xxHIgUM3kQ",
	"Kd0S4sKwe6cpYkXHZkukkjL9Ik/vneJtpEWVSMk4W6KUJ2WulaZaYYUYISkw5JwgWWRUIcoURzLHWea2",
	"QA6Hw0cFKMzqcz8GZMGZBNPJz+zXSMscMltRFU0WOJMkjpxg+RRqxj2971pzjet6ZeyQ4dcIIpAKqczM",
	"9cS1+RCA+t6C2quD+r4bliQJZ2kA7LMXSZbZH5riMVhTc49+XBGQRILIMlPoDkskibglqREx0LNC9Jzz",
	"jGCmRwjFbachZAwoJxK2s3WAUFpWTk3k1pV2TbjiRJU4y9ZaxKZoJ8drq4zMWqyGIymiC7TAWTbHyQ3i",
	"SVIKQdLdbaRmg8D86sz84gDRnWTnWau+Pbigs1J0rO/jxamzfJxKJvmcpClly5HXLHq/aEJq818pVUxG",
	"o4wnOFtxqSavxq/GUSAvSkG7BKVGiabMQlAuqFrXxNeniDN2r82rDEdxtOR6lfUZvzb9keuPuNBqXQs0",
	"s0cZx3r2xhzl0A1nKCV6BUgWJNHmhZDDKXsLU52gazuna60E3Y+J6XFtbTLb384UhMc1LhW/HmqN4HCn",
	"BCUSEWb+B/NOT05bGqUkIafiW0wzPM8IsuP9hxlhyhKezykz9hNIK+mdnRUxa4Qxv/3WokJ++y3aSUmh",
	"scIZmpc0S5HCS7kLLtH1kl+jATovBUHvuLbLiQBtsIOzO7yW1VRidHT+EXGWrWMkM35HpNoFCHpTNAzQ",
	"GBclUzQnaMfSqUQDPdgPU9i7+MPFlfaKFlgq3/8+w7r7O352+hP66fSwo+99huOfTg9116vzj6Ojj28O",
	"R0fnH3fNSt8AbuS335oVAeLRAB2Wig9Sokii0JzUsLpjd8pMIClTmMH7f568OTlEGjp6d/7RvOOC5BmA",
	"K7R5dMQFOTvVzJ18uLTYAHafrwEBBqIqSrMkvsyInjLacY1+Oj20o5o2b7lIiEetWdCx4SO/ok8Ge8af",
	"vM+w+WPJp9FnDeJKrB2dSEPYGgUVUSpj0oagJnrNHt5EFaX5Yd65X36Ec0G0GHt3/jEGyQXDaSo/smjy",
	"YAFdjd4GVzAxiz6cJCQjxp6e1kzeT9X0DKPruYG3bCZmH5q/jATwor1tdjXEuPV8ZpIkpZMum/QBZmqR",
	"rQdLPsvoHC9mMhFYG54zXhCmpaZ1ji8tvMoguSGkmOGM3pK6jfkib1mYf+N3xgpRHOluzujSkkrrCoZy",
	"knOxRnih3cMMS6UpDu18yDKc44GeN1Z0npHd4ZSdmc5YECAC7WInRicxC9CAUVqjp84T4wtEGU4UvaVq",
	"PZyyjxKkQRp4aiALp9GLfBqhnRcop6xURO7qjd5b6Wd7aMVLAQ/G+jfBSz1dI2/11N4E0tEByvAva98G",
	"ZfSGILOsIbokyrTU0BRH5L7IaEJVtkaEARfXRtA+nRbFmjrzCglu0cp4zGUB4paRWyI8SoZ1EjSb1CKm",
	"jC+fSi8ZXy4b5GLpAxxGzkD1MzVzzm/dWt/CefQgAsntPWmcaTGtl3eYptSqOv/2jmo+JuhLSUqSorLQ",
	"SNbzggczSX8hwymzuzAGFVqyjGpNllYCtIG7550OK76fGUzPzM48dZl2Px2DtDhD0rzMFGaElzLT9Pvj",
	"ijBD4jBhbboKom2jNAY9mRHNRYIkhClnrxn7gMqKU3ZOLz4iLUT1xHa3QQb6wDR5LhZa4t4SbR0wVMkC",
	"DZ1xNviFCN5A3EEf4swSZ/l8O6RZjOxQhs5e71p/H+ZrF2Vw2Y0jXBSCWzT1osjwVcA7j2PFu1sM4fSW",
	"Sj1DM+jAGs123lNWQijX2CtSGyxmWzQ1SmBdbVUrkhdcYEE1su8TQlKzkFuclZpof+TiRpM/Z0tJU4Ja",
	"BGj9eEYGS4EpM/EkJXjWJOfx9y/7NqZik6eScxjqAiiGTnpkQkC81a5ZttXvFmWWxYiRuwqu3jVNbi/G",
	"B+jSWOfoI6vMH1DFF0SJ9eAQtMGK4JSI/r00gz1C533zn5bj8QFB4wZu98b90a2ZVAIrsnQOihdf541A",
	"cZlrkwEUQRRHWptEcTTnJUtJGvhAlRSv7805EYO6X2AHXkOcSdCUyCE6w4UMgl+wb2pFqGj1qhQw41ok",
	"G7LMcQFcqLfNorAax0TaeCgmwOg7WQRPDArHfges/tydoFCBoh39h4aVkhyzNLZcalU+TTOy2wL9AyjY",
	"SV2ZWkiV1oxrKhPsbqBEFxRcab/dLWlqNmQahRgwiwIx09bJO1jCgYXmjkIQO4ZrX9fWMSK3hDVFq8dQ",
	"QRkLlQPMFQQQqEOJcnqvV2jWqyUKoNDKBWqYS+KcoIK35MGv0evDw5PRfEkGEA4aEDa43Ru+iCaeBnMq",
	"1GqUrDi7WQ9yzfLKtoUzmIyyZYmzwV40MeTaFSEzk5mltOOg4DWWBKVUkERpMarlFqasCkLIcu7eUk28",
	"zvnE4A1RmWjClm69C8Fz42P8Wg36MDJePhFypO33Y+fz+3hg5enUuvlIsO5VD470dxJE4KrXBfzaqlvC",
	"l4z+UnWE32CuPtr1TlDlOl6SL/uX5AtyT5u964br/xkNlcHoyLWTRKFbitEtLYjYHWr20twviYrBpwOf",
	"Ww0oa0SOQSM6mdy0QVvjdJmkllXaRHJKpfKGUyW0bPsa53V6EVcrIkmHGU3znKQUK5KtDQM66jLHUTHC",
	"t5wCpUAcY2B1AMqwIizx4tHOSK54mWmNrpIVUisuCbCt36mADNEOGS6H2rfoZsBppKe9vfVV9zxgzKYp",
	"+6mP1+MI7Hk6SjJaDG6pgtOSQaGXcbD/NI/UImimaE54qerO4jjqsyUgxKI4usNUgarGTvlDvJvrFSgS",
	"2wMuvUJrZ+j2uvNGH+9gLI0Hv5eb/8GfYxzZWcYosP4vnJo3hhgcy2hpa9sGtshz9A4rcofX6Mq8a9L8",
	"wbiTyuXBLBEkJUxRnMkn++wHlfsVQGmGUl0MtCdu6o/Au865gxN3E2msDtt9uBTtQDyaC0RzvIST6CoB",
	"YNN6rsi9qp/Bb25/osF/vDit9fn8EEcgxXuPXSgryo7VnejHfoXaC9dQwhSLlSCkkWTBli5/wWVaXE+j",
	"Fckyju64yNJpdF3LsQiaygnEklYmU0LTnu3x+XpTWkaF8V0N4NFMDAv/IUa1prA1mgxM++DnRDe0f02j",
	"FCs8gbejgi3/l2b/l8/j4XA4jR4e9EzrciRYujYQ4FAZfFCh9bYmuf5ckCYu0c4cJzd3WKQoENlPSRAJ",
	"sd0LbWsJ1jtMwASNzaoxgvzjElF6Dmnea1vOnmI4hWIVY3CK3dA3NbnUqwfayBElS7Cqe4RKlKR1xmsb",
	"IuA7zVgLquysAF33CmWELdWq4/CrIbrc4Y9h4S4BZlm/87zRSygZTT59Gg/He/sH8WA8HD9/8TIeD8ff",
	"vfr+c6yf7x88h+cvXn6nn7/6/nNw8NeDotZJYDhaL+lUQvMW7FiJdjgjcP5t0GUQXqMc/8djJ9JtHbzl",
	"YZ+xXCAOooW8n+RvIpWeLQzQ07mPQpikhQZS3eP6hKE1ym3O32NTMEC6Rn1LGZWrC4KlBtscxTxHd6s1",
	"WhJmY/pIKl4UcILpfHT9RLvonqg5z2YJzsCydYH5Bc0UeFGLkkHUDVp0OvLvzGDkaMVp0pHSuIBZz4Sf",
	"9ibZUlvig2allNx3acOU3BtZQiVKYGTnMmZUqs50rIwvC8HnHQR/ypdIv8JzmlG1DpPitLnlz/a0z2tP",
	"41iZZZru9f/abXDSpe1CVqmemxbusOgyQ1s5YICIClzcwGsXvVQ705kYeKkEwbnm7oBebGLd5eUxePcK",
	"aRW728qzMiivM/w2yzPpIoZSus6FBMGKpIG+a6UHtujPS4l2YpPBRBCfSlZYDa1VTjkbmoSUz1sl4Flo",
	"1SSD036LjUc3oY9HUpIpvC0O30Djh/gP4qwmonsIz0xx0wrfuEXUyQwee9MDEtwc4bXJqi+1+IrfEOaB",
	"mLn0Ml9FAU/KiO5d2DbZ2u2EP8tUJHWSf0MS8VdN3XbL6HU5cnzflRG3/+Jlr9trEuEU96sMlS907Ago",
	"GzTIzmzUWyKkkUCumUuZDiIiT06ZDlLtt7cvQjvVLo/3Gar+fcNSXULCwWhJ8hwPDgZ78wHt3HfDCjW0",
	"22SzhsJbICBxMN0pHNNIe0CTKVydIUrNHlgiL79lZ86WInmh512KuoW81xz3Ui8IQglVD8hCRD9APoPI",
	"tVhRNInRii5XRKAfUM4FQQKzlOeNPMXv4m2sQl7Mbh7JQr3ixeAGSTe5HZ8Uda8Ik5Sz2MX9bdr94flJ",
	"d865Hq3YjIP3ZZKRUlbDBaZCtFXmZZeF6blhM8tWrkJ9Um3e0LoNVboNCdd3g+7uDlYGQGxbtGMPk7K1",
	"M4D2tubChoG4We038t4YvYcAllQ4L9COSXmUuyaiCBcBqrneYYkq3Vwdb303fr63f/C8Wyh13Tk4RCWj",
	"X0qCKESpFtQmrpmLBzUs15hev0vyIhvgebK3f9DF79u5NJU91pmv7c2attIx75Du403VadPsmUaBO9B4",
	"12nil0+xYD92269bmlBusE1c8bFPG7tF1LRZd/a61WC0SUWdQqIQPC/Uk6Gabj1iR+GsF+CVfuuAmRxW",
	"Awv9RzDVLoHWwHp94nEHihpT6UK7C2R2uGH6DYLkVAGOAvp4cdKSN/0ZrVUntNMbyqvn43Y3o/98/eHi",
	"bvxf75Z8m3zwvvhyV8i2Z9GhPRvEljeZLI04r4tpPsZXHv1ecFb+TAXkUR8G3sadPSoEmDPzUOs0VYc5",
	"V+yQmT6nIWkeN1ox5O/4TE1S9TTarUdnXar11ge3Tzrg8SHFTXMnzQPW7QKTG06oul9M6Ksnzv5eCQwh",
	"uE3Tf3dK3x9fIN/Yb8EvRPCBXHE4BfKns5B9kpRS8RxleE4yudvOANW0nJeMqvVomVFGxMys5HZ/uGfT",
	"QVtNzEYpLG+etsrKmt60St9qdHp61rdRPYb5pz7LXK9DmJTp0Tv77sP79z899RTRnYXPKFvwTSkzGz09",
	"DwYY8kSDaqXMvCEK0wwyLKpoFZ7boz7bv0qncOePCS6M7UqJHE7ZGS7q59OQfGgy8NiCD9FHyJeh4Ow5",
	"i5+gOzCDAlBTRnCyCkf2+fA7hrZipKlQE2GMBMlgvjJGmMk7IuRuK8EjlRnNR8D9cKz7/vjCXGGpBtX7",
	"aYBHnx8ep8X+3nHk5hbpTbSTi+LIzq4ffMgNW8H/3BlqCJIoNpF+e2ObdB9mY9QJvwufcfg0w2LpHj+6",
	"1ieyhc0s2by2esJJj4B1sAa3+4P84KnzsPkmm+bRl4bSxrRLXqnPNMu/LEeLDLOBemGlvvxS4nTwZRnF",
	"9bewD/7lE5bSdf1ILytEdajyaqK1Tm0hVrpMAi+LjpmymfqtS+KbblHzxUISd2WaAIyu2+BBNmJn7F7z",
	"UcfJioGn26Od8+OLGH24eBej0w9HMTo7uTyq247nQNrtGEzCBem5Im0uZEILE/ZQHLXvX37//TaBDUjN",
	"eSqq5mRJWY0Xxk+7am7h2OvjFTL+zlcMXeY0PNjcdH3S7YFbB9w+jxz2NlJOb+DRSsc2SoxNYqduWpmb",
	"B2DYoB1r6FjO5Cxb77qU3FJqEYJR2CRGa16iBDN7sWyNMFt7zKwLEkKPpwyuNWgwld2kYWl7SatXox4F",
	"UcIk/A2nzKaa2evrNrkd2j2TPtXULgSytmXrtsOnqCBCggcK7gNbG58hLcFlTrEiT5N2j4Q3m7pka1XS",
	"o0naMW2rR2d923xhG7S2AO0sKuMVrNRnXik/q8yOtU81Ax/Zx4Rc/qW1P1xXBx1O9Rx5OOMgRhfHr49P",
	"dzfupYMAKayVEYOoAuIyF7xa27qwWdBxdMfFjZyBdMh4ghVJZ5Q9bVM1L8ruG9Y1DAJxU2LUVn0+Feej",
	"O5Ofr+wFOe05m9t1JywZIgqRjKMSOJbx4e/QUC7MY6b/iLTo8z7dmjZlLBiehkm0shX04N25ClsZ41YB",
	"/vbEBcd5eT3a9wj7bFquJ+0NC3Y8UggCpwN3oZQ0U9nAYhs55Tfg0gzxOBL78jIcCWwkIXHk59+hXKq1",
	"wb1d3JaETnRAGp2RXhNkbY1QiLw/vthFg0oqQFOSIllgJs0luppRosE5R2BSpe5hMadKYOFVHQ5vkZlb",
	"vDWNB6nUfrsm6KJDwrlaHF4Q9G6kBmb9nAk6thBu4WKLtBVY9EuIbzVh7BphZ8NRW3tTHeTe5fN2nCX3",
	"+rztbWwffNScs97Tj6CV8Xx76aNh+Ld9vfiJIiYk3C6W6CB5y1AtYbkiJh/9iaKtx9DWlqTfyRUtkA0n",
	"BoUSvJb7zQa2O2PxUm2Dxf1iq6NETLMn46AheQCPFlRgA2+werUD1n/W/phRVnOCO2wyd0ejO9ut4R13",
	"XlXgedFlQpwL3Z2lRJA0KMTiDAsDeYigllFG4aardIeMLtLtBRBbThlmKTIAaVjaZUFJlsqRInmRYUUk",
	"mpOF3v0EZ5lPWicsLThlbWPqhCljEoPdyFEzideE/9/A7VT7CC1KlmI9Ns6gXMyTDK4vJRHrrrpkWCQr",
	"BG9h5YJk5BY7Ym6mIzaniXBRZDTxknG7rEQzl2oPN9FfnxH1NNvE02MvX3fb9QEqSGCWmInH5lqXLboh",
	"jbFSM8yemjvagy87wW40QdBjcxq+7MvDD7gCwIyUwEzqWdep9Uo/1lSu274jIsdsgjpqHf6hjl13AGvL",
	"+NUj4avt6NQibyPe/yj61OB66LPHVzJTUNpZhG3cwc6cNlZ0jGpWdGysHe0V6WdzgvNuJ+Jx3+13ekg2",
	"R6xDM/MMkIN9WpAEuavdN0i989lVYR7wWiqSw4E7ZPpiKalUuJZEVq2lefulu8ZX56loyw7bUCSsecGl",
	"c1sbh6CN6l6bzz97S4H9kwhJOesnTCjYA/fDOu6CmmI+LlGlxlD74/3ng/HeYO/F1d54cjCejMf/u2tZ",
	"S6pmCc/zruJc7ygkneRUoRWWqxp8k2zyvBMkn92aZXWA5MiedyHXpp7AtjfcfzEcd4HthenSsLoA3u4N",
	"x13gGttUdQ3wEYfIry2rayebF8/cgXR1/eyvQql/FUrtp5eeYjFdtwaWraKkIPr8ZVxT8kG26CUjtyT7",
	"vUVsTgEI7NL68ezhx6BdApBOJ3O7idRuzMLpd9yDsFsi5ppk1sjgodJJKZmXSzAgoPsdNmVY3Y2YSprY",
	"Bi3RtN0qa1M1R9o4650uL5W2+Qz7I0D2ED1z3UzN1oRnXNBfTP0SyTMSo2c/S86euYT3MlGldqz+fvnh",
	"fYyeZXy5yJV5awq9ksWCJuBW3ZD1D1BABRWYChmjZ4zzwtWGzQhTwwBlwfR/NqcHBnYUR7pbHW1B40dR",
	"13Nft120MEmIlLMbsp51JlP+eIlME70wdPImuLN6Q9ZSad9PrpnC92aFJBFEoYzzm7IYorc4y6Svcnb4",
	"4+Xs8Ojo+PJy9l/H/5qdvEGE3VLBGXiWt1hQOMKl/uJ/vQTumpdiYCYzuCHrAe20L5zv2SFjD8LMLtfO",
	"XYl/Jg+GOMe/cIbv5DDh+TPEhd5qV3rx+/F4bLbxjLKTD/XDyWZnSIRip+aW1mSvy/0CTM0q/Hcj3yK0",
	"2oPfuwGXx0cXx1fBPvyGTTCDBHvR6V8SKX2qYlcKtK2kZVYJbQ0zGbaytYnWKLi0/qS1d00bRhmYGXVm",
	"ypKZlNmj106PTeG0y8vT0dXpJYx9eaBlBzMlAqWvMDOBxH9ocfjjJVT983WkEpxVpNRxOfVRSb5lHb02",
	"z5uCZjNN1rKrlixVJLPxVNsW6bZQbmJ0cm7qPmWU3aCU30E9GQn1OkheqHUMx2sA29TPsxC0WUQKhQpB",
	"b7VPreHQBZpnPLmZ2YczWpgCuaIku8O6N27/tNyVpGxYf7L3/f5wPHxydotDRoHValtk6LaoEGRB74kr",
	"gpWRyWgEhXDkgf7r48VpCykwRoiUIXobdC4lQXgueVYqYtta4TT6KLWrn2KFR7umkxlFd5mXyQ1RIzMf",
	"1yNfD+zzsoANGjXxGcLU4qrV4Wl4bO3jo1z0WveoVfGqSAMJzOAW0d7+d9rzGI5Hr2K0Nw7+/m5/uPcS",
	"fu3tx0jv/t7LV+b3yxjtvfx+uP/iuf2923mPxhGvKxsysxcUajM/aF9fsSU59L5TltJbmpY486yAeGHT",
	"/+EA1sEMi9SNQTvQXNsAe32F0fzsJP2FzOZrReoT2xs/f/Xiu5fj3kppup+mWgfIlmczVQ6RAVhL3fHw",
	"/OTGj/galKmXz92ETXJySnNziad+G238/FXfPKEfuqOpWo1WhC5XML+C3kPyqylv4K9ICaKXVS/zbIBv",
	"wmhbmj48WDvVXgTE5k6GFnFa84KkjWKT/Q5lmOVkNFpStSrnWt5Ygzydj2x5oXaGp3MjTME+Wx8IThWN",
	"6K/OCKFSt/Dl4u1XA85OqyKDU/bNN+jHFYaovQUclkS22Q7SaZXTALqpZOtnEJhAh+cncEb67bdVaap3",
	"/vLKt99OEER1oFxgVYZi5+j05Hy3lWxtAEEHV7JKQ7gkOWaKJlViOcwnLIvvvgUwAIJ1Fb0NPF/HSsOq",
	"ItOCDGyc3ip+COeb4ud2Ju9xTlJ37BtUtdKA7DEpMik7MkZcLDGjv7isVkjvAAY2X78g9ypY3oWLWgKG",
	"XOjYuMzmZN7FcF0Ctz+Lra4GxfbwIXxCVDI0lbKcKIEb8VgRKCGZEawVhEKOHA0NDikfpTyRI6+LPb0Q",
	"OGT5KEkXzSSYIVEy7dmzFGecEfg8RVVBDjNk+AAlWSkVEUAsp0Bh1f41KE0LRnKviADT7vzE1qAkLIE0",
	"40EHGV6PcEFNbv51ZZbXgpDQ05NSVZLeEcDF4TtU0IJklJlRQlJxZ3Igr3PNKiR1JPOlxBlVa93liDAl",
	"cAZuoD0oJuIWTnsSwaVEKdXab14qkiLGUzPQuVZZyXoA+RmmeY374GaMLb2XEXxLJNK2qG4hsPcsd+2W",
	"vSVwR9Pu4Deoiy8NJZq7HpoCQ1aqVadzxf97a9IZSIfnJwBmu31xbGnirMhUd4d5vKZMm+u+umUM3rJb",
	"yVklQKwNbwWJAWiu5fjlAkD9GgWFRn8GutCbPzAqoxJBssAJsZDgiCecF1wy8neVJNq57r2tdL2reUCb",
	"bgaYvRB05JGiAX6URDaK8djows71b6qDZCseXVtcaH49whLqliODGEOtMQJCHBg0CqIEJbc4i9EtldoC",
	"kTSnGRZAzwbrNXHcJJy3ldD1zNQqV7+L/iOksAAGemPpbK2BHfbWRewtbmhgHZmPA2kY+wNTDhtdXZ26",
	"CrzwKQbT8q3VDDD3ml/bLAjoDpoWmGael7wq2XYNIWN1LCQouGgg/qPU4ukXrzwP64XDNdV8MU2qGsB0",
	"UaE6oF/dvXaiDyLPHhyjHXuCv8IszbQDQkmWBtlDJq0nowmxRyHOqskydKHtK4kuiPk8SMvEqXRKRpYY",
	"ApSKKvO1l+pzUlFwjBDd7uGsWOE9uN1qPNFoEh0Mx8ODKI68X2V2HrxRLrvCM0VGtRugV9rxpRirWqVT",
	"AnWroXFtzZlMZ5ZoDQUAwVcFNdu0HnzcLvx+E3y9RlWfuzCfTtKNP7ryjj/4a3H68VssjdlUu2TvpgF0",
	"debZqW0h+Vq2TsiEjD1AZ5tkfXBEXOe0J3MMspypf10YywpcV+DIsGy4ls37rpL9ELoRiBb6O4Nzrlbu",
	"U2MaLeFH+dxW2Y816F/X19c/S63ofp0yVCs41/PBIRCgsWlshjEiliGkH8HSDAC7SbF7VfuilG7yYjz2",
	"L+uf1jJv/Uv/MSsDeDpl+l+kXz9M2QOswnyg0LmDJ6n71s2VOeSwru9rnq4b9UiC/JLRz7Y8jDkK2Orb",
	"Oy4v4qF+xKKdcHhglDdw5f54/EePbY9gYfCuQ2IgyxTJEsKHizLLIIDw/A+cianw1TGDE3aLM5q6qIMe",
	"98WfM641ia2vR2zDOJJlnmOxdqTRIf8kWeZQC0Q3N/ZYvxR1t+ylLfoW2NA2YBFWojQyNWuY9NJ9LdAb",
	"41QGhQ2tBwf24jNZNxOtIWQiuPcqNnlkUNgjhUx707d1zzrwL216JsAITMC2SG98o2OjLAwrMVdle235",
	"Vu1lmVWYHoEXojhUJAu+eRPMxnmEAyhPnFvDykXguu8O707QYQJx0LCApDVJKiQ0gYGpXO+qEWuDI7cU",
	"V/atxVPNDjbFu4MSo4A1XxftqxYc7aqN3F+EdKu6o8Zg/jpVRzuqAOz+ToUYfF0ETjKS8PshGL57lZZG",
	"5JB0yqyhA9uxyCAeZopOQ0U3QdKSpZgpuP7huKLpkOnH/qzEZ0D5/By4saOpxhKU+XCB/e5TIP14ooga",
	"mDJH197Fk0RQ7SjbNF/r8MUo51IhfxK624KmZen1BNxCX9/GCITgAjPIi8DvD40DQ8ea6sKiDS3qmrRN",
	"iMAE6Kt8be0HEJC65acG7WuiaiaCTqPPla6fsrPOisVteto8wU1lsbumCQbJozyDUbHiiptEswQrzUAd",
	"XX8fF9lKHpaZNPjPG2whp6sqt/8rGUW1ms1/slFULxqrx+5jsDrMxlkJcN7AcR5J29Vdw2JWc2jekXHT",
	"Mkwq3Acl7/5dTLPn4+dff1xbSp9ri6Nk6b+VSeg4JJCIxgr0hfu2MASDwLSx9ILCG9a8gJoZ6GB3OGVv",
	"9aa3rD1tItlibEcrrNCRL0Uk7eelf4dxFlT7+AOts2++Qb5GKqhDotC14TRzKn9tUsBNXf1L2ITBpVaP",
	"x1B6D8qo7prlU5YIYu4gTJlJUjCl+4boGCcrW2zVfkREu6fXGksVksC0v7b1vcyHIWwdTVR9bdCEJdGn",
	"Nx/eH3++HnbYcfoRRB976sdZ69uoVFeIEU5oN2ucrqoqXtM4QHVlI3hmNYbJRDbqwnKMefEvXpr9RyuS",
	"FYsyQz5JeVjTPhWsUhLRAQly7v+/aWQ0ipuXr3upG+2/eGmfG7zqZ5BsEernypJAO+85G/hSprs27DDH",
	"cjXV1lqGBj+h8w+XV6jzE6xAjo4H0XSqRx78DU3dNw4GV+uCTFBTakwj1zZFz7rCExs2orUV2yDOHRk2",
	"7Zb/nEYPnyuwNUzujccQxHjWibbL/9dR5mmtwk9FUVps1JDTa9Mc+aTXr2HQNIvC/sk2TavA5YNNAx6B",
	"IOy0Z7auL92lK496qmMO0QV87V8ap0I7Xizka+9mxVPGRZeQr1U0rryynVBRwGXpv8ygP9UM0qMffP3R",
	"3wW19u0X/srgC387jDtLyeWJk3S3z0gLDC1tYnU4fsZ4q77euSSq64aTIWlt2kjw19oV7mIfu4+rE+64",
	"Kq4Wo/fHFzEylzhrlZB8vN1FxEwkq33Y1R09023/4U+xIF1Us9EK3xJ0PaCvrpEsFwt670Im9gzCDHLY",
	"V0sQ7biPe0HU4DwrJRR52Tir8HzDBkHsidwWS2qc3h3nhVqbpNf2hlvw77yZauA369f1mbTbwq/ukW+3",
	"gODDbfCRP4fVenkdLeA6Cwj6Ue1FQjNmI3WlY1j/0Tfd/OpFjN6eHr4f6D9eH15cGZo7PfvHO9SR9eJP",
	"kWsOQuAbaOvf8mH4oeHEfbezpW9PqVRnruLYV1N4jcqafeJTukP5/y4f+jX+9zzaOO3y0oww9HTc78p6",
	"xpAQIkyDqhiPZnDZrKoqkcsKaOAt0frYoZeOJm9M26QmlgpJUiJFR/z96Wmt+JRNoTs/voBTe5iQ/TKf",
	"/9peVbRnGtksjw8X7yDtJpx31cFU9DHmaVXTx3c+/XCkO5/6PDXf8T25Q//i4sZ0fSswS4jvdnZyCf3O",
	"qExIlpkvPXtstnz46qh5Gy++JZB8/PlLW1/smO/T0ldDztg9TO+oEXL4WwkXeN7ihKDXxxdX9jC+vWe6",
	"c13muSOkpKsS2S3FJqZgfl+jAgucE0XE4yfRgd/RUUbLu8xwC9jGkDfUa2pub6tkUy283BJ99doXlHyt",
	"6GmrEtyf7G20a0t1xTGdSLBpMH9FMf8nmO/h12p/s/3u6auhXZx+0obiJuU0sHUyit6ELZ/QU5UZURxh",
	"mwJcU0j1KqpOHR2ZhK8LV6/Fl+01oUSbD5aXUk2mbG/oE5zteK5sixHaLmtGTtm+dqCh1oC2tn1Rlyk7",
	"GKJLwtKONblPHmKJru36rv23oVMi6dJ8LFaGH7VVJCPSfHjefj7aTBlufRgprfFf1ZvJ+JImw9+tkWo2",
	"foc+clFw02vmX4BWMvmY9Sy+QpAFEZ0qrZ7K9wRN0lP+x2sToBLTdGMhGt/BbksQsJ22Ku+cWUinFtIE",
	"wQYuS5oSZBIgq6wqDQCK8rjW6G1QlGeC3pNS4AwxoqyKEwQ6Nw4Ap+wtF578vD53JA9av5nLGPtPvhuK",
	"GUiakim7zuh85LtqHZ7cwC2SFU1WPjGyoqfHqxQ1dasGfW4r9XwtvRrWmvrTlWqt0FCHbLWLtxv0lz79",
	"n6FPHTP+Dm2qQVSqb10pPadQIYKwSaM2qjJtulrTEYAAh+/3645anKMxLIS7CEt4SgToihilBH4NKKPK",
	"PjIZwFUjuOgpu3ydLeIl33yD/MUAl3z2D9ejfmvLByQdRKv4TQHHgfswLtQn8IDEug+KrIqluZK0oQ0B",
	"zi8WuFgJLP1NLcCeS2ZEKV3AhRhIWkrdXTFbXsvdNauqbelergJmhtmyhBOclk7V2qQLaRVKDfo2H35u",
	"KJlVz7ZxHt2yid4Jmpbj8UGyyuB/gl6TNddGXs9jqbCAYJdEx0ph9HcIFmjPD6c0y3ACoUCRykcdQMDy",
	"V8wmbtRZ+9N1VL3aWF9GsfAlwf5SUX+d2GylowLx1KVXjKYKKmVtPKhpFM6K0dIX/IrR3BcXMwqhXblr",
	"2HGIrP7pK2l9NfZq1kzrQLZtEpbP+u+JZTcO3JTDXX1m0AyIUkaTT331zQ7PTyzp+ttPI1zQ6OHzw/8N",
	"AAD//33SWDL5owAA",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	for rawPath, rawFunc := range externalRef0.PathToRawSpec(path.Join(path.Dir(pathToFile), "../../../antfly-go/libaf/chunking/openapi.yaml")) {
		if _, ok := res[rawPath]; ok {
			// it is not possible to compare functions in golang, so always overwrite the old value
		}
		res[rawPath] = rawFunc
	}
	for rawPath, rawFunc := range externalRef1.PathToRawSpec(path.Join(path.Dir(pathToFile), "../../../antfly-go/libaf/logging/openapi.yaml")) {
		if _, ok := res[rawPath]; ok {
			// it is not possible to compare functions in golang, so always overwrite the old value
		}
		res[rawPath] = rawFunc
	}
	for rawPath, rawFunc := range externalRef2.PathToRawSpec(path.Join(path.Dir(pathToFile), "../../../antfly-go/libaf/s3/openapi.yaml")) {
		if _, ok := res[rawPath]; ok {
			// it is not possible to compare functions in golang, so always overwrite the old value
		}
		res[rawPath] = rawFunc
	}
	for rawPath, rawFunc := range externalRef3.PathToRawSpec(path.Join(path.Dir(pathToFile), "../../../antfly-go/libaf/scraping/openapi.yaml")) {
		if _, ok := res[rawPath]; ok {
			// it is not possible to compare functions in golang, so always overwrite the old value
		}
		res[rawPath] = rawFunc
	}
	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
